### ISSUE TITLE
crates release and misleading readme

### ISSUE THREAD

**Issue by extrawurst** [Azure/azure-sdk-for-rust#100]
TL;DR;
when is the new repo used for a crates release?

the current crates release is based on the old archived repo which refers to this repo here. confusingly this repo here then refers back to releases on crates.

now I am using the current crates releases:
```
azure_sdk_core = "0.43"
azure_sdk_storage_core = "0.44"
azure_sdk_storage_blob = "0.45"
```
to access the azure blob store. this is 3months old and lacks some api methods that are already implemented in here. 

how are people using this new repo right now? direct `git-ref`?

**Comment by MindFlavor** [comment]
Hi extrawurst,
sorry for the confusion. The release crates refer to the old, archived, repo (and no longer maintained as you have noticed). All the development currently happens here.

This repo is still in the "incubation" phase. We are deciding the final approach for request builders, http clients, etc... and we do not yet have a release schedule. 

For the time being I suggest you to reference the repo directly. I'll leave the issue open to update you on this topic. 

By the way, would you prefer a rigorous release schedule or a more relaxed one (and possibly more agile)?

**Comment by extrawurst** [comment]
Hi @MindFlavor thanks for the detailed response. 

I suggest for the time being to update the readme, I find it still often is not commonly known how to reference a git repo directly without using crates. And also giving this disclaimer you just gave.

I prefer regular updates - more agile, if you will - as long as the lib is not called `1.0`. To be honest I would even consider already starting where this lib is at right now with some `0.1` release on crates, cause it makes much simpler for people to work with. If I want to not get any breaking change I can pin to a specific release and the `git-ref` is still there as a fallback.

My current project is actually building upon this lib to access *azure blob storage* in production in the coming weeks and I would like to migrate to this repo as soon as possible.

**Comment by rylev** [comment]
We're working hard to get to a point where we feel comfortable to release these crates as 0.1. Obviously, we don't expect our 0.1 release to be perfect, but we'd like to get to a point before we release where we're not making extremely large architectural changes on a daily basis which is happening right now.

**Comment by rylev** [comment]
Going to close this since it's now addressed in the Readme. Let us know if there's any further clarification needed. Hopefully we'll have 0.1 releases soon!

**Comment by extrawurst** [comment]
@MindFlavor @rylev thanks for clarifying things. 
but now I am wondering: the readme suggests not to use this lib yet, the old one Is deprecated. 
I assume this one is based off of this one and not more unstable to use over the old one, correct? or would you actually advise to use the old one instead? (not concerned about interface stability, just regular robustness)

**Comment by rylev** [comment]
It should be just as robust from a functionality standpoint, we're just potentially changing the interface fairly dramatically.

**Comment by omid** [comment]
> potentially changing the interface fairly dramatically

Isn't that what "0.1" refers to @rylev? 

We cannot upgrade because of this library. Is there any estimation of when will we have 0.1?
