### ISSUE TITLE
`rust-toolchain.toml` causes `'cargo' component, is not applicable`

### ISSUE THREAD

**Issue by cataggar** [Azure/azure-sdk-for-rust#1009]
`rust-toolchain.toml` from #1006 is causing an error when I try to run `cargo`:

> PS C:\Users\cataggar\io\azure-sdk-for-rust> cargo check -p identity --examples
error: the 'cargo.exe' binary, normally provided by the 'cargo' component, is not applicable to the '1.63.0-x86_64-pc-windows-msvc' toolchain

> PS C:\Users\cataggar\io\azure-sdk-for-rust> rustc --version
rustc 1.63.0 (4b91a6ea7 2022-08-08)

cc @gorzell 

https://github.com/Azure/azure-sdk-for-rust/blob/2536038025b9532e6c93b8d4c00a85bf95b1c9d0/rust-toolchain.toml#L1-L3

**Comment by gorzell** [comment]
Interesting, do you happen to not use `rustup`? That is the only think I can think of that might cause issues.

**Comment by rylev** [comment]
I can confirm that on my Windows machine (where I do use `rustup`) that this works as expected. If it is the case that we require users to use `rustup` we should definitely document that. However, I'm not really convinced that the tradeoff is worth it. We upgrade to new toolchains very quickly, and we're really only saving users on old toolchains the hassle of being reminded to update their toolchain when CI fails.

**Comment by cataggar** [comment]
@rylev, do you have [rustup 1.25.1](https://blog.rust-lang.org/2022/07/12/Rustup-1.25.1.html) on your Windows machine? `rustup self update`

**Comment by rylev** [comment]
I do indeed:

```
> rustup --version
rustup 1.25.1 (bb60b1e89 2022-07-12)
```

**Comment by rylev** [comment]
Found one issue online that seems to mirror what you're seeing [here](https://www.reddit.com/r/rust/comments/bd9ysy/cargo_bug/). The solution that seemed to work was to uninstall and reinstall the toolchain. That might be the easiest. The other option is building rustup locally and debugging it...

**Comment by cataggar** [comment]
https://github.com/rust-lang/rustup/issues/2704 has a similar error message, but was marked as a duplicate of https://github.com/rust-lang/rustup/issues/988 . I removed all my toolchains with `rustup toolchain remove` and readded a couple. It is working now.

Here is my toolchain list before and after:

PS C:\Users\cataggar\io\azure-sdk-for-rust> rustup toolchain list 
stable-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc
ms-1.58
1.63.0-x86_64-pc-windows-msvc (override)


PS C:\Users\cataggar\io\azure-sdk-for-rust> rustup toolchain list
stable-x86_64-pc-windows-msvc (default)
1.63.0-x86_64-pc-windows-msvc (override)

**Comment by cataggar** [comment]
I had to reinstall the toolchains again to get this to work for me with 1.64. I got the same error as before.

**Comment by rylev** [comment]
Can you run the following and try again?

```
rustup toolchain uninstall 1.64.0-x86_64-pc-windows-msvc
rustup toolchain install 1.64.0-x86_64-pc-windows-msvc
```

**Comment by testingapisname** [comment]
@rylev that got me working to get a build going. 

Now just to figure out how to use the SDK :) Thanks for the assist!

**Comment by MrTact** [comment]
I *think* this happened to me just now (Intel Mac running macOS Ventura 13.4.1) because I had a network hiccup while installing the toolchain:
```
info: downloading component 'rust-docs'
info: retrying download for 'https://static.rust-lang.org/dist/2023-06-01/rust-docs-1.70.0-x86_64-apple-darwin.tar.xz'
warning: bad checksum for cached download
error: component download failed for rust-docs-x86_64-apple-darwin: could not rename downloaded file from '/Users/tkeating/.rustup/downloads/9c30ce1f6308a379e677021e00e18f185cc708b4edbddacd193f1fb3e0979c27.partial' to '/Users/tkeating/.rustup/downloads/9c30ce1f6308a379e677021e00e18f185cc708b4edbddacd193f1fb3e0979c27'
```
Nuking the toolchain and letting rustup reinstall it seems to have fixed the problem.
