### ISSUE TITLE
Do not fail for missing content-location header for CosmosDB APIs

### ISSUE THREAD

**Issue by kavyako** [Azure/azure-sdk-for-rust#1022]
It looks like the RUST SDK expects the content-location header to be present in the responses from Azure CosmosDB (documentclient APIs). SDK returns an error if this header is not present. Please note that content-location is not listed in the Common Azure CosmosDB Response headers  [Common response headers - Azure Cosmos DB REST API | Microsoft Docs](https://docs.microsoft.com/en-us/rest/api/cosmos-db/common-cosmosdb-rest-response-headers). Hence taking dependency on this header is not a supported scenario. 
Azure CosmosDB service is not returning this header in the newer versions of the gateway. Hence please fix the SDK to remove dependency on this header.

```rust
let resp = match document_client
            .get_document()
            .execute::<D>()
            .await
            .map_err(into_cosmos_error("Could not get document")) {
                Ok(response) => response,
                Err(err) => {
                    println!("XRAY");
                    return Err(err);
                }
            };
```

Error: "content-location" is not found in headers.

**Comment by rylev** [comment]
@kavyako thanks for reporting - I'll look into fixing this issue.

It looks like you're using an older version of the `azure_data_cosmos` crate, but this is still an issue in the latest version.

**Comment by cataggar** [comment]
@kavyako, are there data-plane specifications for the latest version `2018-12-31`? I don't see any stable APIs published in https://github.com/Azure/azure-rest-api-specs/tree/main/specification/cosmos-db/data-plane .

**Comment by jackiepmsft** [comment]
Hi may I ask how frequently we release a rust crate? I'm trying to test with `azure_data_cosmos = "0.5.0"` but the fix is not there.

**Comment by rylev** [comment]
@jackiepmsft we're releasing about once a month (cc @cataggar who has been doing the releases). We should be due for another release soon. In the meantime, can you switch to using a [git dependency](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories)?
