### ISSUE TITLE
More ergonomic client creation

### ISSUE THREAD

**Issue by rylev** [Azure/azure-sdk-for-rust#1080]
Clients inside of the various SDKs form a tree structure. Typically, a "service" client (e.g., `BlobServiceClient`) is at the top of this structure, and other clients are created using that service client or some intermediate clients that are in turn created using the service client (e.g., a `BlobClient` is created using a `ContainerClient` which in turn is created using the `BlobServiceClient`). 

This can work well but is not always the most ergonomic. For example, if you just want to interact with a specific blob you need to do the following:

```rust
let storage_credentials = StorageCredentials::Key(account.clone(), access_key); // Create the credentials
let service_client = BlobServiceClient::new(account, storage_credentials); // Create the service client
let blob_client = service_client
     .container_client(&container_name) // create the intermediate container client
     .blob_client(&blob_name); // Now we get the blob client. 
```

It would be nice to offer the user a more convenient way to get to the blob client. 

One possible way is to change the `BlobServiceClientBuilder` into just a `ClientBuilder`. Then instead of a `build` method that gives you a `BlobServiceClient` you would have multiple builder methods that give you the client you want: 
* `service(self) -> BlobServiceClient`
* `container(self, container_name: impl Into<String>) -> ContainerClient`
* `blob(self, container_name: impl Into<String>, blob_name: impl Into<String>) -> BlobClient`

This might get a bit unwieldy at deeply nested clients though. 

However, in general such a design together with every client having convenient methods for getting other clients means that getting the client you need is never more than one method call away.

**Comment by rylev** [comment]
Additionally, there are some customers who need different client options depending on the resource. In the current API, they need to traverse the client tree twice. In code:

## Before

```rust
let storage_credentials = StorageCredentials::Key(account.clone(), access_key); // Create the credentials

// Interact with blobs
let blob_client = BlobServiceClientBuilder::new(acount, storage_credentials)
      .retry(blob_retry_options)
     .container_client(&container_name) 
     .blob_client(&blob_name); 

// Interact with container
let container_client = BlobServiceClientBuilder::new(acount, storage_credentials)
      .retry(container_retry_options)
     .container_client(&container_name); 
```

## After 

```rust
let storage_credentials = StorageCredentials::Key(account.clone(), access_key); // Create the credentials

// Interact with blobs
let blob_client = ClientBuilder::new(acount, storage_credentials)
      .retry(blob_retry_options)
      .blob_client(&container_name, &blob_name); 

// Interact with container
let container_client = ClientBuilder::new(acount, storage_credentials)
      .retry(blob_retry_options)
      .container_client(&container_name); 
```

**Comment by ctaggart** [comment]
So this does not currently work?

``` rust
let storage_credentials = StorageCredentials::Key(account.clone(), access_key); // Create the credentials

// Interact with container
let container_client = BlobServiceClientBuilder::new(acount, storage_credentials)
      .retry(container_retry_options)
     .container_client(&container_name); 

// Interact with blobs
let blob_client = container_client.blob_client(&blob_name); 
```

**Comment by rylev** [comment]
That works. This is specifically for when you need clients that have different client options. We want to allow creating clients quickly without necessarily traversing the entire client tree to get to the client you want.

**Comment by juliusl** [comment]
Brainstorming a bit, this feels like a problem that might be better solved w/ proc. macros. The current client creation api's match the pattern of what the upstream .net client builders use, so from that aspect it's good enough. But, since this is rs, I'm thinking you could have proc_macros that also do DI. For example, what if it's like this, 

```rs
#[derive(Azure)]
struct MyStruct {
    #[az::storage::container]
    tenant: String,
    #[az::storage::blob]
    manifest: String,
    #[az::storage::blobs]
    files: HashSet<String>,
}

..

impl MyStruct {
    fn async cleanup(&mut self) { 
      let manifest = self.blob("manifest").deserialize_to::<Manifest>().await.expect("should be a valid manifest");
      
      for d in manifest.delete.iter() {
        if let Some(to_delete) = self.remove(d) {
           let delete_resp = self.blob(to_delete).delete().await;
           // etc, etc
        }
      }
   }
}
```

And then behind the scenes, there's a trait that will setup all of the client trees using the fields to fill out the client creation code.

Of course this can be extended for all other resources in azure too. If there's interest I could work on a prototype.
