### ISSUE TITLE
Unable to upload to  Azure blob storage

### ISSUE THREAD

**Issue by baijal1982** [Azure/azure-sdk-for-rust#1116]
I am using example to upload in blob storage. 

https://github.com/Azure/azure-sdk-for-rust/blob/main/sdk/storage_blobs/examples/container_and_blob.rs

Response 

PutBlockBlobBuilder { client: BlobClient { container_client: ContainerClient { service_client: BlobServiceClient { pipeline: Pipeline { pipeline: [TelemetryPolicy { header: "azsdk-rust-storage/0.6.0 (1.63.0; macos; aarch64)" }, CustomHeadersPolicy, ExponentialRetryPolicy { initial_delay: 200ms, max_retries: 8, max_elapsed: 60s, max_delay: 30s }, TimeoutPolicy { default_timeout: None }, AuthorizationPolicy { credentials: StorageCredentials { credential: "Key" } }, TransportPolicy { transport_options: TransportOptions { inner: Http { http_client: Client { accepts: Accepts, proxies: [Proxy(System({}), None)], referer: true, default_headers: {"accept": "*/*"} } } } }] }, cloud_location: Public { account: "vsmedia", credentials: StorageCredentials { credential: "Key" } } }, container_name: "test" }, blob_name: "blob0.txt" }, body: Bytes(b"something"), hash: Some(MD5([67, 123, 147, 13, 184, 75, 128, 121, 194, 221, 128, 74, 113, 147, 107, 95])), content_type: Some(BlobContentType("text/plain")), content_encoding: None, content_language: None, content_disposition: None, metadata: None, access_tier: None, tags: None, lease_id: None, context: Context { type_map: {} } }

PutBlockBlobBuilder { client: BlobClient { container_client: ContainerClient { service_client: BlobServiceClient { pipeline: Pipeline { pipeline: [TelemetryPolicy { header: "azsdk-rust-storage/0.6.0 (1.63.0; macos; aarch64)" }, CustomHeadersPolicy, ExponentialRetryPolicy { initial_delay: 200ms, max_retries: 8, max_elapsed: 60s, max_delay: 30s }, TimeoutPolicy { default_timeout: None }, AuthorizationPolicy { credentials: StorageCredentials { credential: "Key" } }, TransportPolicy { transport_options: TransportOptions { inner: Http { http_client: Client { accepts: Accepts, proxies: [Proxy(System({}), None)], referer: true, default_headers: {"accept": "*/*"} } } } }] }, cloud_location: Public { account: "vsmedia", credentials: StorageCredentials { credential: "Key" } } }, container_name: "test" }, blob_name: "blob1.txt" }, body: Bytes(b"something"), hash: Some(MD5([67, 123, 147, 13, 184, 75, 128, 121, 194, 221, 128, 74, 113, 147, 107, 95])), content_type: Some(BlobContentType("text/plain")), content_encoding: None, content_language: None, content_disposition: None, metadata: None, access_tier: None, tags: None, lease_id: None, context: Context { type_map: {} } }

PutBlockBlobBuilder { client: BlobClient { container_client: ContainerClient { service_client: BlobServiceClient { pipeline: Pipeline { pipeline: [TelemetryPolicy { header: "azsdk-rust-storage/0.6.0 (1.63.0; macos; aarch64)" }, CustomHeadersPolicy, ExponentialRetryPolicy { initial_delay: 200ms, max_retries: 8, max_elapsed: 60s, max_delay: 30s }, TimeoutPolicy { default_timeout: None }, AuthorizationPolicy { credentials: StorageCredentials { credential: "Key" } }, TransportPolicy { transport_options: TransportOptions { inner: Http { http_client: Client { accepts: Accepts, proxies: [Proxy(System({}), None)], referer: true, default_headers: {"accept": "*/*"} } } } }] }, cloud_location: Public { account: "vsmedia", credentials: StorageCredentials { credential: "Key" } } }, container_name: "test" }, blob_name: "blob2.txt" }, body: Bytes(b"something"), hash: Some(MD5([67, 123, 147, 13, 184, 75, 128, 121, 194, 221, 128, 74, 113, 147, 107, 95])), content_type: Some(BlobContentType("text/plain")), content_encoding: None, content_language: None, content_disposition: None, metadata: None, access_tier: None, tags: None, lease_id: None, context: Context { type_map: {} } }
ListBlobsResponse { prefix: None, max_results: None, delimiter: None, next_marker: None, blobs: Blobs { items: [] }, request_id: c6753db8-c01e-006c-71cc-daa99a000000, date: 2022-10-08 4:17:51.0 +00:00:00 }

Crates 

dependencies]
azure_core = "0.5.0"
azure_storage= "0.6.0"
azure_storage_blobs= "0.6.0"
base64 = "0.13"
bytes = "1.0"
time = "0.3.10"
futures = "0.3"
log = "0.4"
md5 = "0.7"
RustyXML = "0.3"
serde = { version = "1.0" }
serde_derive = "1.0"
serde_json = "1.0"
serde-xml-rs = "0.6"
uuid = { version = "1.0", features = ["v4"] }
url = "2.2"
env_logger = "0.9.1"
tokio = { version = "1", features = ["rt", "macros","rt-multi-thread"] }

[dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
env_logger = "0.9"
reqwest = "0.11"
azure_identity = "0.6.0"

[features]
default = ["enable_reqwest"]
test_e2e = []
test_integration = []
azurite_workaround = []
enable_reqwest = ["azure_core/enable_reqwest", "azure_storage/enable_reqwest"]
enable_reqwest_rustls = [
  "azure_core/enable_reqwest_rustls",
  "azure_storage/enable_reqwest_rustls",
]
into_future = []

Issue 1 -  Await is not getting supported for 
let res = container_client
        .blob_client("blob0.txt")
        .put_block_blob(data.clone())
        .content_type("text/plain")
        .hash(hash).await?;

PutBlockBlobBuilder` is not a future
the trait `futures::Future` is not implemented for `PutBlockBlobBuilder`
PutBlockBlobBuilder must be a future or must implement `IntoFuture` to be awaited
required because of the requirements on the impl of `std::future::IntoFuture` for `PutBlockBlobBuilder

This error resolved if await removed. 

Issue 2 - Code runs successfully but no files getting uploaded to Azure storage container.

**Comment by baijal1982** [comment]
This is working now.
Just added toFuture to

Original 

 container_client
.blob_client("blob0.txt")
.put_block_blob(data.clone())
.content_type("text/plain")
.hash(hash).await?;


Corrected 

 container_client
.blob_client("blob0.txt")
.put_block_blob(data.clone())
.content_type("text/plain")
.hash(hash).toFuture().await?;

**Comment by cataggar** [comment]
@baijal1982, what library did `toFuture` come from?
