### ISSUE TITLE
`await` without `into_future`

### ISSUE THREAD

**Issue by cataggar** [Azure/azure-sdk-for-rust#1117]
From https://github.com/Azure/azure-sdk-for-rust/issues/1116#issuecomment-1272359969, the workaround was to add `toFuture`. I wasn't expecting that to be required.

``` rust
container_client.blob_client("blob0.txt").put_block_blob(data.clone()).content_type("text/plain").hash(hash).await?;
```

``` rust
container_client.blob_client("blob0.txt").put_block_blob(data.clone()).content_type("text/plain").hash(hash).toFuture().await?;
```

May be some additional changes need to be made in addition to #1102.

**Comment by rylev** [comment]
I'm confused. Where would `toFuture` be coming from. The method is `into_future`. A search of `toFuture` in the code base does not return anything.

**Comment by cataggar** [comment]
I think we just need to confirm that this is working as intended:

``` rust
container_client.blob_client("blob0.txt").put_block_blob(data.clone()).content_type("text/plain").hash(hash).await?;
```

**Comment by tkimmm** [comment]
Can also confirm that this error is thrown in:
`table_client.insert(entitiy)?.await?`

And requires an additional chain of
`table_client.insert(entity)?.into_future().await?;`

**Comment by tkimmm** [comment]
Also noticed that this extended to the keyvault api (haven't looked at the SDK for a while, was still implementing `ClientSecretCredential`) - cargo cleaned out my project and removed my local lock file to bulld again.

Puzzled at the moment - on 1.64.0

**Comment by tkimmm** [comment]
I'm on 0.5.0 - it's trivial from my side to just have the additional call, either way thanks Ryan
