### ISSUE TITLE
Code completion fails on storage properties?

### ISSUE THREAD

**Issue by erikpa1** [Azure/azure-sdk-for-rust#1122]
Hi I', trying to get container properties, but Pycharm and VS code, totally dies here, (and also on more examples) Is it some problem of rust-lang server (too young) ? or is it because something azure api uses (a lot of macro or something) ? Its really hard to code, when IDE, can't decide types in such hard language like rust.

![image](https://user-images.githubusercontent.com/19526670/195994900-35376cb9-073a-4112-9ee5-7d478132311b.png)

**Comment by rylev** [comment]
@erikpa1 the code completion seems to be working fine. `rust-analyzer` is properly pointing out that the type of the variable called `properties` is a ` GetProperteriesBuilder`. The SDK's operations do not complete until you call `.await` on them. Until then they are simply builders that allow you to specify different options on the operation. Once you call `.await` on that operation you'll notice that you'll have a `GetPropertiesResponse` which has the data you're looking for. Hope this helps!

**Comment by erikpa1** [comment]
@rylev Nah, stupid me, sorry, I copy code from python, and always forgot await which is required here, thanks for answer
