### ISSUE TITLE
Storage examples are out of date?

### ISSUE THREAD

**Issue by erikpa1** [Azure/azure-sdk-for-rust#1124]
Hi I have code from example:

```
pub async fn upload_blob(container: &str, blob_path: &str, blob: &str) -> Result<bool, Box<dyn Error>> {
    println!("{}", container);
    println!("{}", blob_path);
    println!("{}", blob);

    let container = get_container_client(container);
    container.create();

    let blob_client = container.blob_client(blob_path);


    let res = blob_client
        .put_block_blob("121431241241")
        .content_type("text/plain").await?;

    println!("1-put_block_blob {:?}", res);

    return Ok(true);
}
```

But after this I get error:
```

   |
73 |         .content_type("text/plain").await?;
   |                                    ^^^^^^
   |                                    |
   |                                    `PutBlockBlobBuilder` is not a future
   |                                    help: remove the `.await`
   |
   = help: the trait `std::future::Future` is not implemented for `PutBlockBlobBuilder`


```

This is code from example, I'm I missing something ? I use latest 0.6.0 version. When I remove .await it compiles bot code don't work nothing is written on storage (also container.create() don't work with await, and example has await).

Storage account is also fine, reading examples works.

**Comment by erikpa1** [comment]
Ok I figured, you have to add "into_futures" features to your cargo.toml

azure_storage_blobs = { version = "0.6.0", features = ["into_future"] }

**Comment by rylev** [comment]
Correct, the version on the `main` branch is the absolute latest version and differs a bit from the release on crates.io. We release currently on a monthly basis so eventually this inconsistency corrects itself.
