### ISSUE TITLE
Request builder future is not `Send`

### ISSUE THREAD

**Issue by MindFlavor** [Azure/azure-sdk-for-rust#113]
As correctly noted by [Ben Sully](https://github.com/sd2k) in #112, not using a let binding in request builders makes futures not `Send`able. 

The PR fixes one builder but we should extend the fix to all the other builders.

**Comment by extrawurst** [comment]
@MindFlavor Yeah I just ran into this for the `PutBlockBuilder` in blob storage. interestingly this was no problem in the old deprecated crate (I just started to migrate).

**Comment by MindFlavor** [comment]
It's my fault, I've unintentionally introduced the regression in #84. 
I honestly admit I'm still fuzzy on why it happens, but, hey, you found the problem *and* the solution so I'm in luck 😲 !

Thank you again! 👍
