### ISSUE TITLE
azure_data_cosmos error: resource quota has an unrecognized part

### ISSUE THREAD

**Issue by tcallan** [Azure/azure-sdk-for-rust#1137]
I was testing out the azure_data_cosmos crate with some simple code, lightly adapted from the examples:
```rust
let account = "...";
let key = "...";
let token = AuthorizationToken::primary_from_base64(key)?;
let client = CosmosClient::new(account, token);

let mut dbs = client.list_databases().into_stream();

while let Some(db) = dbs.try_next().await? {
    for d in db {
        println!("{}", d.id);
    }
}
```
Both versions 0.6.0 and 0.7.0 of the crate produce the following error when running:
```
Error: Error { context: Message { kind: DataConversion, message: "resource quota has an unrecognized part - part: \"roleDefinitions=100\" full string: \"databases=1000;collections=5000;users=500000;permissions=2000000;clientEncryptionKeys=20;interopUsers=2000;authPolicyElements=200000;roleDefinitions=100;roleAssignments=2000;\"" } }
```
That seems to point pretty obviously at https://github.com/Azure/azure-sdk-for-rust/blob/4c60222bf1d56d6af87e6e8a555f93fe5cc501e5/sdk/data_cosmos/src/resource_quota.rs#L86 as the source of the error. I pulled the code down locally and commented out the whole else block for the sake of quick testing. With that change my code above works as expected (i.e. I get a list of databases from the account).

**Comment by rylev** [comment]
I agree it doesn't really make sense to error when we encounter a part we're not familiar with. Is `roleDefinitions` meaningful? Should we be capturing that in the resource quota?

**Comment by tcallan** [comment]
`roleDefinitions` (and `roleAssignments` which would also cause an error) are not meaningful to _me_, but I'm not sure about the general value of capturing them.

**Comment by AchuthAnderson** [comment]
any timeline on the fix for this issue?
