### ISSUE TITLE
Set up labels to sync with other repos

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-rust#1142]
- [ ] Triage existing labels, removing any unused ones we don't define in other repos.
- [ ] Rename and recolor labels that are the same or similar to [labels in other repos](https://github.com/Azure/azure-sdk-tools/blob/main/tools/github/data/common-labels.csv).
- [ ] Add Azure/azure-sdk-for-rust to https://github.com/Azure/azure-sdk-tools/blob/main/tools/github/data/repositories.txt

**Comment by cataggar** [comment]
Please reopen if you wish to do this.
