### ISSUE TITLE
Is there an equivalent to AppServiceCredential ManagedIdentity in rust azure_identity?

### ISSUE THREAD

**Issue by tomasro27** [Azure/azure-sdk-for-rust#1148]
Is there an equivalent to AppServiceCredential ManagedIdentity in rust azure_identity?

https://github.com/Azure/azure-sdk-for-python/blob/40f3d19b92381699f348f354d3f4d0dc2df88bf0/sdk/identity/azure-identity/azure/identity/_credentials/app_service.py

Looking at the python sdk, AppServiceCredential uses both MSI_ENDPOINT and MSI_SECRET env vars, which I cant' find on the azure identity in rust. 

imds_managed_identity_credentials.rs uses 
const MSI_ENDPOINT_ENV_KEY: &str = "IDENTITY_ENDPOINT";
const MSI_SECRET_ENV_KEY: &str = "IDENTITY_HEADER";

which is different from msi endpoint in python sdk

  IDENTITY_ENDPOINT = "IDENTITY_ENDPOINT"
  IDENTITY_HEADER = "IDENTITY_HEADER"
  IDENTITY_SERVER_THUMBPRINT = "IDENTITY_SERVER_THUMBPRINT"
  IMDS_ENDPOINT = "IMDS_ENDPOINT"
  MSI_ENDPOINT = "MSI_ENDPOINT"
  MSI_SECRET = "MSI_SECRET"
  https://github.com/Azure/azure-sdk-for-python/blob/40f3d19b92381699f348f354d3f4d0dc2df88bf0/sdk/identity/azure-identity/azure/identity/_constants.py

**Comment by tomasro27** [comment]
Looking more into this it seems there are multiple types of managed identity, and this particular one is "App Service MSI version 2017-09-01" which is equivalent to "AppServiceV2017ManagedIdentitySource" in dotnet.

This looks like the full list, at least from dotnet side.

ServiceFabricManagedIdentitySource.TryCreate(options) ??
  AppServiceV2019ManagedIdentitySource.TryCreate(options) ??
  AppServiceV2017ManagedIdentitySource.TryCreate(options) ??
  CloudShellManagedIdentitySource.TryCreate(options) ??
  AzureArcManagedIdentitySource.TryCreate(options) ??
  TokenExchangeManagedIdentitySource.TryCreate(options) ??
  new ImdsManagedIdentitySource(options);
  
  Are there plans to support them?

**Comment by cataggar** [comment]
Hi @tomasro27, we would like to have parity. No one is actively working on it right now. There is additional analysis at https://github.com/Azure/azure-sdk-for-rust/pull/1016#issuecomment-1218025400

> > It would be nice if all credential options failed fast if unavailable. I think our ImdsManagedIdentityCredential is actually a combination of these two source types in .NET:
AppServiceV2019ManagedIdentitySource
ImdsManagedIdentitySource

May be see if `ImdsManagedIdentityCredential`  meets your needs.
