### ISSUE TITLE
Azure SDK should automatically set endpoints based on the cloud it is in

### ISSUE THREAD

**Issue by archoversight** [Azure/azure-sdk-for-rust#1156]
Hey,

We are using Vector (https://vector.dev/) for logging in Azure USGov Virginia and Azure USGov Arizona and unfortunately the Azure SDK for Rust makes many assumptions that is running entirely within the Public cloud. There are many endpoints and services that have a different URL and the defaults do not work. It would makes sense to either pick up the value automatically from `~/.azure/config` or the environment variable `AZURE_CLOUD_NAME`.

This way when creating clients for things like blob storage it would automatically pick the correct URL.

Please see:

https://learn.microsoft.com/en-us/azure/azure-government/compare-azure-government-global-azure#guidance-for-developers

for information on all the endpoints that change and the appropriate URL's to match them to.

Thanks,
Bert JW Regeer

**Comment by juliusl** [comment]
Probably could add something for that here, https://github.com/Azure/azure-sdk-for-rust/blob/3de510ce055be3cdc65b3b46783d4f6d97db4fe7/sdk/storage/src/cloud_location.rs#L9 ?

**Comment by rylev** [comment]
As @juliusl we should add support for this to the `CloudLocation` enum which then can be passed to the `BlobServiceClientBuilder` [here](https://github.com/Azure/azure-sdk-for-rust/blob/3de510ce055be3cdc65b3b46783d4f6d97db4fe7/sdk/storage_blobs/src/clients/blob_service_client.rs#L35).

**Comment by juliusl** [comment]
@archoversight Where is `AZURE_CLOUD_NAME` documented?

**Comment by archoversight** [comment]
@juliusl it is what I see most commonly used by various other companies when they are scripting support for alternate Azure locations.

I don't think it is explicitly documented anywhere by Microsoft. When it comes to AWS, we use `AWS_REGION` with similar effect.

For example `us-gov-west-1` and `us-east-2` are valid AWS regions that direct the API calls to the right locations.

**Comment by archoversight** [comment]
Also adding the enum would not allow for automatic detection. Clients using the code would need to add detection for the appropriate cloud.

Vector for example requires:

- account name
- container name

When provided the account name it uses the default credential finder:

- EnvironmentCredential
- ManagedIdentityCredential
- AzureCliCredential

But those credentials are not searched for until after an attempt is made to use Object Storage, at which point the default location is used (AzureCloud) while the credentials are for AzureUSGovernment and the URL for object storage is wrong.

Unless the requirement/expectation is that all software explicitly has configuration to select the right particular enum. At the moment the supported Azure clouds are named:

```
% az cloud list --output table
IsActive    Name               Profile
----------  -----------------  ---------
False       AzureCloud         latest
False       AzureChinaCloud    latest
True        AzureUSGovernment  latest
False       AzureGermanCloud   latest
```

having every piece of software match against these explicitly and set the right enum would mean breaking changes necessary for each and every time that Azure spins up another cloud.

**Comment by juliusl** [comment]
@archoversight Just to clear up things up a bit, the enum we're talking about adding is called `CloudLocation::AutoDetect`. 

Take a peek at my PR (#1166) but it basically works the way you described in your description above.

**Comment by archoversight** [comment]
The `auto_detect` function seems to rely on either a configured `~/.azure/config` file or an environment variable to be set, which is better than what exists currently.

In AWS though the SDK knows that if neither of those is set it can interrogate the default credential providers (in specific order) to try and find where it is located. On system with IAM instance profiles attached for example, and no other configuration it can still know it is located in `us-gov-west-1` because the IAM instance profile through the well known metadata endpoint URL provides that information, from there all the correct URL's can be automatically created.

Does Azure make something similar available. Could the credentials provided be interrogated to find out what "cloud" a machine is located in? This avoids needing to provide additional configuration to make things work out of the box.

**Comment by demoray** [comment]
IMSD provides functionality similar to what @archoversight describes from AWS's IAM.

https://learn.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service?tabs=linux#sample-5-get-the-azure-environment-where-the-vm-is-running

**Comment by juliusl** [comment]
@archoversight  @demoray That's a pretty good idea, actually I like that a lot more than file or env, but I think for the dev box scenario env/file make sense as a fallback. 

cc: @cataggar I wanted to check to see if you had any concerns about calling IAM from the SDK?

**Comment by ctaggart** [comment]
Are there any other Azure SDKs using IMDS for this purpose? You can use the [azure_svc_imds](https://github.com/Azure/azure-sdk-for-rust/tree/main/services/svc/imds) crate for accessing IMDS.

**Comment by archoversight** [comment]
> @archoversight @demoray That's a pretty good idea, actually I like that a lot more than file or env, but I think for the dev box scenario env/file make sense as a fallback.

For cases where you are not using IMDS or are not running on Azure but are using other types of credentials setting it from the environment or reading it from the central config is required.

This is certainly not an XOR I was proposing here, just arguing that the default should try to do some discovery on its own if possible to reduce overhead for callers of the SDK.

AWS does have a flag to disable the SDK from automatically reaching out to the IMDS: `AWS_EC2_METADATA_DISABLED` (See https://docs.aws.amazon.com/sdkref/latest/guide/feature-imds-credentials.html)

Ultimately you want to make it as easy as possible for consumers to get a setup that just works. Having good defaults helps. In the AWS SDK if there are credentials other than IMDS provided it will never reach out to IMDS for example.
