### ISSUE TITLE
put-block-list blob-content-md5 header not supported

### ISSUE THREAD

**Issue by extrawurst** [Azure/azure-sdk-for-rust#118]
the `put-block-list` call supports setting this md5 hash that we see in `Blob` for when you `get-blob` it back (see https://docs.microsoft.com/en-us/rest/api/storageservices/put-block-list).

I wonder if you guys have a high level doc how to contribute? cause I am confused about what code generation is going on in here if I were to add this missing header myself?

**Comment by MindFlavor** [comment]
We are currently phasing out the code generator by simplifying the request builders (less traits, less reliance on builder pattern, etc...). We are experimenting with the new approach in the CosmosDB crate (which was the most feature-complete).
We will try to write a "how to start contributing" guide as soon as it's finished (I've kicked off the migration in #119).

**Comment by MindFlavor** [comment]
You were indeed right, the support for `blob-content-md5` was missing!

In the PR abovementioned I've added it, along with some other enhancements (for example, we use now `bytes` instead of a more complicated `&[u8]`).
