### ISSUE TITLE
"header not found x-ms-request-charge" error when deleting from cosmos

### ISSUE THREAD

**Issue by ayngling** [Azure/azure-sdk-for-rust#1184]
The operation succeeds, but an error is returned. I have tested various versions of the library, including the newest. (The error seems similar to an earlier issue that was solved: https://github.com/Azure/azure-sdk-for-rust/issues/1022 )

```
[dependencies]
tokio = { version = "1.1.0", features = ["rt-multi-thread", "macros", "time"] }
azure_core = "0.8.0"
azure_data_cosmos = "0.9.0"
```

```
use azure_data_cosmos::prelude::*;
use std::error::Error;

const COSMOS_ACCOUNT: &str = "xxx";
const COSMOS_MASTER_KEY: &str = "xxx";
const COSMOS_DATABASE: &str = "xxx";

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error + Send + Sync>> {
    let collection_name = "xxx";
    let document_id = "xxx";
    let partition_key = "xxx";

    let authorization_token = AuthorizationToken::primary_from_base64(&COSMOS_MASTER_KEY)?;
    let client = CosmosClient::new(COSMOS_ACCOUNT.to_string(), authorization_token);
    let database = client.database_client(COSMOS_DATABASE);
    let collection_client = database.collection_client(collection_name.to_string());
    let document_client = collection_client.document_client(document_id, &partition_key)?;

    document_client.delete_document().into_future().await?;

    Ok(())
}
```

Result:
```
Error: Error { context: Message { kind: DataConversion, message: "header not found x-ms-request-charge" } }
```

**Comment by ayngling** [comment]
This issue has hit all our production API. I believe the issue started a few days ago, possibly the 9th. (We started receiving reports from users around that time).

**Comment by ayngling** [comment]
The error occurs here: https://github.com/Azure/azure-sdk-for-rust/blob/356952d4e10a8d93e0cc782eb01a53f95604ec68/sdk/data_cosmos/src/operations/delete_document.rs#L64

**Comment by ayngling** [comment]
An update on this. We got the following from Azure support today: "We got update from our product team, they are currently working on a hotfix for this issue. they will update with a deployment time after finalizing the changes."

So it seems this is not an issue with the SDK, but rather an issue in Azure that will be fixed.

**Comment by cataggar** [comment]
Thank you for the update @ayngling. Will close this, but keep us posted.
