### ISSUE TITLE
Is there something similar to download_blob() from python sdk

### ISSUE THREAD

**Issue by JuanGarcia0323** [Azure/azure-sdk-for-rust#1187]
Hello, I'm looking for something similar to the next and at this point I'm not completlly sure if it exists in the current state of the sdk on Rust:

`container.get_blob_client(i).download_blob().readinto(data) # data is a BytesIO object and blob is the metada-blob`

That's the python code that I'm using right now, if there's a way to do this on the curren sdk of Rust that would be great. Thanks in advance.

**Comment by JuanGarcia0323** [comment]
Hello again, I already found the way to do this, so I proceed to share the code and close the Issue:

```
let blob_stream = container_client // Download specific blob using the name
        .blob_client("blob-name")
        .get()
        .into_stream()
        .next()
        .await
        .expect("The program failed while downloading the blob")
        .unwrap();

    let result = blob_stream // Collect all the information on Bytes
        .data
        .collect()
        .await
        .expect("Error while dowloading blob_result data");

    let reader = Cursor::new(result);
```

**Comment by demoray** [comment]
If you're looking to download the entire blob in one SDK API call, you can do that with [BlobClient::get_content](https://docs.rs/azure_storage_blobs/latest/azure_storage_blobs/prelude/struct.BlobClient.html#method.get_content)

**Comment by JuanGarcia0323** [comment]
Perfect I'll try it. Thank you so much.
