### ISSUE TITLE
DevOps - Run pipeline

### ISSUE THREAD

**Issue by iagosrodrigues** [Azure/azure-sdk-for-rust#1188]
Are there any plans to have a function to run a pipeline in the mngt_devops crate?

**Comment by vaaleyard** [comment]
+1, also interested

**Comment by demoray** [comment]
The `mgmt` and `svc` crates expose the ["Azure Resource Manager" REST APIs](https://learn.microsoft.com/en-us/rest/api/resources/), with the management and data-plane respectively.

While Azure DevOps (ADO) implements a number of features via the ARM APIs, much of the ADO API is not exposed via ARM.

That said, there is an effort to implement the ADO REST API for rust: https://github.com/microsoft/azure-devops-rust-api/
