### ISSUE TITLE
code: 10054, kind: ConnectionReset, message: "An existing connection was forcibly closed by the remote host."

### ISSUE THREAD

**Issue by JuanGarcia0323** [Azure/azure-sdk-for-rust#1191]
Hello again, when I'm trying to execute the code, after a while the program returns the error: `code: 10054, kind: ConnectionReset, message: "An existing connection was forcibly closed by the remote host."` and I'm not completely sure why this is happening.

I'd like to know if this is a problem inside the library or if is it something related with the Azure server that I'm consuming. Thanks in advance.

**Comment by minghuaw** [comment]
This looks like a `std::io::Error` which likely originated from the underlying transport. I think there is a higher chance that something is wrong on the server side than on the client side

**Comment by JuanGarcia0323** [comment]
Yeah, I have the feeling that the problem it's occurring because I'm doing multiple large requests to the server and probably it's dropping the connection. I have another doubt and I don't know if should open another issue, I want to connect using a proxy, is there some way to do that? Thanks in advance, I really appreciate the quick response, and good disposition.

**Comment by cataggar** [comment]
The default http library being used is reqwest. It supports proxies.
https://docs.rs/reqwest/latest/reqwest/#proxies
