### ISSUE TITLE
Why are these crates not yet published?

### ISSUE THREAD

**Issue by jeschkies** [Azure/azure-sdk-for-rust#120]
Hi :wave: 
I was trying to use only the blob storage crate with
```toml
azure_storage = { version = "0.2", default-features = false, features = ["blob"] }
```

However, the crate is not found and I cannot find it on [crates.io](https://crates.io/search?page=2&q=azure_storage). Have the crates not benn published yet?

**Comment by extrawurst** [comment]
its not published yet. see #100

**Comment by jeschkies** [comment]
Thanks for the link. Would it make sense to create an issue tracking the state? If it's a few days out it's fine but you probably don't want people like me asking every few days :slightly_smiling_face:

**Comment by extrawurst** [comment]
I guess this issue can be pinned and kept open for updates, right @rylev ?
