### ISSUE TITLE
How to tell if there are issues with put_block_blob? Upload not working

### ISSUE THREAD

**Issue by LukasDeco** [Azure/azure-sdk-for-rust#1224]
Hello!

I am running this code:

```
// Get the resulting GIF data as a vector of bytes
        let gif_data = gif_encoder.into_inner().unwrap();
        let gif_data_bytes = gif_data.get_ref().clone();

        // Store the GIF data in Azure Blob Storage
        let account = std::env::var("STORAGE_ACCOUNT").expect("missing STORAGE_ACCOUNT");
        let access_key = std::env::var("STORAGE_ACCESS_KEY").expect("missing STORAGE_ACCOUNT_KEY");
        let container = std::env::var("STORAGE_CONTAINER").expect("missing STORAGE_CONTAINER");

        let storage_credentials = StorageCredentials::Key(account.clone(), access_key);
        let blob_client = ClientBuilder::new(account.clone(), storage_credentials)
            .blob_client(&container, encode(gif_name.clone().as_str()).into_owned());

        let blob_builder = blob_client.put_block_blob(gif_data_bytes);

        // Return the URL of the stored GIF
        let blob_url = format!(
            "https://{}.blob.core.windows.net/{}/{}",
            account,
            blob_client.container_client().container_name(),
            encode(gif_name.as_str()).into_owned()
        );
```

When I try to access `blob_url` there is nothing there and nothing shows up in the container in azure portal. I'm not sure how to see what kind of errors I might be getting? I have inspected the `blob_builder` variable but it doesn't have any errors or error statuses on it. Any ideas? Do I need to specify `content_type` on `put_block_blob`? gif_data_bytes is a `Vec<u8>`.

**Comment by demoray** [comment]
In your code sample, `blob_builder` is a future, of which you must `await` on it.

Try changing it to:
```
let blob_builder = blob_client.put_block_blob(gif_data_bytes).await?;
```

**Comment by johnbatty** [comment]
+1 for the advice to add `.await` to execute the future.

I'd also suggest adding `content_type` to help identify the data type when it is retrieved.

Note that this function will return a [`PutBlockBlobResponse`](https://docs.rs/azure_storage_blobs/latest/azure_storage_blobs/blob/operations/struct.PutBlockBlobResponse.html), so you should also change your variable name from `blob_builder` to `response` (or similar)...
```
let response = blob_client
    .put_block_blob(gif_data_bytes)
    .content_type("image/gif")
    .await?;
```
Also see the github repo for usage examples, in particular [put_block_blob_00](https://github.com/Azure/azure-sdk-for-rust/blob/main/sdk/storage_blobs/examples/put_block_blob_00.rs#L41)

**Comment by LukasDeco** [comment]
Thanks for your help I was able to get it working with `await?` and the `content_type`! It works great now!

My only problem left is trying to get the hash to work 😄 

```
let image_bytes = std::fs::read(gif_path).unwrap();
        let hash = Hash::MD5(
            image_bytes.clone()[..16]
                .try_into()
                .expect("Incorrect bytes length"),
        );
        let res = blob_client
            .put_block_blob(image_bytes)
            .content_type("image/gif")
            .hash(hash) //TODO get hash to work
            .await?;

```
I'm getting `Error Code: Md5Mismatch` not sure if you guys know if I'm not building the hash correctly?

**Comment by johnbatty** [comment]
See this example for how to calculate an md5 hash:
    https://github.com/Azure/azure-sdk-for-rust/blob/main/sdk/storage_blobs/examples/put_block_blob_00.rs#L35

Your code isn't working because you are only doing the hash on the first 16 bytes of your data - it needs to be calculated over all the data.  Also worth noting that calculating/providing a hash is optional, so you could just remove the call to `.hash(hash)`.

**Comment by LukasDeco** [comment]
I have tried that example but md5 didn't seem to be in scope. I'm pretty sure I tried all the exports...

**Comment by johnbatty** [comment]
Add `md5` to your dependencies in `Cargo.toml` like this:
https://github.com/Azure/azure-sdk-for-rust/blob/main/sdk/storage_blobs/Cargo.toml#L24

**Comment by LukasDeco** [comment]
Oh duh... okay. Thank you! Got it working now.
