### ISSUE TITLE
azure_identity Credential implementations do not cache/refresh tokens

### ISSUE THREAD

**Issue by johnbatty** [Azure/azure-sdk-for-rust#1228]
In `azure_identity` the `XXXCredential` implementations of get_token() always do the work to fetch a new token, even if the previous token has not expired. It does no caching or refreshing of previously obtained tokens. This will clearly impact performance if you are making many API calls.  The impact will vary according to the credential mechanism, but a particularly bad example is if `AzCliCredential` is used then an `az` process is spawned to get a credential on every REST API call!

There is an [`AutoRefreshingTokenCredential`](https://docs.rs/azure_identity/latest/azure_identity/struct.AutoRefreshingTokenCredential.html) wrapper that does provide caching and renewing on expiry.  However, the documentation/examples do not explain that this needs to be used in order to have token caching, or the implications of not using it.  This wrapper also has [a recently discovered issue](https://github.com/Azure/azure-sdk-for-rust/issues/1225) where a single credential cannot be used for multiple different resources.

Links to several `get_token()` implementations, demonstrating that they unconditionally fetch new tokens:
- [AzureCliCredential::get_token()](https://github.com/Azure/azure-sdk-for-rust/blob/main/sdk/identity/src/token_credentials/azure_cli_credentials.rs#L125)
- [ClientSecretCredential::get_token()](https://github.com/Azure/azure-sdk-for-rust/blob/main/sdk/identity/src/token_credentials/client_secret_credentials.rs#L103)
- [ImdsManagedIdentityCredential::get_token()](https://github.com/Azure/azure-sdk-for-rust/blob/main/sdk/identity/src/token_credentials/imds_managed_identity_credentials.rs#L92)

At a minimum we should improve the `azure_identity` documentation to explain the behaviour.  However, I don't think that this is sufficient as it is too easy for developers to use a Credential provider in an inefficient way that will degrade performance in a way that is not obvious (it just makes your API calls slower).

The equivalent [Credential objects in the dotnet SDK do cache/refresh tokens](https://learn.microsoft.com/en-gb/dotnet/api/azure.identity.managedidentitycredential?view=azure-dotnet#methods), so I think that the ideal goal would be to rework the Rust SDK Credential implementations to implement token caching/refreshing to align with this behaviour.

**Comment by demoray** [comment]
With at least one of the providers, IMDS, there are rate limits that will break due to rate limits unless the tokens are cached.

**Comment by demoray** [comment]
Implemented in 1484.
