### ISSUE TITLE
azure_storage::core::client::with_azure_sas requires '?' in SAS token string

### ISSUE THREAD

**Issue by karataliu** [Azure/azure-sdk-for-rust#123]
Glad to see the new project home!

<hr/>

When I'm writing a sample for accessing blob with SAS, I noticed that SAS token returned by `azure_mgmt_storage::operations::storage_accounts::list_service_sas` doesn't have a leading `?`. While `azure_storage::core::client::with_azure_sas` requires a leading `?`.

The caller code needs to be:
```
azure_storage::core::client::with_azure_sas(account, ("?".to_owned() + sas_token).as_ref())
```

Another look from the table client code:
https://github.com/Azure/azure-sdk-for-rust/blob/c3aac9fd08ebfd4c3dd182563afeaf97735de74a/sdk/storage/src/table/table_client.rs#L55

Here the sas token value comes from https://github.com/Azure/azure-sdk-for-rust/blob/374e834633c75f9a5f3929ab8f2dd3eb81c8dc68/sdk/storage/src/core/connection_string.rs#L6

The [doc example](https://docs.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string#service-sas-example) indicates that it doesn't have the leading '?' either.

Shall `azure_storage::core::client::with_azure_sas` be changed to accepting string without leading `?`? If there is a historical reason for this, could we get it accept both leading `?` and non-leading `?`?

**Comment by MindFlavor** [comment]
I agree with you, not requiring the `?` is the way to go. The `?` is an artifact of the url query pairs so it should not be there. 

I would postpone the fix until PR #119 is completed but it should be easy to fix.
