### ISSUE TITLE
Blob Storage: Is batch operation supported? 

### ISSUE THREAD

**Issue by Mossaka** [Azure/azure-sdk-for-rust#1249]
A quick skim of the supported APIs in azure_storage_blobs, I didn't find a batch deletion operation as described [here](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.blobdeletebatchoperation?view=azure-dotnet). I am looking for an operation that can submit a batch deletion of a list of objects.

```rust
self.client.delete_objects(...)
```

Thank you 🙏

**Comment by johnbatty** [comment]
I just checked and can confirm that batch delete is not currently implemented in `azure_storage_blobs`.

Unfortunately it is an unconventional API that is not as straightforward to implement as most of the other APIs:
https://learn.microsoft.com/en-us/rest/api/storageservices/blob-batch

**Comment by arpad-m** [comment]
I think this is a dupe of #1068

**Comment by demoray** [comment]
It is.  Closed in preference of the previous work item.
