### ISSUE TITLE
ClientCertificateCredential undeclared type with azure_identity 0.11.0

### ISSUE THREAD

**Issue by matwilwe** [Azure/azure-sdk-for-rust#1259]
Is ClientCertificateCredential supported in version 0.11.0 of the azure_identity crate?

I'm getting errors when I'm trying to use it in my project even though I'm pointing my toml at the latest version. I also noticed that the crates.io entry is missing the struct definitions for ClientCertificateCredential and CertificateCredentialOptions. 

I'm also very new to rust so it's distinctly possible that I'm doing something stupid. Thank you in advance!

**Comment by demoray** [comment]
To use the client certificate features of the azure_identity crate, you need to specify the `client_certificate` feature.  Can you check that you have this feature enabled?
