### ISSUE TITLE
Can't build valid EventSubscription create or update request in azure_mgmt_eventgrid

### ISSUE THREAD

**Issue by JWT95** [Azure/azure-sdk-for-rust#1270]
## Problem

The [Azure REST API](https://learn.microsoft.com/en-us/rest/api/eventgrid/controlplane-version2022-06-15/event-subscriptions/create-or-update?tabs=HTTP#request-body) documentation defines the `properties.destination` field in the Event Subscription as having type one of `WebHookEventSubscriptionDestination`, `EventHubEventSubscriptionDestination`, `StorageQueueEventSubscriptionDestination`... Each of these types contain an `endpointType` field and a `properties` field giving details of the endpoint.

The autogenerated `azure_mgmt_eventgrid` crate has the `properties.destination` field as having type [`EventSubscriptionDestination`](https://docs.rs/azure_mgmt_eventgrid/0.11.0/azure_mgmt_eventgrid/package_2022_06/models/struct.EventSubscriptionProperties.html). This only contains the `endpoint_type` field and not the `properties` field. So it is impossible to use the crate to create an Event Subscription.

## Ideas

I'm not sure if this is a bug in the Rust code autogenerator or the Azure REST API spec. The [OpenAPI spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/eventgrid/resource-manager/Microsoft.EventGrid/stable/2022-06-15/EventGrid.json) has:

```json
    "EventSubscriptionProperties": {
        ...
        "destination": {
          "$ref": "#/definitions/EventSubscriptionDestination",
          "description": "Information about the destination where events have to be delivered for the event subscription.\r\nUses Azure Event Grid's identity to acquire the authentication tokens being used during delivery / dead-lettering."
        },
```

and 

```json 
    "EventSubscriptionDestination": {
      "description": "Information about the destination for an event subscription.",
      "required": [
        "endpointType"
      ],
      "type": "object",
      "properties": {
        "endpointType": {
          "description": "Type of the endpoint for the event subscription destination.",
          "enum": [
            "WebHook",
            "EventHub",
            "StorageQueue",
            "HybridConnection",
            "ServiceBusQueue",
            "ServiceBusTopic",
            "AzureFunction"
          ],
          "type": "string",
          "x-ms-enum": {
            "name": "EndpointType",
            "modelAsString": true
          }
        }
      },
      "discriminator": "endpointType"
    },
```
and

```json
    "StorageQueueEventSubscriptionDestination": {
      "description": "Information about the storage queue destination for an event subscription.",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/EventSubscriptionDestination"
        }
      ],
      "properties": {
        "properties": {
          "$ref": "#/definitions/StorageQueueEventSubscriptionDestinationProperties",
          "description": "Storage Queue Properties of the event subscription destination.",
          "x-ms-client-flatten": true
        }
      },
      "x-ms-discriminator-value": "StorageQueue"
    },
```

So perhaps some combination of discriminator and AllOf that the generator doesn't handle?

The generated Rust code has the model for the `StorageQueueEventSubscriptionDestination` type but isn't using it in the `EventSubscription` create or update request.

**Comment by JWT95** [comment]
@johnbatty as discussed

**Comment by johnbatty** [comment]
Further information on schema discriminators:
- [x-ms-discriminator](https://github.com/Azure/autorest/blob/main/docs/extensions/swagger-extensions-examples/x-ms-discriminator-value/readme.md)
- [Swagger polymorphism](https://gist.github.com/leedm777/5730877#polymorphism)
- [OpenAPI spec for discriminator](https://spec.openapis.org/oas/v3.1.0#discriminator-object)
  - Note that in this spec the discriminator has a required `propertyName` field, which the Azure specs do not have

**Comment by cataggar** [comment]
I added support for unions in #1414. It should be possible now.

https://docs.rs/azure_mgmt_eventgrid/0.16.0/azure_mgmt_eventgrid/package_2022_06/models/struct.EventSubscriptionProperties.html


pub struct EventSubscriptionProperties {
    pub topic: [Option](https://doc.rust-lang.org/nightly/core/option/enum.Option.html)<[String](https://doc.rust-lang.org/nightly/alloc/string/struct.String.html)>,
    pub provisioning_state: [Option](https://doc.rust-lang.org/nightly/core/option/enum.Option.html)<[ProvisioningState](https://docs.rs/azure_mgmt_eventgrid/0.16.0/azure_mgmt_eventgrid/package_2022_06/models/event_subscription_properties/enum.ProvisioningState.html)>,
    pub destination: [Option](https://doc.rust-lang.org/nightly/core/option/enum.Option.html)<[EventSubscriptionDestinationUnion](https://docs.rs/azure_mgmt_eventgrid/0.16.0/azure_mgmt_eventgrid/package_2022_06/models/enum.EventSubscriptionDestinationUnion.html)>,
    pub delivery_with_resource_identity: [Option](https://doc.rust-lang.org/nightly/core/option/enum.Option.html)<[DeliveryWithResourceIdentity](https://docs.rs/azure_mgmt_eventgrid/0.16.0/azure_mgmt_eventgrid/package_2022_06/models/struct.DeliveryWithResourceIdentity.html)>,
    pub filter: [Option](https://doc.rust-lang.org/nightly/core/option/enum.Option.html)<[EventSubscriptionFilter](https://docs.rs/azure_mgmt_eventgrid/0.16.0/azure_mgmt_eventgrid/package_2022_06/models/struct.EventSubscriptionFilter.html)>,
    pub labels: [Vec](https://doc.rust-lang.org/nightly/alloc/vec/struct.Vec.html)<[String](https://doc.rust-lang.org/nightly/alloc/string/struct.String.html)>,
    pub expiration_time_utc: [Option](https://doc.rust-lang.org/nightly/core/option/enum.Option.html)<[OffsetDateTime](https://docs.rs/time/0.3.29/x86_64-unknown-linux-gnu/time/offset_date_time/struct.OffsetDateTime.html)>,
    pub event_delivery_schema: [Option](https://doc.rust-lang.org/nightly/core/option/enum.Option.html)<[EventDeliverySchema](https://docs.rs/azure_mgmt_eventgrid/0.16.0/azure_mgmt_eventgrid/package_2022_06/models/event_subscription_properties/enum.EventDeliverySchema.html)>,
    pub retry_policy: [Option](https://doc.rust-lang.org/nightly/core/option/enum.Option.html)<[RetryPolicy](https://docs.rs/azure_mgmt_eventgrid/0.16.0/azure_mgmt_eventgrid/package_2022_06/models/struct.RetryPolicy.html)>,
    pub dead_letter_destination: [Option](https://doc.rust-lang.org/nightly/core/option/enum.Option.html)<[DeadLetterDestinationUnion](https://docs.rs/azure_mgmt_eventgrid/0.16.0/azure_mgmt_eventgrid/package_2022_06/models/enum.DeadLetterDestinationUnion.html)>,
    pub dead_letter_with_resource_identity: [Option](https://doc.rust-lang.org/nightly/core/option/enum.Option.html)<[DeadLetterWithResourceIdentity](https://docs.rs/azure_mgmt_eventgrid/0.16.0/azure_mgmt_eventgrid/package_2022_06/models/struct.DeadLetterWithResourceIdentity.html)>,
}
