### ISSUE TITLE
How to pass token credentials to azure_security_keyvault client dynamically

### ISSUE THREAD

**Issue by omofolarin** [Azure/azure-sdk-for-rust#1278]
Hi, please I'm trying to use the KeyClient::new(vault_url, token_credentials)

I need to be able to pass token credentials dynamically based on the different tenants of my API. I've looked at the azure identity crate and I'm not sure if there's a way to go about it.

Thanks

**Comment by omofolarin** [comment]
Thanks for the response @johnbatty I'm going over Azure identity documentation to be sure I understand how to go about it.

**Comment by demoray** [comment]
Based on the discussion, I believe this issue is addressed.  Please re-open if you have further concerns with this issue.
