### ISSUE TITLE
Cannot compile on Apple M1

### ISSUE THREAD

**Issue by christopher-wilke** [Azure/azure-sdk-for-rust#1283]
I am not able to compile the SDK on my Apple M1 processor. Seems the issue is related to `ring`.

`ring-0.14.6/pregenerated/aesv8-armx-linux64.S:193:1: error: unknown directive  .type GFp_aes_hw_decrypt,%function`

I believe this is a known issue, please see https://github.com/briansmith/ring/issues/1063

**Comment by cataggar** [comment]
Using `native-tls` is the default, not `rustls`. Which crate are you wanting to use and what features did you select?

**Comment by cataggar** [comment]
@christopher-wilke, that is an outdated crate, not to be used. Please see:
https://github.com/Azure/azure-sdk-for-rust/blob/main/HISTORY.md

**Comment by christopher-wilke** [comment]
@cataggar  Thx for your quick feedback.

The only thing I did was adding the `azure_sdk_for_rust` crate to my `Cargo.toml` file.  Then rust-analyzer crashed because of the error above.

`[dependencies]
azure_sdk_for_rust = "0.12.0"`

Is there anything I miss here?
