### ISSUE TITLE
iot hub: device twin desired_tags values should allow types besides String

### ISSUE THREAD

**Issue by wolf-0711** [Azure/azure-sdk-for-rust#1287]
In `iot_hub/src/service/operations/update_or_replace_twin` [^1]
the `desired_tags` field is defined as `HashMap<String, String>` but according to the documentation [^2] _[a]ll values in JSON objects can be of the following JSON types: boolean, number, string, object. Arrays are also supported._

[^1]:  https://github.com/Azure/azure-sdk-for-rust/blob/main/sdk/iot_hub/src/service/operations/update_or_replace_twin.rs#L18
[^2]: https://learn.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins

**Comment by demoray** [comment]
In similar situations, we use return a `serde_json::Value`.  This should be a straightforward change.
