### ISSUE TITLE
Unable to sign blobs (SAS) when using TokenCredential

### ISSUE THREAD

**Issue by Nohac** [Azure/azure-sdk-for-rust#1298]
Hi.

I'm having a problem where I need to add SAS tokens to blobs from a service I'm working on so that an application can get time limited access to media files.

Using the azurite emulator locally, this works fine, but when running the service on azure using `TokenCredential` to authenticate against azure blob storage, I'm getting the following error message:
```
Shared access signature generation - SAS can be generated only from key and account clients
```

I asked ChatGPT for a solution, and it told me this:

> For a SAS token to work with Azure AD (TokenCredential), you should use user delegation SAS. The Rust SDK might not support this at the moment. Azure SDKs are under active development and the feature you're looking for may be included in a future release.

I tried looking into it, and I found that other SDK's have this feature:
```c#
var userDelegationKey = await blobServiceClient
    .GetUserDelegationKeyAsync(DateTimeOffset.UtcNow, 
                               DateTimeOffset.UtcNow.AddDays(7));
```
([source](https://www.codewithadam.com/Azure/generating-sas-token-azure-managed-identity-User-Delegation/))

Unfortunately, searching through the azure sdk for rust docs, I can't find anything to solve this problem.

Any suggestions or help is appreciated.

**Comment by Nohac** [comment]
I just saw that https://github.com/Azure/azure-sdk-for-rust/issues/1346 was closed as complete. Just so I'm not wasting to much time on this, that PR was only for creating a user delegation key, but it's still not possible to get a SAS token from it?

**Comment by demoray** [comment]
That's correct.  The first step is available but using them is not yet.

This project is maintained on a volunteer basis at this point, so some tasks such as this one get broken down into individual components.
