### ISSUE TITLE
Resource Graph API Version for China Endpoint

### ISSUE THREAD

**Issue by giridharmb** [Azure/azure-sdk-for-rust#1299]
#### Using Resource Graph, how can we fetch records for Azure China Endpoint ?

Looks like it is expecting specific API version of resource graph:

```bash
The resource type 'resources' could not be found in the namespace 'Microsoft.ResourceGraph' 
for api version '2022-10-01'. The supported api-versions 
are '2018-09-01-preview,2019-04-01,2021-03-01,2021-06-01-preview'
```

#### Error that I'm seeing

```bash
Err(
    Error {
        context: Full(
            Custom {
                kind: HttpResponse {
                    status: NotFound,
                    error_code: Some(
                        "InvalidResourceType",
                    ),
                },
                error: HttpError {
                    status: NotFound,
                    details: ErrorDetails {
                        code: Some(
                            "InvalidResourceType",
                        ),
                        message: Some(
                            "The resource type 'resources' could not be found in the namespace 'Microsoft.ResourceGraph' for api version '2022-10-01'. The supported api-versions are '2018-09-01-preview,2019-04-01,2021-03-01,2021-06-01-preview'.",
                        ),
                    },
                    headers: {
                        "expires": "-1",
                        "x-ms-correlation-request-id": "1ea7eb2e-4374-4ea7-b857-bd0dfa5e81ce",
                        "content-type": "application/json; charset=utf-8",
                        "content-length": "268",
                        "x-ms-failure-cause": "gateway",
                        "x-content-type-options": "nosniff",
                        "x-ms-request-id": "1ea7eb2e-4374-4ea7-b857-bd0dfa5e81ce",
                        "x-ms-routing-request-id": "CHINANORTH3:20230609T205622Z:1ea7eb2e-4374-4ea7-b857-bd0dfa5e81ce",
                        "strict-transport-security": "max-age=31536000; includeSubDomains",
                        "x-ms-ratelimit-remaining-tenant-reads": "14999",
                        "pragma": "no-cache",
                        "date": "Fri, 09 Jun 2023 20:56:21 GMT",
                        "cache-control": "no-cache",
                    },
                    body: b"{\"error\":{\"code\":\"InvalidResourceType\",\"message\":\"The resource type 'resources' could not be found in the namespace 'Microsoft.ResourceGraph' for api version '2022-10-01'. The supported api-versions are '2018-09-01-preview,2019-04-01,2021-03-01,2021-06-01-preview'.\"}}",
                },
            },
            "server returned error status which will not be retried: 404",
        ),
    },
)
```

Code sample that I'm using >

**Comment by giridharmb** [comment]
`// Using Azure Resource Graph, fetch Virtual Machine Records

use azure_identity::{ClientSecretCredential, TokenCredentialOptions};
use std::{env, sync::Arc};
use std::any::Any;
use std::borrow::Cow;
use std::future::IntoFuture;
use std::str::FromStr;

use azure_core::{AppendToUrlQuery, ClientOptions, ExponentialRetryOptions, new_http_client, RetryOptions};
use azure_core::auth::TokenCredential;
use azure_core::headers::content_type_from_headers;
use azure_core::query_param::API_VERSION;
use azure_core::resource_manager_endpoint::AZURE_CHINA_CLOUD;

use azure_identity::authority_hosts::{AZURE_CHINA, AZURE_PUBLIC_CLOUD};


use azure_mgmt_resourcegraph::models::{QueryRequest, QueryRequestOptions, ResourceChangesRequestParameters};
use azure_mgmt_resourcegraph::Client as AzureResourceGraphClient;
use azure_core::Url;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {

    let my_options = TokenCredentialOptions::new(AZURE_CHINA.parse().unwrap());

    let client_id = "<CLIENT_ID_FOR_CHINA>";
    let client_secret = "<CLIENT_SECRET_FOR_CHINA>";
    let tenant_id = "<CHINA_TENANT_ID>";

    let client_sec_creds = ClientSecretCredential::new(
        azure_core::new_http_client(),
        my_http_client,
        tenant_id.parse().unwrap(),
        client_id.parse().unwrap(),
        client_secret.parse().unwrap(),
        my_options,
    );

    let mut creds = Arc::new(client_sec_creds);

    let exponential_retry = ExponentialRetryOptions {
        initial_delay: Default::default(),
        max_retries: 100,
        max_total_elapsed: Default::default(),
        max_delay: Default::default(),
    };

    let retry_options = RetryOptions::exponential(exponential_retry);

    let my_az_rg_client = AzureResourceGraphClient::builder(creds).endpoint(azure_core::resource_manager_endpoint::AZURE_CHINA_CLOUD).retry(retry_options).build();

    // Fetch only the first 10 records

    let my_top = 10;
    let my_skip = 0;

    let my_query = "Resources | where type =~ 'microsoft.compute/virtualmachines'".to_string();

    let query_options = QueryRequestOptions {
        skip_token: None,
        top: Option::from(my_top),
        skip: Option::from(my_skip),
        result_format: None,
        allow_partial_scopes: None,
        authorization_scope_filter: None,
    };

    let custom_query_request = QueryRequest {
        subscriptions: vec![],
        management_groups: vec![],
        query: my_query,
        options: Option::from(query_options),
        facets: vec![],
    };

    let query_request = QueryRequest::from(custom_query_request);

    let resources = my_az_rg_client.resources(query_request).await;

    println!("{:#?}", resources);

    Ok(())
}`

**Comment by giridharmb** [comment]
https://gist.github.com/giridharmb/06025f097c628e1672469a351b926f8e

**Comment by giridharmb** [comment]
If I replace:

```rust
    let client_id = "<CLIENT_ID_FOR_CHINA>";
    let client_secret = "<CLIENT_SECRET_FOR_CHINA>";
    let tenant_id = "<CHINA_TENANT_ID>";
```

With Credentials for US Region

And also replace this:

```rust
azure_core::resource_manager_endpoint::AZURE_CHINA_CLOUD
```

With 

```rust
azure_core::resource_manager_endpoint::AZURE_PUBLIC_CLOUD
```

Then the code executes without any errors and I'm able to fetch records (in this case, Virtual Machines) using Resource Graph.

**Comment by giridharmb** [comment]
By the way, the required permissions (Microsoft Graph API) 
have already been granted to `<CLIENT_ID_FOR_CHINA>`

**Comment by giridharmb** [comment]
Is there a way to over-ride Graph API Version while making Resource Graph requests ?

**Comment by ctaggart** [comment]
It is unfortunate that the latest stable API version is not supported. 😞 

> The supported api-versions are '2018-09-01-preview,2019-04-01,2021-03-01,2021-06-01-preview'."

Here are the versions that are published with this crate:

https://github.com/Azure/azure-sdk-for-rust/blob/5014404dff3cd77faf37a7077ec67bb6a2cf1f4c/services/mgmt/resourcegraph/Cargo.toml#L34-L43

I recommend trying `package-preview-2021-06` as documented in [tags.md](https://github.com/Azure/azure-sdk-for-rust/blob/main/services/tags.md). So it would be:

```
azure_mgmt_resourcegraph = { version = "0.12.0", default-features = false, features = ["package-preview-2021-06", "enable_reqwest"] }
```
