### ISSUE TITLE
Remove the need for extra params in request builders

### ISSUE THREAD

**Issue by thomastaylor312** [Azure/azure-sdk-for-rust#130]
This is related to #129, but currently it is hard to capture a request builder within a struct. So for example. if I wanted to reuse the same configuration to make a request to a container:

```rust
let thing = blob_client
    .get_blob()
    .with_container_name(BLOB_CONTAINER);
MyStruct { thing }
```

In this case, I now have the builder struct that has at least one (if not more) explicit lifetimes and 2 or more type parameters. If I want to store this in a struct, that struct now has to have those exact same parameters and lifetimes set, which is a bit of a verbose overkill. Like I mentioned this would likely be solved by #129, but wanted to bring it up in a separate issue just in case

**Comment by rylev** [comment]
This should now be be fixed with the new style of builders introduced in #147.
