### ISSUE TITLE
put_block_list fails after removing the md5 feature.

### ISSUE THREAD

**Issue by NickButcher1** [Azure/azure-sdk-for-rust#1314]
I have dependencies on
azure_storage = "0.13.0"
azure_storage_blobs = {version = "0.13.0", features = ["md5"]}
azure_core = "0.13.0"

I have a working client which uploads blobs to Azure storage.

I want to remove the md5 feature (as now allowed by https://github.com/Azure/azure-sdk-for-rust/pull/1292), but when I do so, I see put_block_list requests fail with error "header not found content-md5". Note that put_block requests succeed.

I think I can see the bug:

API docs for put_block and put_block_list say that if I omit the content-md5 header from the request then it will also be omitted from the response.
- https://learn.microsoft.com/en-us/rest/api/storageservices/put-block-list?tabs=azure-ad
- https://learn.microsoft.com/en-us/rest/api/storageservices/put-block?tabs=azure-ad

But looking at the code I see:
- PutBlockResponse.from_headers() allows for content_md5 to be optional.
- PutBlockListResponse.from_headers() still requires content_md5 to be present. This is the bug.

**Comment by demoray** [comment]
@NickButcher1 thanks for the report.  [azure_storage_blobs 0.13.1](https://crates.io/crates/azure_storage_blobs/0.13.1) should fix this issue.
