### ISSUE TITLE
Tokio v1.0 is not working with azure_sdk_keyvault.

### ISSUE THREAD

**Issue by sinister296** [Azure/azure-sdk-for-rust#1343]
The current project setup I have made uses tokio 1.0 if some of the other crates that I have used in my application. The issue is when I try to use get_secrets() for the KeyVaultClient, the program panics saying 'thread 'main' panicked at 'not currently running on a tokio 0.2'. 

The tokio 1.0 dependency cannot be removed because the crate which uses it is a crucial part of the application.

Is there any way to make it work with tokio 1.0?

**Comment by demoray** [comment]
azure_sdk_keyvault, as available via crates.io, is not part of this SDK.  Rather, it was developed and contributed by @guywaldman and last updated 3 years ago.

The crate for keyvault that is maintained as part of the Azure SDK for Rust is [azure_security_keyvault](https://crates.io/crates/azure_security_keyvault), and this crate supports tokio 1.0.
