### ISSUE TITLE
Azure storage: support Get User Delegation Key

### ISSUE THREAD

**Issue by KodyKantor** [Azure/azure-sdk-for-rust#1346]
When an Azure Storage account is accessed via Azure AD the client secret cannot be used to generate SAS tokens. Instead, the clients are expected to retrieve a short-lived user delegation key.

https://learn.microsoft.com/en-us/rest/api/storageservices/get-user-delegation-key

The user delegation key can later be used to create user delegation SAS tokens.

The user delegation key expires occasionally. Ideally the SDK would additionally refresh this token in the background as necessary.

**Comment by KodyKantor** [comment]
Related to #1298.

CC @mario-guerra

**Comment by demoray** [comment]
This is now available in 0.16.0

https://docs.rs/azure_storage_blobs/latest/azure_storage_blobs/prelude/struct.BlobServiceClient.html#method.get_user_deligation_key
