### ISSUE TITLE
`AzureCliCredential` parses an incorrect token expiry time in multi-threaded Unix applications

### ISSUE THREAD

**Issue by pencels** [Azure/azure-sdk-for-rust#1371]
## Description

To get an access token, `AzureCliCredential` shells out to `az account get-access-token` and parses up the `expiresOn` string as a datetime value. Since `az` formats the datetime without a timezone offset, it assumes the offset with `date::assume_local()`.

https://github.com/Azure/azure-sdk-for-rust/blob/f97818515f46904149951c659a165bf158ea926a/sdk/identity/src/token_credentials/azure_cli_credentials.rs#L19-L26

`date::assume_local()` delegates to [`time`](https://github.com/time-rs/time)'s function `UtcOffset::current_local_offset()`.

https://github.com/Azure/azure-sdk-for-rust/blob/f97818515f46904149951c659a165bf158ea926a/sdk/core/src/date/mod.rs#L116-L119

For most Unix systems, `UtcOffset::current_local_offset()` will return `Ok(offset)` for single-threaded applications, and `Err(IndeterminateOffset)` for multi-threaded applications, as defined by [this function](https://github.com/time-rs/time/blob/6aa8db51b9949c46b352579c9e951056b8ce333f/time/src/sys/local_offset_at/unix.rs#L130).

In my case, I am running my application on Ubuntu (WSL), and my application is multi-threaded. So this offset is always indeterminate.

(Aside: There's [a](https://github.com/time-rs/time/issues/293) [whole](https://github.com/time-rs/time/issues/380) [conversation](https://internals.rust-lang.org/t/synchronized-ffi-access-to-posix-environment-variable-functions/15475) about thread-safety of accessing local time zone data, which is the reason why this behavior exists. If certain things change in the Rust ecosystem, then this problem may just resolve itself as simply as installing a new release of `time`.)

Because the offset is indeterminate, `date::assume_local()` will default the expiry time to being in the UTC time zone, when it should be in my local (PDT) time zone. This is obviously incorrect behavior, because the expiry time is now hours off from the actual time it should represent.

This can manifest as bugs further down the line, e.g. in `AutoRefreshingTokenCredential` where recently cached tokens are refreshed constantly because they are viewed as expired. Each token refresh adds consistent overhead to SDK calls. In particular, this led my calls through SDK clients to take approximately ~1.3s each rather than an expected ~90ms each when the token was only refreshed as needed.

## Workarounds/Solutions

- As users of the SDK, what we can do to mitigate this:
    - (RECOMMENDED) Use other credential types. This will avoid the issue, simply because other credential types don't interact with this code.
    - (NOT recommended) Manually override the thread-count check by using the [`set_soundness()`](https://github.com/time-rs/time/blob/6aa8db51b9949c46b352579c9e951056b8ce333f/time/src/util.rs#L87) function provided by `time`. This requires some understanding of the thread-safety of your application and probably isn't worth the effort to do correctly.
- As SDK authors, what we can do to fix this:
    - Wait for the Rust ecosystem to figure out a way to manage thread-safe access of local time information, then consume this new thread-safe interface.
    - Push for changes in the Azure CLI output. It seems az-cli was looking into representing the expiry time as an integer timestamp instead (https://github.com/Azure/azure-cli/issues/19700). If implemented, the `AzureCliCredential` would just have to deserialize the epoch timestamp, circumventing the need to determine the system's local offset. However, I haven't seen much activity on this issue, so I'm not sure what the timelines are there.
    - We could also try to use `set_soundness()`  in the SDK itself, but this is probably unsafe. Again, not recommended.

## Relevant Issues/PRs
- https://github.com/Azure/azure-cli/issues/19700
- https://github.com/Azure/azure-cli/pull/20219
- https://github.com/time-rs/time/issues/296
- https://github.com/time-rs/time/issues/293

**Comment by demoray** [comment]
@cataggar, with the recent changes made to chrono, we might want to revisit our migration from `chrono` to `time` as it relates to this.  Specifically, `chrono` no longer relies on `libc::localtime_r`, instead replies on code originally from the `tz-rs` crate to handle this in a thread-safe fashion.

Ref: https://github.com/chronotope/chrono/releases/tag/v0.4.30

**Comment by cataggar** [comment]
I think it is best that the Azure CLI pass the unix timestamp along.
I opened https://github.com/Azure/azure-cli/issues/19700 to see if we could this going again.

**Comment by cataggar** [comment]
My PR to pass the unix timestamp was replaced with https://github.com/Azure/azure-cli/pull/27476

**Comment by demoray** [comment]
This has been mitigated in 0.16.2, released earlier today.  In the future, we should make use of the az-cli feature that was linked earlier if the functionality is available.

For existing az-cli instances, we use `tz-rs` to attempt to identify and resolve the timezone.
