### ISSUE TITLE
Missing latest package-2023-05 api version for CognitiveServices

### ISSUE THREAD

**Issue by patryk-s** [Azure/azure-sdk-for-rust#1382]
Thanks for the hard work that is put into this repo!

I noticed that `DeploymentProperties` do not have the [rateLimits](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/resource-manager/Microsoft.CognitiveServices/stable/2023-05-01/cognitiveservices.json#L3543C10-L3543C20) field, and then I found that the `package-2023-05` version is not available (and [denied](https://github.com/Azure/azure-sdk-for-rust/blob/main/services/mgmt/cognitiveservices/autorust.toml)). Will this version be generated soon(ish)?

**Comment by cataggar** [comment]
The problem with `package-2023-05` is that they added operations like `Models_List`. 

``` json
"/subscriptions/{subscriptionId}/providers/Microsoft.CognitiveServices/locations/{location}/models": {
      "get": {
        "tags": [
          "Models"
        ],
        "operationId": "Models_List",
        "description": "List Models.",
```

The package can be generated by running:
cargo run --release -p azure-autorust -- -p azure_mgmt_cognitiveservices

And when you try to compile it, you get this error:
```
error[E0428]: the name `models` is defined multiple times
    --> mgmt\cognitiveservices\src\package_2023_05\mod.rs:2594:1
     |
5    | pub mod models;
     | --------------- previous definition of the module `models` here
...
2594 | pub mod models {
     | ^^^^^^^^^^^^^^ `models` redefined here
```

One solution would be to add a property to `autorest.toml` that allows setting the `models` module name to something other than "models". For example, it could be set to "model".

**Comment by patryk-s** [comment]
Where do I run this exactly, or what steps am I missing to get this working?
> cargo run --release -p azure-autorust -- -p azure_mgmt_cognitiveservices

I'm getting this error when I tried in different directories:
```
Error: Error { context: Custom(Custom { kind: Io, error: Os { code: 2, kind: NotFound, message: "No such file or directory" } }) }
```

**Comment by patryk-s** [comment]
cool, thanks a lot!
