### ISSUE TITLE
access to vault to have better error message

### ISSUE THREAD

**Issue by dzmitry-lahoda** [Azure/azure-sdk-for-rust#14]
try next with wrong az account:
```
    let mut key_vault_client = KeyVaultClient::new(&creds, "lahodapro");
    println!("list secrets for");
    let secrets = key_vault_client.list_secrets().await?;
```
Expected: error message about wrong auth usage
Actual: error about some value is missing
Notes: that is very important that entry point to azure via auth to have guiding errors, not cryptic

**Comment by ftt** [comment]
I think this should be covered by **[Proposal] Error Handling #625**.

**Comment by rylev** [comment]
Just as an FYI: #625 won't solve this but it does provide facilities for improving the error message.
