### ISSUE TITLE
Support half open ranges

### ISSUE THREAD

**Issue by arpad-m** [Azure/azure-sdk-for-rust#1438]
Both the standard `Range` HTTP header (or `range` in HTTP/2 lingo) as well as the `x-ms-range` header support half open ranges, meaning ones like `bytes=1234-`.

https://learn.microsoft.com/en-us/rest/api/storageservices/specifying-the-range-header-for-blob-service-operations

The SDK's [Range type](https://docs.rs/azure_core/0.16.0/azure_core/request_options/struct.Range.html) does not however: it always requires an end to be specified.

As the end is exposed, it would be a semver breaking change to turn the `end` field on the `Range` into an option (or even a bool field `has_end` or such as the struct is exhaustively public).

**Comment by demoray** [comment]
If this is something we include, we might do something akin to the [SliceIndex](https://doc.rust-lang.org/std/slice/trait.SliceIndex.html) trait, where it supports multiple of the base range types (including [RangeFrom](https://doc.rust-lang.org/std/ops/struct.RangeFrom.html)).

**Comment by arpad-m** [comment]
The spec for the `range` header [says](https://www.rfc-editor.org/rfc/rfc9110#name-range-specifiers) that there is two possible ranges, one "int range" which has an obligatory start and an optional end, and one "suffix range", which has no start but an end. Then the `range` header is a comma seperated list of int or suffix ranges.
