### ISSUE TITLE
GetBlobResponse contains no metadata

### ISSUE THREAD

**Issue by arpad-m** [Azure/azure-sdk-for-rust#1439]
The [Docs for the HTTP API](https://learn.microsoft.com/en-us/rest/api/storageservices/get-blob?tabs=azure-ad) mention that metadata headers are returned for the get blob operation:

> `x-ms-meta-name:value` | A set of name-value pairs that's associated with this blob as user-defined metadata.

The [`GetBlobResponse`](https://docs.rs/azure_storage_blobs/latest/azure_storage_blobs/blob/operations/struct.GetBlobResponse.html) type however contains no field that has the metadata. There is the `get_metadata` API call, but it only returns the metadata, not the content. If you are interested in both the content and the metadata, and you use the SDK, you'd have to issue two HTTP requests, and then do some additional measures to ensure atomicity of the operation.

I think the SDK should expose the metadata obtained from the headers in the response.

**Comment by krishanjmistry** [comment]
Hi @arpad-m,
It looks like the metadata you're after should be accessible via the `blob` field of the [`GetBlobResponse`](https://docs.rs/azure_storage_blobs/latest/azure_storage_blobs/blob/operations/struct.GetBlobResponse.html).
The `blob` field stores a value of [`Blob`](https://docs.rs/azure_storage_blobs/latest/azure_storage_blobs/blob/struct.Blob.html), it looks like this captures and exposes the metadata you're after.

**Comment by arpad-m** [comment]
Oh indeed that's the case. Thanks for pointing that out! I suppose then this is resolved.
