### ISSUE TITLE
Missing headers in put_block() method.

### ISSUE THREAD

**Issue by Somsubro-Banerjee** [Azure/azure-sdk-for-rust#1450]
I am trying to use the put_block function to upload a large file in chunks to Azure blob storage.

` let mut block_ids: Vec<BlobBlockType> = Vec::new();`

and then inside a loop I run the following commands:

` let block_id: BlockId = base64::encode(&total_bytes_uploaded.to_string()).into();`
 ` block_ids.push(BlobBlockType::Uncommitted(block_id.clone()));`
 ` let result = blob_client
                .put_block(block_id, Arc::clone(&buffer)[..n].to_vec())
                .await;`

 But I get a error response from azure:
 
 ` Upload Unsuccessful: Error { context: Full(Custom { kind: HttpResponse { status: BadRequest, error_code: Some("InvalidBlobOrBlock") }, error: HttpError { status: BadRequest, details: ErrorDetails { code: Some("InvalidBlobOrBlock"), message: None }, headers: {"x-ms-error-code": "InvalidBlobOrBlock", "x-ms-request-id": "fd85d579-801e-004d-8000-0b671b000000", "content-length": "234", "x-ms-version": "2020-10-02", "content-type": "application/xml", "server": "Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0", "date": "Mon, 30 Oct 2023 07:11:08 GMT"}, body: b"\xef\xbb\xbf<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>InvalidBlobOrBlock</Code><Message>The specified blob or block content is invalid.\nRequestId:fd85d579-801e-004d-8000-0b671b000000\nTime:2023-10-30T07:11:08.5751574Z</Message></Error>" } }, "server returned error status which will not be retried: 400") }`
 
 which basically tells my content_type is not defined. I am trying to upload a large zip file (about 3.5gb in size) in smaller chunks. 
 
 So I believe in the put_block() function we need a another header which specifies the content type ? like we have it in the put_block_blob() method ? as this ?
 

 
![image](https://github.com/Azure/azure-sdk-for-rust/assets/29462545/c8cf04b7-85a3-4974-9d1c-26160e352e9d)

If you have any other way of uploading large files to azure blob can somebody please help ?

**Comment by demoray** [comment]
I regularly use this SDK to upload multiple-gig files using put_block.  The implementation from one of my projects that uses put_blob to upload large files is available here:  https://github.com/microsoft/avml/blob/main/src/upload/blobstore.rs

I do not believe this is an issue that relates to content-type.  Azure has a trouble-shooting guide that discusses potential issues that could result in this error.  Could one of these be an issue relating to your usage? 

https://learn.microsoft.com/en-us/troubleshoot/azure/general/invalid-blob-or-block-content-or-invalid-block-list

**Comment by Somsubro-Banerjee** [comment]
Yes, the Issue I am facing is one among them, it's the `InvalidBlockOrBlob`. Let me go through the document and try to debug it.
Let me also take look at the repo you provide and figure something out of it.

**Comment by Somsubro-Banerjee** [comment]
Can you tell me what am I missing out here ?

`if opt.status.success() {
        update_status = "Completed";

        debug!("Starting upload for the Output file");

        let file_path = format!("/home/H494655/UniSim-Downloader/hci-airgap-packages-bash/UniSim/Package.zip");

        let mut file_data = Vec::new();
        let mut file = File::open(&file_path)?;

        file.read_to_end(&mut file_data)?;

        debug!("{:?}",file.metadata());

        let storage_credential = StorageCredentials::Key(account.clone(), access_key);
        let blob_client = ClientBuilder::new(account, storage_credential).blob_client(&container, blob_name);

        // let result = blob_client.put_block_blob(file_data).content_type("application/zip").await;

        let mut file = File::open(file_path)?;
        
        let buffer = Arc::new(vec![10; 1024 * 1024]);
        let mut total_bytes_uploaded: usize = 0; // Counter for total bytes uploaded

        let mut block_ids: Vec<BlobBlockType> = Vec::new();

        loop {
            let n = file.read(&mut Arc::make_mut(&mut buffer.clone())[..])?;
            if n == 0 {
                break;
            }

            let block_id: BlockId = base64::encode(&total_bytes_uploaded.to_string()).into();
            block_ids.push(BlobBlockType::Uncommitted(block_id.clone()));

            let result = blob_client
                .put_block(block_id, Arc::clone(&buffer)[..n].to_vec())
                .await;
        
            match result {
                Ok(_) => {
                    total_bytes_uploaded += n;
                    info!("Uploaded {} bytes so far", total_bytes_uploaded);
                    // info!("Upload Successful!");
                },
                Err(err) => {
                    error!("Upload Unsuccessful: {:?}", err);
                    return Err(convert_azure_error_to_io_error(err));
                }
            }
        }

        let block_list = BlockList { blocks: block_ids };
        let result = blob_client.put_block_list(block_list).await;
        match result {
            Ok(_) => info!("All blocks committed successfully!"),
            Err(err) => {
                error!("Failed to commit blocks: {:?}", err);
                return Err(convert_azure_error_to_io_error(err));
            }
        }
        download_url = blob_client.url().unwrap().to_string();
        debug!("file is available at {}", download_url);
    } else {
        update_status = "Failed";
    }`

**Comment by demoray** [comment]
Well, I have a few issues.  

First, I don't think the following works as you expect.  When I use this code, every byte in the resulting block is "\x0a".
`let n = file.read(&mut Arc::make_mut(&mut buffer.clone())[..])?;`

Second, the BlockId has an issue.  Per the documentation: 
> A valid Base64 string value that identifies the block. Before it's encoded, the string must be less than or equal to 64 bytes in size.  For a specified blob, the length of the value for the blockid parameter must be the same size for each block.`
https://learn.microsoft.com/en-us/rest/api/storageservices/put-block?tabs=azure-ad

In your implementation, the first Block Id is "0" (1 byte long), the second block id is "1048576" (7 bytes long).

**Comment by demoray** [comment]
I simplified your example as the following, which works to upload large files:

```rust
    let mut file = File::open(&args.file)?;

    let mut total_bytes_uploaded: usize = 0; // Counter for total bytes uploaded

    let mut blocks = BlockList::default();

    loop {
        let mut buffer = vec![0; 10 * 1024 * 1024];

        let n = file.read(&mut buffer)?;
        if n == 0 {
            break;
        }
        buffer.truncate(n);

        let block_id = BlockId::new(format!("{total_bytes_uploaded:016x}"));
        println!("block id: {block_id:?} {n}");
        blocks
            .blocks
            .push(BlobBlockType::Uncommitted(block_id.clone()));

        let response = blob_client
            .put_block(block_id, buffer)
            .await
            .context("upload failed")?;

        println!("response: {response:?}");
        total_bytes_uploaded += n;
    }

    blob_client
        .put_block_list(blocks)
        .await
        .context("failed to commit")?;

    let download_url = blob_client.url().unwrap().to_string();
    println!("file is available at {}", download_url);
```

**Comment by Somsubro-Banerjee** [comment]
Thank you for the explanation and for letting me know how to proceed. Let me try to use your approach and I will let you know if this works and I will close the Issue.

Thanks again Appreciate it :)

**Comment by Somsubro-Banerjee** [comment]
@demoray Thank you for your help and support, this worked like a charm. I will proceed to close this issue and also create a Stackoverflow question and answer so that it can reach out to people with similar issues and tag you of course!
