### ISSUE TITLE
Should `cosmos::CreateTriggerBuilder` take optional `TriggerType` and `TriggerOperation`

### ISSUE THREAD

**Issue by rylev** [Azure/azure-sdk-for-rust#150]
These fields are required but perhaps a sensible default can be picked for the user.

https://github.com/Azure/azure-sdk-for-rust/pull/147#discussion_r559672114

**Comment by MindFlavor** [comment]
I don't think a default should be chosen, they are an integral part of a trigger. In SQL, for example, are explicit (there is no default) so having one would be awkward for every DBA. Also I cannot imagine what a default would be.

**Comment by rylev** [comment]
`TriggerOperation::All` seems like a natural default to me, but I get the point about `TriggerType` as that doesn't seem to have a good default. If you think this wouldn't be helpful, we can close this.

**Comment by rylev** [comment]
Going to close this - requiring both arguments seems fine. If someone disagrees we can reopen this.
