### ISSUE TITLE
`azure_storage_blobs` 0.18.0 failed to publish

### ISSUE THREAD

**Issue by johnbatty** [Azure/azure-sdk-for-rust#1512]
The SDK 0.18.0 release happened yesterday, but the latest version of `azure_storage_blobs` on crates.io is 0.17.0:
https://crates.io/crates/azure_storage_blobs

I see that the version has been [bumped in the code to 0.18.0](https://github.com/Azure/azure-sdk-for-rust/blob/main/sdk/storage_blobs/Cargo.toml#L3), so can only assume that there was some problem in the publishing process.

**Comment by omid** [comment]
It's released on Friday, that's the reason :D

![Thou Shalt not deploy on Friday](https://img.devrant.com/devrant/rant/r_2096652_1qyBC.jpg)

**Comment by demoray** [comment]
Fixed.

https://crates.io/crates/azure-storage-blobs/0.18.0
