### ISSUE TITLE
How to set "x-ms-version" in a service client, e.g. a blob client

### ISSUE THREAD

**Issue by dlf-dds** [Azure/azure-sdk-for-rust#1514]
using it like this
```
let blob_client = ClientBuilder::new(account, storage_credentials)
        .cloud_location(cloud_location)
        .blob_client(container, blob_name);
    let data = data.as_bytes().to_vec();
    blob_client.put_block_blob(data).await?;
```
I don't see how to set the api version when using the azure sdk.

**Comment by dlf-dds** [comment]
I think it's hard coded here:
https://github.com/Azure/azure-sdk-for-rust/blob/aac41053c04585335d2764dc2d341750bc43fb38/sdk/storage/src/clients.rs#L27
...
Is there some way to modify this after the client is created, but before it is used?

**Comment by johnbatty** [comment]
It is possible to override the header value using a pipeline Policy:
https://github.com/Azure/azure-sdk-for-rust/issues/1290

**Comment by demoray** [comment]
Closed.  Thanks for providing the answer @johnbatty
