### ISSUE TITLE
Docs have failed to publish for some crates for several releases

### ISSUE THREAD

**Issue by krishanjmistry** [Azure/azure-sdk-for-rust#1535]
This isn't an exhaustive list, but a few examples where I've noticed failures.

The docs for the generated crate `azure_mgmt_network` have failed to publish with the message _recursive without indirection_. Links to docs.rs follow:
- https://docs.rs/crate/azure_mgmt_network/0.16.0
- https://docs.rs/crate/azure_mgmt_network/0.17.0
- https://docs.rs/crate/azure_mgmt_network/0.18.0

There's been some work in the past to counteract this - notably the `properties.boxed` section of the [`autorust.toml`](https://github.com/Azure/azure-sdk-for-rust/blob/main/services/mgmt/network/autorust.toml) file.  However, the source of failure here is introduction of new tags. The tags are taken from the README in the spec: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/network/resource-manager/readme.md

The tag which is currently failing is `profile_hybrid_2020_09_01` - there's a question here as to whether this tag needs to be generated at all.
However, it's also worth noting that the latest tag now is `package-2023-09` - which was released last week. When the Rust SDK crates are regenerated with the latest specs, this will be another faulty tag.

Another example I found whilst running `cargo clippy --all-features` locally was on the `azure_mgmt_hardwaresecuritymodules` crate. This time, docs have failed to publish since version 0.12 due to multiple definitions of models within the preview tags.
- https://docs.rs/crate/azure_mgmt_hardwaresecuritymodules/0.18.0

It's worth noting that something like this would have been spotted by `cargo clippy --all-features` or `cargo check  - something the GitHub actions which currently run don't do.

**Comment by cataggar** [comment]
Good idea. We have a Geneva Action that you can run from the Actions tab in any fork for any branch named `check-all-services`. May be we could add one named `clippy-all-services`.

- https://github.com/Azure/azure-sdk-for-rust/actions/workflows/check-all-services.yml
- https://github.com/Azure/azure-sdk-for-rust/blob/main/.github/workflows/check-all-services.yml
- https://github.com/Azure/azure-sdk-for-rust/blob/main/services/autorust/codegen/templates/check-all-services.yml.jinja

It would be good to run after updating the services. After new versions are published, you can monitor the failures at https://docs.rs/releases/recent-failures .

**Comment by demoray** [comment]
Do you mean github-action?

**Comment by demoray** [comment]
This should fix the issues, but does not ensure the issue is fixed long term.

https://github.com/Azure/azure-sdk-for-rust/pull/1545

**Comment by krishanjmistry** [comment]
> It would be good to run after updating the services. May be we could add one named clippy-all-services

Is there any reason we're not just updating the github-actions that run in all PR's to run `cargo clippy --all-features` instead? That way, any change that goes in meets this quality bar and there's less action on the user to run any actions manually.

**Comment by krishanjmistry** [comment]
This isn't isolated to generated services either...
- https://docs.rs/crate/azure_messaging_servicebus/0.19.0
- https://docs.rs/crate/azure_messaging_eventgrid/0.19.0
- https://docs.rs/crate/azure_iot_hub/0.19.0
