### ISSUE TITLE
Add support for PowerBI Fabric Capacities

### ISSUE THREAD

**Issue by DevLazio** [Azure/azure-sdk-for-rust#1542]
The azure_mgmt_powerbidedicated is not able to control the new Fabric Capacities.

What changed :
- provider changed from Microsoft.PowerBIDedicated to Microsoft.Fabric
- new api version : 2023-11-01

For example, to pause a PowerBI Capacity the crafted REST API request was : `https://management.azure.com/subscriptions/<subscription-id>/resourceGroups/<resource-group>/providers/Microsoft.PowerBIDedicated/capacities/<capacity-name>/suspend?api-version=2021-01-01`
for the new Fabric Capacity it is now :
`https://management.azure.com/subscriptions/<subscription-id>/resourceGroups/<resource-group>/providers/Microsoft.Fabric/capacities/<capacity-name>/resume?api-version=2023-11-01`

Using the Microsoft.Fabric provider or the new API version with the old capacities is not possible so I suppose it should be it's own service.

**Comment by cataggar** [comment]
Hi @DevLazio,

The `azure_mgmt_powerbidedicated` is published directly from the specs.
https://github.com/Azure/azure-sdk-for-rust/blob/main/services/mgmt/powerbidedicated/README.md

That readme has a link to the specs that it used:
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/powerbidedicated/resource-manager/readme.md

I do not see a Fabric API spec in https://github.com/Azure/azure-rest-api-specs/ . May be create an issue there?
