### ISSUE TITLE
CosmosDB: make PartitionKey mandatory

### ISSUE THREAD

**Issue by MindFlavor** [Azure/azure-sdk-for-rust#155]
While it was possible to use certain SKUs in the past that allowed a paritionless container this is no longer the case.
We should follow through and make it mandatory in the SDK as well.

For example [create document](https://github.com/Azure/azure-sdk-for-rust/blob/master/sdk/cosmos/src/requests/create_document_builder.rs) makes partition key(s) optional and should be changed. 

I also would like to take the time to discuss a partition key reimagining. Right now it's treated as an independent field from the serialized type while it's clearly not the case. 

For example, let's take the code of [examples/document_00.rs](https://github.com/Azure/azure-sdk-for-rust/blob/master/sdk/cosmos/examples/document_00.rs). 

We have a document defined like this:

[https://github.com/Azure/azure-sdk-for-rust/blob/bee90032290089297cfdd0c9f7ada3518890e2cb/sdk/cosmos/examples/document_00.rs#L13-L19](https://github.com/Azure/azure-sdk-for-rust/blob/bee90032290089297cfdd0c9f7ada3518890e2cb/sdk/cosmos/examples/document_00.rs#L13-L19)

Right now the only constraints in order to use it in Cosmos are:

1. to be `Serialize` and `Deserialize` (in practice, they are not both required at the same time  if you just want to insert/retrieve).
2. Have a field that matches the partition key specified in the container creation.

1 is enforced, 2 is not. 

What makes thing worse is that, right now, in every `CreateDocument`, `ReplaceDocument` etc... we accept an *arbitrary* value.

For example:

[https://github.com/Azure/azure-sdk-for-rust/blob/bee90032290089297cfdd0c9f7ada3518890e2cb/sdk/cosmos/examples/document_00.rs#L142-L146](https://github.com/Azure/azure-sdk-for-rust/blob/bee90032290089297cfdd0c9f7ada3518890e2cb/sdk/cosmos/examples/document_00.rs#L142-L146)

This is clearly a poor design solution because it allows the user to pass whatever they want to `partition_keys()` even tough the correct value is already in the serialized struct. Needless to say, a value that does not match the partition key will make the call fail.

In other words, we should be able to extract it automatically without asking for it at all. 

The call would then become:

```rust
 let create_document_response = collection_client 
     .create_document() 
     .execute(&doc) 
     .await?; 
```

Less verbose, and much less error prone.

One approach is to have a trait that must be implemented on every document. Something like:

```rust
pub trait CosmosDocument {
   fn partition_keys(&self) -> &PartitionKeys
}
```

So the code above will be amended like this:

```rust
impl<'a> CosmosDocument  for MySampleStruct<'a> {
  fn partition_keys(&self) -> &PartitionKeys {
      &self.id
  }
}
```

This way we could extract the *correct* value at runtime instead of asking for it from the user. 

This could also be automated via proc macro so the implementation becomes automatic. We could end up with something akin to `serde`:

```rust
 #[derive(Serialize, Deserialize, Debug)] 
 struct MySampleStruct<'a> { 
     #[cosmos(PartitionKey)]
     id: Cow<'a, str>, 
     a_string: Cow<'a, str>, 
     a_number: u64, 
     a_timestamp: i64, 
 } 
```

What do you think?

**Comment by rylev** [comment]
> While it was possible to use certain SKUs in the past that allowed a paritionless container this is no longer the case.
We should follow through and make it mandatory in the SDK as well.

Is there documentation somewhere that points to when it is possible to not use a partition? The documentation seems to indicate that this is optional. Is the documentation just misleading? If so, would you be able to list all the requests where the partition key is mandatory? We can then make them mandatory again in this requests.

> One approach is to have a trait that must be implemented on every document. 

In general I'm definitely favorable to this approach. I do have some specific concerns with your suggestion:

I believe the trait implementation would look different:

```rust
impl<'a> CosmosDocument  for MySampleStruct<'a> {
 // Note: We cannot borrow `PartitionKeys`, we must return an owned value
  fn partition_keys(&self) -> PartitionKeys {
      // Note: we need to convert into `PartitionKeys` explicitly
      [&self.id].into()
  }
}
```

Note for the proc-macro, we'd need to explicitly state that the user is deriving `CosmosDocument`:

```rust
 // Note: we must list `CosmosDocument` in the derive list
 #[derive(Serialize, Deserialize, Debug, CosmosDocument)] 
 struct MySampleStruct<'a> { 
     #[cosmos(PartitionKey)] // Note: I'd prefer `#[cosmos(partition_key)]`
     id: Cow<'a, str>, 
     a_string: Cow<'a, str>, 
     a_number: u64, 
     a_timestamp: i64, 
 } 
```
 
Thoughts?

Also cc @thomastaylor312 and @ctaggart. There were concerns about introducing proc macros, but this proc-macro would be optional, and we can put it behind a feature flag.

**Comment by MindFlavor** [comment]
Sorry, I have phrased it imprecisely. 

The non-partiotioned containers are deprecated: while still supported the users are not supposed to use them anymore. 
From the docs: [https://docs.microsoft.com/en-us/azure/cosmos-db/migrate-containers-partitioned-to-nonpartitioned](https://docs.microsoft.com/en-us/azure/cosmos-db/migrate-containers-partitioned-to-nonpartitioned)

> The non-partitioned containers are legacy and you should migrate your existing non-partitioned containers to partitioned containers to scale storage and throughput. Azure Cosmos DB provides a system defined mechanism to migrate your non-partitioned containers to partitioned containers. 

While we *could* allow the legacy container usage, I think we should start with the right foot and follow the recommended usage (particularly since we are not in 1.0 yet). Most SDKs do not support non-partitioned containers at all (C# at least does not albeit with some user confusion [https://stackoverflow.com/questions/55224670/cosmosdb-container-without-partitionkey](https://stackoverflow.com/questions/55224670/cosmosdb-container-without-partitionkey)).,

About the proc-macros, I think they could be worth the trouble: with a simple annotation the users will save a lot of typing a possibly a lot of runtime errors.

PS: apologies for my sloppy syntax above, I was thinking out loud, yours is much more precise.

**Comment by thomastaylor312** [comment]
I personally would prefer a proc-macro as a crate user. Completely fine if it is behind a feature flag too

**Comment by rylev** [comment]
We should check whether having multiple partition keys is possible or not. @MindFlavor

**Comment by rylev** [comment]
From the docs:
> Currently, the SQL API supports a single partition key, so this is an array containing just one value.

We should remove the ability to set more than one partition key.

**Comment by thomastaylor312** [comment]
If this is the case, should we just have the `partition_key` method take a single value instead of the need to wrap in an array? So: 

```rust
client.partition_key("my_id")
```

Instead of 

```rust
client.partition_key(["my_id"])
```
