### ISSUE TITLE
[docs] azure_identity docs seem to be wrong.

### ISSUE THREAD

**Issue by lcrownover** [Azure/azure-sdk-for-rust#1588]
I'm trying to do something very simple: Use use the Azure CLI to print out an access token.

In trying to get _something_ going, I'm following the official example on the [azure_identity docs on crates.io](https://crates.io/crates/azure_identity), it shows:

```rust
let credential = DefaultAzureCredential::default();
let response = credential
    .get_token(&["https://management.azure.com/.default"])
    .await?;
```

`credential` is an instance of `DefaultAzureCredential`, which does not have a \***public**\* `.get_token()` method. Using `default()`, the resulting object looks like:

```
DefaultAzureCredential { sources: [Environment(EnvironmentCredential { http_client: Client { accepts: Accepts, proxies: [Proxy(System({}), None)], referer: true, default_headers: {"accept": "*/*"} }, options: TokenCredentialOptions { authority_host: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("login.microsoftonline.com")), port: None, path: "/", query: None, fragment: None } }, cache: TokenCache(RwLock { value: {} }) }), ManagedIdentity(ImdsManagedIdentityCredential { http_client: Client { accepts: Accepts, proxies: [Proxy(System({}), None)], referer: true, default_headers: {"accept": "*/*"} }, object_id: None, client_id: None, msi_res_id: None, cache: TokenCache(RwLock { value: {} }) }), AzureCli(AzureCliCredential { cache: TokenCache(RwLock { value: {} }) })], cache: TokenCache(RwLock { value: {} }) }
```

So I then look at the [README.md for the azure_identity package in this repository](https://github.com/Azure/azure-sdk-for-rust/blob/main/sdk/identity/README.md) and it instead shows:

```rust
let credential = azure_identity::create_credential()?;
```

The only `create_credential()` method I see is [in the token_credentials::specific_azure_credential file](https://github.com/Azure/azure-sdk-for-rust/blob/f473bc948cd4ae41dfd5dc3293498c8952d8dee2/sdk/identity/src/token_credentials/specific_azure_credential.rs#L33). This example doesn't work either.

So what is the correct way to get a token? There are plenty of `get_token()` and `get_access_token()` methods all over, but they're all private.

**Comment by demoray** [comment]
`get_token` is exposed via the TokenCredential trait, which the azure-identity credential providers implement.

Import `azure_core::auth::TokenCredential` and you'll have access to get_token.

**Comment by lcrownover** [comment]
That's interesting. The following code works:

```rust
    let credential = DefaultAzureCredential::default();
    let token = credential
        .get_token(&["https://management.azure.com/.default"])
        .await?;
    println!("token: {:?}", token.token.secret());
```

But after creating the `credential`, rust-analyzer doesn't seem to know about any of that functionality:

<img width="542" alt="image" src="https://github.com/Azure/azure-sdk-for-rust/assets/15133041/697de3d2-b202-46be-8a16-f34296a4c74b">

"get_token" listed in completions is just sourced from existing text in the buffer.

Same with VS Code:

<img width="545" alt="image" src="https://github.com/Azure/azure-sdk-for-rust/assets/15133041/cbc0e73c-33c5-401d-865e-06ba7c983a69">

I don't have buffer text completion configured in VS Code so there's no completions available at all.

I don't know much about how rust-analyzer works, but can you reproduce this?

**Comment by demoray** [comment]
I'm not familiar with using that portion of VS Code + rust-analyzer.  With VS Code + rust-analyzer, I can confirm it is able to find the implementation using this example:

```rust
use azure_identity::DefaultAzureCredential;
use azure_core::auth::TokenCredential;

fn main() {
    let credential = DefaultAzureCredential::default();
    let _ = credential.get_token(&[".default"]);
}
```

![image](https://github.com/Azure/azure-sdk-for-rust/assets/47821/49c24bf6-e74f-4172-8241-2fc0ced2319c)

As such, addressing issues in rust-analyzer+vscode is out of scope for the Azure SDK for Rust.

**Comment by lcrownover** [comment]
Fair enough, if your environment shows correct autocompletions then I suspect something is off on my end.

Thanks for the help!
