### ISSUE TITLE
missing services due to invalid readme formatting

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-sdk-for-rust#159]
Several services are missing because of incorrect formatting in the readme files. The `### Tag:`s are supposed to be under `## Configuration` in the readme files. Unfortunately, several readme files have put them under `## Suppression` or  `## Composite packages`. To fix the readme files, another `###` should be used for those headings when they are underneath  `## Configuration`. I've added pull requests to fix the readme files. We could also loosen up our parser and support `### Tag:`s anywhere in the file even in incorrect hierarchies.

### data-plane
- [x] machinelearningservices https://github.com/Azure/azure-rest-api-specs/pull/12593
- [x] mixedreality https://github.com/Azure/azure-rest-api-specs/pull/12599
- [x] iotcentral https://github.com/Azure/azure-rest-api-specs/pull/12574

### resource-management
- [x] trafficmanager https://github.com/Azure/azure-rest-api-specs/pull/12597
- [x] sql https://github.com/Azure/azure-rest-api-specs/pull/12596
- [x] security https://github.com/Azure/azure-rest-api-specs/pull/12595
- [x] PolicyInsights https://github.com/Azure/azure-rest-api-specs/pull/12594
- [x] HDInsight https://github.com/Azure/azure-rest-api-specs/pull/12592
- [x] eventhub https://github.com/Azure/azure-rest-api-specs/pull/12591
- [x] Authorization https://github.com/Azure/azure-rest-api-specs/pull/12590
- [x] AlertsManagement https://github.com/Azure/azure-rest-api-specs/pull/12588

**Comment by ctaggart** [comment]
My last PR finally got merged yesterday.

**Comment by rylev** [comment]
Can we close this then?

**Comment by ctaggart** [comment]
Recently also fixed adp https://github.com/Azure/azure-rest-api-specs/pull/13850 and opened a pull request for subscription https://github.com/Azure/azure-rest-api-specs/pull/14001.
