### ISSUE TITLE
Un`Send`able futures returned by service endpoints

### ISSUE THREAD

**Issue by uint** [Azure/azure-sdk-for-rust#160]
The [`TokenCredential` trait](https://github.com/Azure/azure-sdk-for-rust/blob/master/sdk/core/src/lib.rs#L108) isn't bound by `Send` or `Sync`. As a result, `dyn TokenCredential` isn't `Send`. Since the `OperationConfig` in each (or some?) services contains `Box<dyn TokenCredential>`, the `OperationConfig` itself isn't `Send`. And so, futures returned by functions that require `OperationConfig` tend to not be `Send`able (as far as I understand, anyway). This seems to cause problems when using a multi-threaded runtime.

Would it be reasonable to add a `Send + Sync` bind to `TokenCredential`? I tried it locally and it seems to solve my problems. I'm happy to give you a PR.

**Comment by ctaggart** [comment]
Hi @uint, yes a PR that shows what needs to change for one service would be great! I can adjust the code in autorust accordingly.

**Comment by uint** [comment]
There! It's actually just a small change to core, so there's probably no need for the codegen.
