### ISSUE TITLE
device identity creation with x509 certificates

### ISSUE THREAD

**Issue by PradeepKiruvale** [Azure/azure-sdk-for-rust#163]
Hi All,

I had a look at the IoTHub examples. I see the example of device identity creation with the SAS. Does this support the device identity creation with x509 certificates as well?

Please let me know where can I find some examples, if any.

Also does this crate support the device provisioning using the DPS?

Thanks & Regards,
Pradeep

**Comment by corollaries** [comment]
Hi,

Yes, I haven't gotten around to creating examples of x509 certificates but the following should work:
```rust
    let device = service_client
        .create_device_identity()
        .device_id(device_id)
        .authentication_using_x509(
            "first thumbprint",
            "second thumbprint",
        )
        .status(Status::Enabled)
        .execute()
        .await?;
```

However, please note that the API of the `iothub` crate (and specifically identities as well) will get several breaking changes soon which will result in the example I just provided not working any longer. 

Device provisioning using DPS is not supported as of this moment.

**Comment by PradeepKiruvale** [comment]
Great, thanks for the clarifications. I am looking for the DPS based features. Hope they will be supported soon

**Comment by rylev** [comment]
@corollaries you worked on the `create_device_identity` operation in #158. Do you remember what the status is as it relates to this issue?

**Comment by corollaries** [comment]
@rylev I think this can be closed. It's implemented, some better examples would possibly be helpful at a certain point which I would be able to do in the near future.

**Comment by rylev** [comment]
Thanks!
