### ISSUE TITLE
Putting a block blob to a BlobBlockStorage type storage account errors out with unsupported header

### ISSUE THREAD

**Issue by maxburke** [Azure/azure-sdk-for-rust#165]
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: 
AzureError(UnexpectedHTTPResult(UnexpectedHTTPResult { expected: [201], received: 400, body: "\u{feff}<?xml 
version=\"1.0\" encoding=\"utf-8\"?><Error><Code>UnsupportedHeader</Code><Message>One of the HTTP headers 
specified in the request is not supported.\nRequestId:91cf4122-401e-00aa-2b78-f63a30000000\nTime:2021-01-
29T19:54:42.1130255Z</Message><HeaderName>x-ms-access-tier</HeaderName></Error>" }))', src/import/index_builder.rs:311:50
```

It appears these accounts do not support the Access Tier header; this header should probably be optional (or unsettable).

**Comment by MindFlavor** [comment]
Hi @maxburke,
Can you please share more details (or a repro)? I'm unable to reproduce the issue.

I've tried executing this example: [put_block_blob_00.rs](https://github.com/Azure/azure-sdk-for-rust/blob/master/sdk/storage/examples/put_block_blob_00.rs) on my storage account: the example creates a block blob, adds two uncommitted blocks and the commits them. 
It worked with both Hot and Cool access tiers.

**Comment by maxburke** [comment]
Hi!

So, the storage account kind is `BlockBlobStorage`. We created this type of account with the following Terraform resource definition:

```
resource "azurerm_storage_account" "sa_westus2_infra_blockblob" {
  name                     = "ultestblockblob"
  resource_group_name      = azurerm_resource_group.grp_data_storage.name
  location                 = "West US 2"
  account_kind             = "BlockBlobStorage"
  account_tier             = "Premium"
  account_replication_type = "LRS"
  enable_https_traffic_only = true
  min_tls_version   = "TLS1_2"
}
```

Notice the account kind is "BlockBlobStorage", not "Storage" or "StorageV2". 

In the storage browser there is no way to change the tier of the objects, as they do not have a tier type:

![image](https://user-images.githubusercontent.com/253368/106492843-419db700-646d-11eb-9e75-b995aa6bd5e5.png)

When using put_block_blob on this type of storage account we get the error above.

**Comment by MindFlavor** [comment]
Yes, my bad, it makes sense. Thank you for clarifying it to me 👍 !

Making the access tier optional is relatively easy but I'm not sure it's the right solution. 
As you rightly pointed out, the entire concept of tiering is absent in high performance storage accounts so it does not make sense to support it. 

@rylev: do you think this kind of distinction warrants a specific client or we can just make do with the simplification?

**Comment by maxburke** [comment]
Any more thoughts on this?

**Comment by rylev** [comment]
Having an entirely separate client seems like a bit of overkill just for this one particular distinction. I'm fine with trying to simple route of just making it optional, but if someone wants to try the separate client, we can also see how it looks.

**Comment by MindFlavor** [comment]
I agree with you, the separate client is too much work for this first release. We can always change it later if it ends up being not ergonomic to use.
