### ISSUE TITLE
storage_accounts::list_service_sas failed with 'HTTP Error 411. The request must be chunked or have a content length.'

### ISSUE THREAD

**Issue by karataliu** [Azure/azure-sdk-for-rust#166]
storage_accounts::list_service_sas cannot work after #157 

```
<BODY><h2>Length Required</h2>\r\n<hr><p>HTTP Error 411. The request must be chunked or have a content length.</p>\r\n</BODY>
```

Seems similar to https://github.com/seanmonstar/reqwest/issues/838

It is now sending an empty body, but doesn't send content-length
```
let req_body = bytes::Bytes::from_static(azure_core::EMPTY_BODY);
```

cc @ctaggart

**Comment by ctaggart** [comment]
Sorry about that @karataliu. I'll have a look.

**Comment by karataliu** [comment]
It's working well now. Thank you.

**Comment by ctaggart** [comment]
Great to hear! Thanks for letting us know.
