### ISSUE TITLE
Some Azure endpoints have some trouble handling duplicated slashes ('//') in the endpoint's URL

### ISSUE THREAD

**Issue by andras-pinter** [Azure/azure-sdk-for-rust#1664]
Hey!

I encountered an issue when I wanted to query an AppConfiguration endpoint with the `azure_svc_appconfiguration` crate.
The generated URL contained a duplicate slash, which confused Azure's AppConfiguration endpoint.

Example:
My base URL: `https://some-app-conf.azconfig.io/`
The generated request's URL: `https://some-app-conf.azconfig.io//keys?api-version=2023-10-01`
This resulted in a 404 response. However, if I remove the duplicated slash from the Request, like:
`https://some-app-conf.azconfig.io/keys?api-version=2023-10-01`
everything just works as expected.

This could be an issue for other Azure REST endpoints as well.
I think some Azure endpoints experiencing some troubles dealing with duplicated slashes in the URL.

I tried with the latest version (0.20.0).

I made a draft Pull Request to solve this problem: https://github.com/Azure/azure-sdk-for-rust/pull/1663

**Comment by kingofthehill444** [comment]
Please see this [comment on the PR](https://github.com/Azure/azure-sdk-for-rust/pull/1663#issuecomment-2248594904) as I am also facing this issue!
