### ISSUE TITLE
AKS Support

### ISSUE THREAD

**Issue by jmintb** [Azure/azure-sdk-for-rust#167]
I would like to work on [AKS](https://azure.microsoft.com/en-us/services/kubernetes-service/) support.
As fare as I can tell there are no issues or pull-requests related to AKS at the moment, so I assume I won't be duplicating effort.
Would anyone object to me looking into this? :)

Edit:
I was referring to the sdk directory. I had overlooked the services directory, it seems to support interacting with AKS.
This issue doesn't really make sense.

**Comment by karataliu** [comment]
Yes `services/mgmt` supports service control planes as long as the service swagger is present.

**Comment by XavierGeerinck** [comment]
I think this might need to be re-opened. https://github.com/Azure/azure-rest-api-specs/tree/main/specification/containerservice/resource-manager/Microsoft.ContainerService/aks is present, but it's not in the Rust SDK
