### ISSUE TITLE
long running operations

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-sdk-for-rust#174]
These are service operations marked  with `x-ms-long-running-operation`. The are polled. I think we can turn it into a stream.

See links in  https://github.com/ctaggart/azure-rest-api-specs/pull/7

Probably use a stream similar to:
- https://github.com/Azure/azure-sdk-for-rust/blob/master/sdk/identity/src/device_code_flow/mod.rs

**Comment by ctaggart** [comment]
The Java SDK now has some docs on long-running operations
https://docs.microsoft.com/en-us/azure/developer/java/sdk/lro

**Comment by cataggar** [comment]
Azure SDK Core Library for C++
> Polling long-running operations (LROs), via Operation<T>.
https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/core/azure-core/README.md#long-running-operations

Azure SDK for Go
https://github.com/Azure/azure-sdk-for-go/search?q=long-running
https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md#long-running-operations

**Comment by yoshuawuyts** [comment]
>  I think we can turn it into a stream.

I think this intuition is right, and I think that's what we should attempt to implement that.

**Comment by cataggar** [comment]
Guidance for LROs was added in September here:
https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#long-running-operations--jobs

**Comment by AdamGlass** [comment]
The storage account create() (LRO example) takes its parameters and returns a request builder that implements into_future() which can be invoked directly or through await.  list()'s RequestBuilder has a into_stream().   Should create() 's RequestBuilder implement both? eg. a simple future for 'acceptance' and a stream of progress objects that allow for later failure?  Or should the create() future only signal for completion/failure of the whole operation and hide the acceptance/intermediate states? 

eg. do we need a mechanism for  all 3 - simple acceptance, progress tracking, and full completion/failure?

What's the requirement for backward compatibility?

(i'm sure i lack some context)

**Comment by cataggar** [comment]
There is some new documentation here:
https://azure.github.io/typespec-azure/docs/howtos/Azure%20Core/long-running-operations

**Comment by AdamGlass** [comment]
I'm on vacation but my skim of that material suggests that they're really emphasizing 'terminal' status eg. succeed/failed/canceled rather than any other intermediate progress.  That makes sense to me as how often do you really care about any other intermediate states.

**Comment by cataggar** [comment]
#1370 got us started. More specific issue can be created as they arise.
