### ISSUE TITLE
How do I access BlobPrefix when listing blobs?

### ISSUE THREAD

**Issue by shepmaster** [Azure/azure-sdk-for-rust#175]
If I'm reading the [online docs](https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs#response-body) correctly, the blob listing API (as exposed by `azure_storage::blob::container::requests::ListBlobsBuilder`) should have a `BlobPrefix` element:

```xml
<EnumerationResults ServiceEndpoint="http://myaccount.blob.core.windows.net/"  ContainerName="mycontainer">  
  <!--...-->
  <Blobs>  
    <Blob><!--...--></Blob>  
    <BlobPrefix>  
      <Name>blob-prefix</Name>  
    </BlobPrefix>  
  </Blobs>  
  <NextMarker />  
</EnumerationResults>  
```

However, I don't see a way of getting that data back:

```rust
pub struct ListBlobsResponse {
    pub incomplete_vector: IncompleteVector<Blob>,
    pub request_id: RequestId,
    pub date: DateTime<Utc>,
}
```

It seems like it would need to be something like `IncompleteVector<(Blob, BlobPrefix)>` (I'm not sure exactly when it is present with respect to `Blob`, however).

---

Specifically, I'm looking for something like `CommonPrefixes` from the [parallel S3 API method](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html#API_ListObjectsV2_ResponseSyntax), so hopefully this piece of data is the appropriate thing.

**Comment by MindFlavor** [comment]
Yes you are right, the response does not yet parse all the possible fields (in fact right now it only extracts the blob list and the `NextMarker` for pagination).
We should definitely add the virtual hierarchy fields in the response 👍 .

**Comment by MindFlavor** [comment]
Hi @shepmaster, 
I have a PR that should expose the information you want. 

I've also added an example (`list_blobs_01`) that shows how to use the delimiter and prefix to navigate the virtual hierarchy. 

In a nutshell, it creates some blobs with a structure similar to this:

```
firstfolder
  | secondfolder
    | blob 1
    | blob 2  
  | thirdfolder
    | blob 1
    | blob 2
  | blob1
  | blob2
blob_at_root_01
blob_at_root_02
```

And then calls `list_blobs` passing `\` as delimiter and changing the prefix to get only the subentries in that folder. 

I hope it's what you were looking for (I admit I was lazy and didn't check what `CommonPrefixes` in S3 do 🤷‍♂️ ). If not please let us know!

**Comment by MindFlavor** [comment]
@shepmaster can we close this?

**Comment by shepmaster** [comment]
Yes, I believe so. Thanks!
