### ISSUE TITLE
crates.io links are outdated

### ISSUE THREAD

**Issue by Seppel3210** [Azure/azure-sdk-for-rust#181]
"Homepage" and "Repository" link to the old archived repository.
"Documentation" is 404.

**Comment by MindFlavor** [comment]
Hello @Seppel3210,
the crates are not published in crates.io yet (see #120 for updates). An unfortunate consequence of that is the documentation in docs.rs are not available (they are built from the published crates). 

As for the Homepage and Repository they should point to the new repo but I am unable to find the old reference anywhere. Can you point me to the wrong reference?

**Comment by ctaggart** [comment]
We'll leave #120 open.
