### ISSUE TITLE
Managing UAMIs

### ISSUE THREAD

**Issue by ianstanton** [Azure/azure-sdk-for-rust#1827]
Hello! I am hoping to find a way to manage User Assigned Managed Identities (UAMIs), Role Assignments, etc in a Rust application. I'm searching through all of the crates in this repo, and I'm not finding anything yet. 

Here's what I'd like to be able to do:
- Create / update / delete UAMIs
- Crete / update / delete Role Assignments
- Add a Federated Credential to a  UAMI for a given kubernetes ServiceAccount

I'd like to avoid making API calls via HTTP client in this application. Basically, I'd like to be able to do [things like this](https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/how-manage-user-assigned-managed-identities?pivots=identity-mi-methods-rest) via some crate. Is this possible? Thanks in advance :)

**Comment by heaths** [comment]
ARM crates are not yet on our schedule for the new work we're doing in the `feature/track2` crate. We do have some unofficial, unsupported ARM crates in `main`, however, that should work for you: <https://github.com/Azure/azure-sdk-for-rust/tree/main/services/mgmt/msi>. If that doesn't contain the endpoint support you require, please be more specific about which Azure service you need support for. Note that crates under the `svc` directory in the `main` branch match up with the REST API specs directory in <https://github.com/Azure/azure-rest-api-specs>.

/cc @ronniegeraghty

**Comment by ianstanton** [comment]
Thanks for your reply! It looks like something like this might work:
```
  let client = azure_mgmt_msi::Client::builder(credential).build()?;

  let uami_created = client
      .user_assigned_identities_client()
      .create_or_update(
          subscription_id,
          resource_group_name,
          resource_name,
          parameters,
      )
      .await?;
```
I'll give this a try
