### ISSUE TITLE
Make the crates buildable with only rustls

### ISSUE THREAD

**Issue by purkhusid** [Azure/azure-sdk-for-rust#191]
It would be very nice if all the crates could be built without native TLS. This could be done either via a feature flag or just make sure that all dependencies are configured to use rustls.

E.g. the `azure_core` package currently has `reqwest` as a dependency but is not configured to use rustls.

**Comment by MindFlavor** [comment]
It's a good idea.  👍 
We'll have to delay this until we have completed the crates rewrite and the core crate reorg though. 

Let's keep this open to track it.

**Comment by cataggar** [comment]
`rustls` has been supported for a while now. 

https://github.com/Azure/azure-sdk-for-rust/blob/06f56a422c6c3ef3ff0332525d991cc550df4a11/sdk/core/Cargo.toml#L51

**Comment by dhduvall** [comment]
Is there a way to build `azure_security_keyvault` with only `rustls`? I can't seem to make it happen.

**Comment by bmc-msft** [comment]
Yes, use it with `default-features = false` and the feature `enable_reqwest_rustls`

**Comment by dhduvall** [comment]
I see; it just hasn't been released yet. Thanks. (Turns out `rustls` still has a C dependency that doesn't build out of the box for me, so I went back to `openssl`, but I'll see if I can get that working once this makes it to crates.io.)

**Comment by caseykneale** [comment]
> Yes, use it with `default-features = false` and the feature `enable_reqwest_rustls`

Where are the crate features documented? Had to find this via searching github closed issues
