### ISSUE TITLE
Generating new models.rs and operations.rs for Azure Policy definitions

### ISSUE THREAD

**Issue by mdtro** [Azure/azure-sdk-for-rust#208]
Hi, I'm interested in contributing updated models.rs and operations.rs for the newer API versions related to Azure Policy, but would need some guidance on how best to introduce this. I've been able to successfully run AutoRust to generate the new stubs and got them working in my code albeit a bit messy with having to copy/paste and pull in the necessary dependencies like `OperationConfig` ([here](https://github.com/Azure/azure-sdk-for-rust/blob/master/services/mgmt/resources/src/lib.rs)).

Specifically, I'm looking at these specifications: https://github.com/Azure/azure-rest-api-specs/tree/master/specification/resources/resource-manager/Microsoft.Authorization/stable/2020-09-01

The latest this SDK has available is the [2019-09 version ](https://github.com/Azure/azure-sdk-for-rust/tree/master/services/mgmt/resources/src/package_policy_2019_09).

I see there are several PRs in flight that will be shuffling a lot around. Should I wait for those to be merged before beginning? 

Thank you for the great work with this SDK! I'm excited to see it maturing.

**Comment by rylev** [comment]
Hey @mdtro 👋 - As you've noticed things are in a bit of a state of flux as we're moving to an architecture that lines up with other SDKs in other languages. @ctaggart has been working on the code generation part of this project, and he can help you decide when and how to get these changes in.

**Comment by ctaggart** [comment]
Thanks for the encouragement. #211 fixes this.

**Comment by mdtro** [comment]
Ah wow! Thank you!
