### ISSUE TITLE
Azure storage queue - Delete Message

### ISSUE THREAD

**Issue by MindFlavor** [Azure/azure-sdk-for-rust#21]
As per [https://docs.microsoft.com/en-us/rest/api/storageservices/delete-message2](https://docs.microsoft.com/en-us/rest/api/storageservices/delete-message2).

**Comment by Alexei-B** [comment]
I need to be able to delete queue messages, so I've created a PR to implement a delete message request in the queue name service. I tried my best to follow the existing pattern for the code, so hopefully it fits in nicely with how you'd expect it to be implemented.
