### ISSUE TITLE
A way to see the error body

### ISSUE THREAD

**Issue by omid** [Azure/azure-sdk-for-rust#212]
Seems like there is no way to know the error body: https://github.com/Azure/azure-sdk-for-rust/blob/94fde5d4ee03d5836a0c32191fdb1444e92b1b73/sdk/core/src/errors.rs#L67

If I'm wrong and I can have access to the body, I would be glad if you lead me to that.

**Comment by ctaggart** [comment]
This is fixed in #251.

**Comment by omid** [comment]
A PR with (+252,009 −1,276,669) changed lines :D 👍🏼 
Thanks, man. Hope to see a release (stable/beta/alpha/...) soon.

**Comment by ctaggart** [comment]
Me too. This bug was fixed on this [single line](https://github.com/Azure/azure-sdk-for-rust/pull/251/files#diff-1a60b556d3b6e26cd2792c5f6c0361be8b04a732fc8602888dd8695d270b2c4dR85) where I added `body`:
```
"Unexpected HTTP result (expected: {:?}, received: {:?}, body: {:?})",
```
