### ISSUE TITLE
handle x-ms-pageable in services codegen

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-sdk-for-rust#218]
https://github.com/Azure/autorest/blob/master/docs/extensions/readme.md#x-ms-pageable

**Comment by ctaggart** [comment]
See #83 & #84 and search `continuation_token` & `continue_execution`.

**Comment by cataggar** [comment]
The work for azure_core is in https://github.com/Azure/azure-sdk-for-rust/issues/341.

**Comment by cataggar** [comment]
Fixed by #742.
