### ISSUE TITLE
Automatically box use of struct as a field in that struct

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-sdk-for-rust#225]
As hinted in #84, we should (when possible) automatically box types when they are used as the type of their own field. 

For example, it should be possible to detect the following situation:

```rust
struct Foo {
   bar: Bar,
   foo: Foo
}
```

and turn it into:

```rust
struct Foo {
   bar: Bar,
   foo: Box<Foo>
}
```

**Comment by cataggar** [comment]
Fixed by #1385.
