### ISSUE TITLE
Question:  Implementing HttpClient for other types

### ISSUE THREAD

**Issue by wokket** [Azure/azure-sdk-for-rust#252]
Hey guys, self-confessed rust noob here trying to convert an existing .net core service over to rust as a self-learning exercise.  I'm building an `actix-web` service that talks to Cosmos, but have hit a roadblock around the abstracted HttpClient notion.  

I can't execute a `reqwest` call inside `actix` (due to a lack of tokio runtime) so figured I'd just implement `azure_core::HttpClient` for the baked in `actix_web::client::Client`  http client that I know works, but get smacked with the error 'only traits defined in the current crate can be implemented for arbitrary types' because both the trait and concrete type are external to my crate.

Is the expectation that this library will provide impls for the common? (all?) http clients, or should I be wrapping the actix client in a custom struct solely for the purposes of providing an impl, or something else I haven't thought about yet?

Cheers

**Comment by rylev** [comment]
Hi! This is a common issue in Rust - one work around is creating a new type that wraps the 3rd party type. For example:

```rust
struct ActixClient(actix_web::client::Client);
```

You can then implement `Deref` for it which would allow you to call any methods on actix's `Client` type through your wrapper type. Finally, this means you can implement the `HttpClient` trait for your type. 

I hope this helps!

**Comment by wokket** [comment]
Cool, thanks for letting me know that is the intent, and for the pointer to `Deref` 👍
