### ISSUE TITLE
UnsupportedHeader for put_block_blob operation

### ISSUE THREAD

**Issue by ArtemTrofimushkin** [Azure/azure-sdk-for-rust#259]
Greetings, I am trying to use this SDK with a storage account (kind: BlockBlobStorage, performance: Premium). 
When I try to put block blob (for example, with the [following code sample](https://github.com/Azure/azure-sdk-for-rust/blob/master/sdk/storage/examples/put_block_blob_00.rs)), I get this error:

```
Error: UnexpectedHTTPResult(UnexpectedHTTPResult { expected: [201], received: 400, body: "\u{feff}<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>UnsupportedHeader</Code><Message>One of the HTTP headers specified in the request is not supported.\nRequestId:c8438c84-d01e-0036-6cb3-50e8b1000000\nTime:2021-05-24T15:40:19.4944666Z</Message><HeaderName>x-ms-access-tier</HeaderName></Error>" })
```

I think this occurs because of the default value for the access_tier property of [PutBlockBlobBuilder](https://github.com/Azure/azure-sdk-for-rust/blob/master/sdk/storage/src/blob/blob/requests/put_block_blob_builder.rs#L36) and [PutBlockListBuilder](https://github.com/Azure/azure-sdk-for-rust/blob/master/sdk/storage/src/blob/blob/requests/put_block_list_builder.rs#L35)

According to the official [docs](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-storage-tiers#storage-accounts-that-support-tiering), an access tier can be specified on a storage account level, thus, it not allowed to specify it on blob level. That's why validation error occurs

When I try to change the specified property value to `None`, mentioned code sample passes without error
Can I open pull-request for this?

**Comment by ctaggart** [comment]
In #172, this was set to default to default to `access_tier: Some(AccessTier::Hot),` instead of None. I'm not sure why.  cc @maxburke
