### ISSUE TITLE
GetBlobResponse produces error: CoreError(HeaderNotFound(\\\"content-range\\\"))\")

### ISSUE THREAD

**Issue by jefshe** [Azure/azure-sdk-for-rust#267]
I received this error while upgrading to the latest version of master today.

I think it is caused by https://github.com/Azure/azure-sdk-for-rust/blob/master/sdk/storage/src/blob/blob/responses/get_blob_response.rs#L33

Where we are always expecting this header to be present but I think this is only true if the request has requested a subset of the blob

**Comment by ctaggart** [comment]
Probably related to https://github.com/Azure/azure-sdk-for-rust/pull/253

**Comment by jefshe** [comment]
I've attempted my own fix at https://github.com/Azure/azure-sdk-for-rust/pull/268
