### ISSUE TITLE
check response status code for credential calls

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-sdk-for-rust#270]
Adding per https://github.com/Azure/azure-sdk-for-rust/pull/266#discussion_r641674512. A couple of places in a azure_identity use reqwest directly. They issue a HTTP request, but do not check for a successful error code. Certain errors will have an error response that can be deserialized. In most cases, I'm not sure it is worth trying to deserialize an error message.

sdk\identity\src\device_code_flow\mod.rs
sdk\identity\src\client_credentials_flow\mod.rs
``` rust
    client
        .post(url)
        .header("ContentType", "Application / WwwFormUrlEncoded")
        .body(encoded)
        .send()
        .await?
        .text()
        .await
        .map(|s| -> Result<LoginResponse, Error> {
            Ok(serde_json::from_str::<LoginResponse>(&s)?)
        })?
    // TODO The HTTP status code should be checked to deserialize an error response.
    // serde_json::from_str::<crate::errors::ErrorResponse>(&s).map(Error::ErrorResponse)
```

**Comment by cataggar** [comment]
This was fixed in #544.
