### ISSUE TITLE
remove test credentials

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-sdk-for-rust#280]
> This will get flagged, assuming this is an auth token, even if ephemeral or fake. Cognitive Search even have a public, read-only sample account that we shared creds to - on docs.microsoft.com even - and was flagged. We do have a system in place for azure-sdk-for-net and some other languages to deal with this, but we need to get the pipeline fully built up and used. Perhaps, for now, this will be okay - as long as it is not actual valid creds into our Azure sub (if so, it needs to be rotated immediately) - but I would add a TODO comment or even BUGBUG we can scan to find these - or open a tracking issue even.
https://github.com/Azure/azure-sdk-for-rust/pull/277#discussion_r643359743

**Comment by demoray** [comment]
@heaths the test credentials are in every SDK I've checked thus far. 

Searches for the account key in:
* [azure-sdk-for-net](https://github.com/search?q=repo%3AAzure%2Fazure-sdk-for-net%20Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq&type=code)
* [azure-sdk-for-go](https://github.com/search?q=repo%3AAzure%2Fazure-sdk-for-go%20Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq&type=code)
* [azure-sdk-for-python](https://github.com/search?q=repo%3AAzure%2Fazure-sdk-for-python%20Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq&type=code)

This is a well-known and public account key.   Can we revisit the need for removing these, given every other SDK uses them?

Ref: https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio#well-known-storage-account-and-key

**Comment by heaths** [comment]
These have exceptions, which I think requires getting this repo into our standard engsys pipeline. Still, if there is some way to exempt them outside that policy, I think it's fine to leave as-is for now until we actually get flagged.

**Comment by demoray** [comment]
Ok.  Closing for now.  If we start getting alerts, we'll deal with the exception process then.
