### ISSUE TITLE
Figure out how to support streaming bodies for WASM target

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-rust#293]
In PR #288 the initial [check](https://github.com/Azure/azure-sdk-for-rust/pull/288/checks?check_run_id=2800339208) failed because `azure_core::TransportPolicy` does not implement `azure_core::Policy` for WASM. Previously this didn't matter because you'd hve to pass in a transport policy to `Pipeline::new()` and it was only defined as `Arc<dyn Policy>`; however, with the changes to be more consistent with other languages' SDK, azure_core now creates the `TransportPolicy`.

As part of #37 we do want to support WASM so we need to figure out the transport story. If/when reqwest supports WASM we could probably just remove `#[cfg(not(target_arch = "wasm32"))]` from sdk/core/src/policies/transport.rs; otherwise, we may need a WASM-specific transport to use the browser sandbox's network stack.

**Comment by ctaggart** [comment]
reqwest does support WASM. https://github.com/seanmonstar/reqwest

**Comment by heaths** [comment]
I guess we need to figure out why we have - or need to tighten up - the `cfg` condition above in various places. For example, we currently don't create an implementation of `HttpClient` for WASM but sounds like we could. We default to reqwest anyway (default feature).

**Comment by rylev** [comment]
The issue isn't around the usage of `reqwest` in general. The issue is that `reqwest` does not support streaming bodies in wasm. For instance, `reqwest::Body::wrap_stream` is not available in wasm. We need to figure out how we reconcile this. 

This is why it might be necessary to not use `reqwest` for wasm targets so that we can build in streaming support.

**Comment by johnbatty** [comment]
@rylev Looks like this `reqwest` PR might provide the required streaming body support?
https://github.com/seanmonstar/reqwest/pull/1576
