### ISSUE TITLE
Move request methods to pipeline

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-rust#294]
Rather than expose the underlying HttpClient, we should move request methods to the pipeline like in our other SDKs. We have helper methods for creating paged results, handling different error cases, etc. This also make it possible to abstract the pipeline from the protocol and handle, potentially, AMQP.

**Comment by yoshuawuyts** [comment]
Can we merge this issue into the https://github.com/Azure/azure-sdk-for-rust/issues/290 tracking issue?

**Comment by heaths** [comment]
That's all rather specific to Cosmos. This is specifically about refactoring the pipeline now so that we're not depending on reqwest's `Request` (or wherever it comes from - I forget off hand).

**Comment by cataggar** [comment]
I want to update the services to do this.

**Comment by cataggar** [comment]
Services have been updated in #527.

**Comment by cataggar** [comment]
Closing this in favor of #802.
