### ISSUE TITLE
Remove should_panic unit tests

### ISSUE THREAD

**Issue by rylev** [Azure/azure-sdk-for-rust#307]
Many unit tests are `should_panic` tests when they do not have to be.

It is preferable to not use `should_panic` as this requires string matching against the panic output which can be finicky and does not allow for any type safety. 

An example [here](https://github.com/Azure/azure-sdk-for-rust/blob/23b09b360013dc5a96db0b042ec94060c4f2acd7/sdk/core/src/request_options/ba512_range.rs#L105) shows that we are calling `unwrap` just to match against the panic message. Instead, we should `assert_eq!` against the error returned.

**Comment by u5surf** [comment]
@rylev 
Hi, I'm newbie as rust programmer. 
I would like to try this issue for making improvement my skills.

**Comment by rylev** [comment]
Feel free to submit a PR! Let me know if you need any help! 😊
