### ISSUE TITLE
Functional Testing in Azure with DevOps Pipelines

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-sdk-for-rust#316]
In the future, we may set up an Azure subscription for running functional tests. We'll use Azure DevOps Pipelines.

I investigated what it would take to get the cargo test results captured https://github.com/microsoft/vstest-docs/issues/252 and look like the solution may be to just use https://github.com/johnterickson/cargo2junit.

**Comment by karataliu** [comment]
x2junit is about rendering result.. Looks anyway the result cannot show directly in github, so suppose first step is to run and return green/red.
