### ISSUE TITLE
The error occurred on list_blobs method. CRC64 length 0 bytes instead of 8

### ISSUE THREAD

**Issue by glassonion1** [Azure/azure-sdk-for-rust#318]
The error occurred on list_blobs method. CRC64 length 0 bytes instead of 8

Code is below.

```rust
let http_client = azure_core::new_http_client();
let storage_account_client =
            StorageAccountClient::new_access_key(http_client, "{my_account_name}", "{my_account_key}");
let container_client = storage_account_client.as_container_client("my_container_name");

// Creates a container.
// this is ok.
let _res = container_client
     .create()
    .public_access(PublicAccess::None)
    .execute()
    .await
    .unwrap();
// Puts a blob data.
// this is ok.
let blob_client = container_client
    .as_container_client("my_container_name")
    .as_blob_client("blob1");
let _res = blob_client
    .put_block_blob("sample data...")
    .content_type("text/plain")
    .execute()
    .await
    .unwrap();

// panic
let res = container_client
    .list_blobs()
    .execute()
    .await
    .unwrap();
```

Error message is here.
```
thread 'blob::sample::test_blob' panicked at 'called `Result::unwrap()` on an `Err` value: XmlError(Custom { field: "CRC64 length 0 bytes instead of 8" })', sample/src/blob.rs:999:99
```

Do I need a CRC64 hash when putting blob data?
(No error occurs when executing the get method.)

**Comment by inpactnosakae** [comment]
I have the exact same problem.  It does not occur when the container is empty (I wish that was an option! =))

**Comment by arnodb** [comment]
I confirm, this happens with a regular Azure blob storage, and not with Azurite.

I haven't investigated but it could be that the storage returns an empty header instead of no header at all. One option could be to map a zero length header to `None`.

P.S. the `azurite_workaround` feature does not compile.

**Comment by inpactnosakae** [comment]
I think the problem is that azure will respond with a empty <Content-CRC64 />, (maybe azurite doesn't do that?)

Thenthe following should be deserialized to `None`, but becomes Some("") instead. 
```
BlobProperties {
    ...
    pub content_crc64: Option<ConsistencyCRC64>,  
    ...
```

**Comment by arnodb** [comment]
> respond with an empty `<Content-CRC64 />`

Yes, sorry, I talked about headers but I forgot that this API call returns XML.

That is harder to fix since the deserializer does not know about the `Option`.

I suppose the MD5 suffers from the same problem.

**Comment by MindFlavor** [comment]
Good analysis! The only thing that troubles me is that this bug slipped though our E2E tests. 🤦‍♂️

**Comment by arnodb** [comment]
I tried with a custom deserialization function, but it fails when the field is not present, so I guess the way to go is using the `serde_with` crate and implementing `FromStr` instead of `Deserialize` for `ConsistencyXxx` structs.

**Comment by MindFlavor** [comment]
> I tried with a custom deserialization function, but it fails when the field is not present, so I guess the way to go is using the `serde_with` crate and implementing `FromStr` instead of `Deserialize` for `ConsistencyXxx` structs.

Yes I've just hit your problem. It's another azurite idiosyncrasy 🤷‍♂️.

**Comment by arnodb** [comment]
By the way, I cannot find any reference to `Content-CRC64` in any public documentation I know. Especially not in https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs.

IMO, it should never be empty, but without documentation, it's hard to tell.

**Comment by ctaggart** [comment]
> I think the problem is that azure will respond with an empty <Content-CRC64 />, (maybe azurite doesn't do that?)

Can we please confirm if this is true by capturing a response? A unit test can be added for the deserialization.

**Comment by inpactnosakae** [comment]
I captured two very similar responses, one from azure and one from azurite:

Other than noting that `<Content-CRC64 >` really isn't included in the response from azure, I can't do much from here. I hope it helps someone because as the timestamps suggests it really took me nearly 2 hours to get fiddler to play nice. 

### Azure:
```
HTTP/1.1 200 OK
Content-Type: application/xml
Vary: Origin
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: e4466c96-a01e-000b-1a55-6ecc12000000
x-ms-client-request-id: 3617cf26-73f8-4aef-b763-85e437eaadb3
x-ms-version: 2020-04-08
Date: Thu, 01 Jul 2021 08:47:17 GMT
Connection: close
Content-Length: 850

<?xml version="1.0" encoding="utf-8"?><EnumerationResults ServiceEndpoint="https://myaccountname.blob.core.windows.net/" ContainerName="images"><MaxResults>1000</MaxResults><Delimiter>/</Delimiter><Blobs><Blob><Name>sample.png</Name><Properties><Creation-Time>Wed, 02 Jun 2021 06:58:37 GMT</Creation-Time><Last-Modified>Wed, 02 Jun 2021 06:58:37 GMT</Last-Modified><Etag>0x8D92593D8B7C1DF</Etag><Content-Length>9051</Content-Length><Content-Type>image/png</Content-Type><Content-Encoding /><Content-Language /><Content-CRC64 /><Content-MD5>BRM9PUBaksjQUG7YHqLJwA==</Content-MD5><Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>true</ServerEncrypted></Properties><Metadata /><OrMetadata /></Blob></Blobs><NextMarker /></EnumerationResults>
```

### Azurite: 
```
HTTP/1.1 200 OK
Server: Azurite-Blob/3.13.1
content-type: application/xml
x-ms-client-request-id: a3ecb970-7ad8-4c2a-a795-823d090a7a9d
x-ms-request-id: fe9f51d4-19be-4fd9-b029-266dcbbea427
x-ms-version: 2020-08-04
date: Thu, 01 Jul 2021 10:13:17 GMT
Connection: close
Transfer-Encoding: chunked

3d3
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><EnumerationResults ServiceEndpoint="http://192.168.1.163:10000/devstoreaccount1" ContainerName="images"><Prefix/><Marker/><MaxResults>1000</MaxResults><Delimiter>/</Delimiter><Blobs><Blob><Name>sample.png</Name><Properties><Creation-Time>Thu, 01 Jul 2021 10:12:46 GMT</Creation-Time><Last-Modified>Thu, 01 Jul 2021 10:12:46 GMT</Last-Modified><Etag>0x1FB58C8B2F03370</Etag><Content-Length>50374</Content-Length><Content-Type>image/png</Content-Type><Content-Encoding/><Content-Language/><Content-MD5>YF7texLZZcGCTT3+gaFWSQ==</Content-MD5><Content-Disposition/><Cache-Control/><BlobType>BlockBlob</BlobType><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>true</ServerEncrypted><AccessTier>Hot</AccessTier><AccessTierInferred>true</AccessTierInferred><AccessTierChangeTime>Thu, 01 Jul 2021 10:12:46 GMT</AccessTierChangeTime></Properties></Blob></Blobs><NextMarker/></EnumerationResults>
0
```
Azurite started with `docker run -p 10000:10000 -p 10001:10001 mcr.microsoft.com/azure-storage/azurite`

Both requests triggered with azure storage explorer and captured with Fiddler 4 in windows 10

query parameters in request: ?delimiter=%2F&maxresults=1000&include=metadata&restype=container&comp=list
