### ISSUE TITLE
Auth Crate Name

### ISSUE THREAD

**Issue by rylev** [Azure/azure-sdk-for-rust#32]
Currently we have an auth_aad crate, but authorization may take many forms. Additionally, it seems that most of the other language SDKs don't use this naming convention for their auth packagaes. JS and C# use "authorization", but go uses "azidentity". Shall we converge on the JS and C# naming conventions?

**Comment by heaths** [comment]
Yes, please use JS and C# naming conventions. Go is ramping back up, but seems to have had a lull when other languages were standardizing a set of cross-cutting guidelines. But the create name would still be something like azure-identity. Classes (structs) typically take the form of *Credential, like `EnvironmentCredential`.

**Comment by ctaggart** [comment]
I think Python & C# provide good examples. In Python, you create a client with an implementation of `azure.core.credentials.TokenCredential`. An example is the [StorageManagementClient](https://docs.microsoft.com/en-us/python/api/azure-mgmt-storage/azure.mgmt.storage.storagemanagementclient?view=azure-python):
``` python
StorageManagementClient(credential, subscription_id, api_version=None, base_url=None, profile=<KnownProfiles.default: <azure.profiles.DefaultProfile object>>, **kwargs)
```

Here are a couple of examples from the [How to authenticate and authorize Python apps on Azure](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate?tabs=cmd) docs that show using `azure.identity` classes provided from https://pypi.org/project/azure-identity/ package:
``` python
from azure.identity import DefaultAzureCredential
credential = DefaultAzureCredential()

from azure.identity import AzureCliCredential
credential = AzureCliCredential()
```

C# has an [Azure.Core.TokenCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.core.tokencredential?view=azure-dotnet) abstract class in `Azure.Core` package with lot of implementation from the Azure.Identity package:
```
    Azure.Identity.AuthorizationCodeCredential
    Azure.Identity.AzureCliCredential
    Azure.Identity.ChainedTokenCredential
    Azure.Identity.ClientCertificateCredential
    Azure.Identity.ClientSecretCredential
    Azure.Identity.DefaultAzureCredential
    Azure.Identity.DeviceCodeCredential
    Azure.Identity.EnvironmentCredential
    Azure.Identity.InteractiveBrowserCredential
    Azure.Identity.ManagedIdentityCredential
    Azure.Identity.SharedTokenCacheCredential
    Azure.Identity.UsernamePasswordCredential
    Azure.Identity.VisualStudioCodeCredential
    Azure.Identity.VisualStudioCredential
```

So, we probably want to have similar implementations in an `azure_identity` crate.

**Comment by ctaggart** [comment]
A trait implementation must live in the same crate due to Rust's [trait coherence and the orphan rule](https://pingcap.com/blog/rust-huge-compilation-units#trait-coherence-and-the-orphan-rule), so I'm struggling to figure out the right design for the dependencies in my head.

**Comment by heaths** [comment]
Can't we just define a trait like `TokenCredential` in azure-core and each struct implement that create in azure-identity? I don't see how that's any different than built-in (well, std) traits.

**Comment by rylev** [comment]
Yes, since presumably almost all usage of an Azure SDK will require usage of the sdk-core crate, we can put it in there.

**Comment by ctaggart** [comment]
`sdk-core` seems like the right place to put the `TokenCredential` interface. However, [that crates dependencies](https://github.com/Azure/azure-sdk-for-rust/blob/3735b0d22f6629ba3f37dce59eef544b89d8249d/sdks/core/Cargo.toml#L15-L32) need to be trimmed. Or may be we should create a `azure-services-core` as well. I want to take a dependency on `TokenCredential` from the services.

**Comment by rylev** [comment]
I'd definitely love to take a look at the core crate and see how we can trim it down. Our old friend features might be able to help us out there.

**Comment by heaths** [comment]
The create should be "azure-core" to match all other languages' SDKs. We should be idiomatic and absolutely do what makes sense for Rust, but "module" names and, when appropriate, type/method names should be similar. See <https://azure.github.io/azure-sdk/general_introduction.html#consistent>. Is there some reason you don't like "azure-core"? The fact it's a client SDK should be obvious from other branding, such as crate descriptions, etc.

**Comment by ctaggart** [comment]
Yes, but with an underscore please instead of a dash. The use statement will  be `use azure_core::TokenCredential` whether the crate is named `azure-core` or `azure_core` and I prefer it to be consistent as well.

**Comment by rylev** [comment]
This can be closed as we have decided on azure-identity as the name.
