### ISSUE TITLE
Design a pageable solution for list operations

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-rust#341]
Like in our other languages' SDKs, we need a solution like [`Pageable<T>`](https://docs.microsoft.com/en-us/dotnet/api/azure.pageable-1) that can fetch more pages as needed. It should do so automatically while providing callers the ability to fetch page by page if they wish to.

Ideally needed for #218

**Comment by heaths** [comment]
How easily can that be extracted? In so our other SDKs, implementations really only need to provide a way to get the next link or page token, and there are helpers because there's a couple very common ways...by design: services are supposed to do it one way for new APIs anyway.

What you said there seems very involved. I assume want every implementation to have to write that code. Harder to maintain, not to mention harder to improve centrally if needs be.

**Comment by cataggar** [comment]
> Ideally we could expose some equivalent to Pageable that implements Stream (for the reasons outlined above)
❤️ 

All of the generated services that have operation responses with `x-ms-pageable` #218 would benefit from a shared abstraction. Here are what some other Azure SDKs do:

Azure SDK for CPP has a `Azure::PagedResponse<T>` that was added in May:
https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/core/azure-core/CHANGELOG.md

Azure SDK for JavaScript [has](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/core/core-client-paging-rest/test/paginate.spec.ts)
:
``` js
import { PagedAsyncIterableIterator } from "@azure/core-paging";
```
and a new experimental [Azure Rest Core Paging library](https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/core/core-client-paging-rest).

Azure SDK for Go has done it a [couple of ways](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/MIGRATION_GUIDE.md#pagination).

**Comment by heaths** [comment]
We might want some heuristic scanning as well. I can't say for sure for this Microsoft swagger extensions, but for some other extensions some services aren't always so consistent. That said, if other languages' generators use only this I see no reason to be different and try to support more.

**Comment by cataggar** [comment]
Basic guidelines here:
https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#98-pagination

azure_core::Pageable was added in #534.

**Comment by cataggar** [comment]
Closing, since `azure_core::Pageable` exists now.
