### ISSUE TITLE
[Discussion] Decide on tracing package/pattern

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-rust#344]
All our SDKs use some form of tracing for application-level tracing as well as distributed tracing. In the case of .NET, for example, we use an abstraction on `System.Diagnostics.Tracing` which [enables both](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Diagnostics.md).

It's been suggested to use the [`tracing`](https://crates.io/crates/tracing) crate, which seems to do the same thing, with supporting crates for [logging](https://github.com/tokio-rs/tracing/tree/master/tracing-log) and [OpenTelemetry](https://crates.io/crates/tracing-opentelemetry).

/cc @thomastaylor312

**Comment by thomastaylor312** [comment]
Yeah, the nice thing about `tracing` is consumers can hook up whatever they want into it. I haven't really looked into the distributed tracing part of it though

**Comment by MidasLamb** [comment]
I've used `tracing` with OpenTelemetry and hooked it up to Application insights, and it gives very nice results imho, very easy to use also: 
![image](https://user-images.githubusercontent.com/14802865/132174773-e2463b50-b607-458d-ac6f-1e2331239391.png)

**Comment by yoshuawuyts** [comment]
As per https://github.com/Azure/azure-sdk-for-rust/pull/504#issuecomment-965809346, we should also ensure that we add support for distributed tracing. The way I've seen this usually implemented is by getting a trace token from the current context, and passing a derived token to child HTTP requests, allowing an out-of-band trace aggregator link the requests together.

I don't know what the current state of distributed tracing is with Azure. I know of standards such as the [`TraceContext` header](https://docs.rs/http-types/2.12.0/http_types/trace/struct.TraceContext.html), but I don't know whether Azure supports them.

I'd love for us to get a better understanding how to generate, link, and collect distributed traces in the context of the SDK. @MidasLamb do you have any code available for the example you shared? It seems like it might make for a good starting point!

**Comment by MidasLamb** [comment]
@yoshuawuyts , I've got this to set up the screenshot I posted before:
```rust 
fn set_up_open_telemetry() {
    let tracer = opentelemetry_application_insights::new_pipeline(
        "<redacted>".to_owned(),
    )
    .with_client(reqwest::Client::new())
    .install_batch(opentelemetry::runtime::Tokio);

    let telemetry = tracing_opentelemetry::layer().with_tracer(tracer);

    // Some filtering to reduce the amount of nights
    let filter = tracing_subscriber::EnvFilter::from_default_env()
        .add_directive("handler=trace".parse().unwrap())
        .add_directive("backend=trace".parse().unwrap());

    let fmt_layer = tracing_subscriber::fmt::layer();

    let subscriber = Registry::default()
        .with(filter)
        .with(fmt_layer)
        .with(telemetry);

    tracing::subscriber::set_global_default(subscriber).unwrap();
}
```

for the rest, the code just contains the "normal" `#[tracing::instrument]` at various places.

However, everything currently runs in one process so I haven't had to do anything w.r.t. distributed tracing.

**Comment by heaths** [comment]
I can speak to general diagnostics and tracing for .NET (they are a bit intertwined), but do know that all our official language support work similarly: all HTTP calls (at least - other protocols may work a bit differently) are logged by Azure core (like our azure_core) and all headers, parameters, and body are sanitized unless explicitly enabled - some of which the client SDKs themselves do because they know what's safe. We also have a safe list that should be the same across all languages. Ideally, that's all that clients "have" to do: add any implementation-specific headers and/or query params that are safe to log/trace by default.
