### ISSUE TITLE
add "create file" operation to Azure Storage data_lake (using Pipeline architecture)

### ISSUE THREAD

**Issue by thovoll** [Azure/azure-sdk-for-rust#356]
https://docs.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/create

**Comment by thovoll** [comment]
Continuing #290

**Comment by thovoll** [comment]
@heaths @rylev I'd like to get some early input on how to model the Azure Storage data_lake operations for create/rename file/directory. These operation are all combined into a single REST API: https://docs.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/create

I'm thinking to expose these as 4 different operations in the Rust SDK. I'm also thinking to expose 'fail if the destination already exists' at a higher level of abstraction than 'use a conditional request with If-None-Match: "*"'.

Does this sound ok, and are there examples of other Azure Rust SDK crates that do this kind of thing already?

**Comment by thovoll** [comment]
Found that the .Net ADK for Azure Storage uses a generated Path REST client, and then layers a File client and Directory client on top, exposing higher level concepts such as 'rename'.

Is there an example of using an underlying generated REST client in the Rust SDK?

**Comment by rylev** [comment]
We don't currently generate code for our "hand rolled" SDKs (i.e., the ones in the sdk directory). If you take a look into the cosmos crate you'll notice that we build the clients up from scratch. Eventually we will want to try to generate the boilerplate rest calls from metadata, but for most services that's not possible because the metadata describing those APIs does not exist.

**Comment by thovoll** [comment]
Thanks. Any thoughts on the SDK design I proposed of the heavily overloaded "create path" REST call?

**Comment by thovoll** [comment]
It has become clear that we should match the .Net SDK as much as possible with respect to naming and structure, so I will eventually create a File and Directory client.

**Comment by thovoll** [comment]
PRs: #358, #451, #491
