### ISSUE TITLE
Create http client abstraction in core

### ISSUE THREAD

**Issue by rylev** [Azure/azure-sdk-for-rust#36]
Instead of relying on a hardcoded `reqwest` or `hyper` client, we should create an abstraction in the core crate that allows us to plug in different implementations if we want to. We need to decide how that plugability works. The choices I think we have are:
* A single concrete type with implementations decided on compile time feature flags. 
* Make the Configuration struct generic over some type T that implements a Client trait
* Store a Box<dyn Client> in the configuration struct.

**Comment by ctaggart** [comment]
Here is some prior art. May be one of these existing abstractions will work or help out.

reqwest use http = "0.2"
https://github.com/seanmonstar/reqwest/blob/master/Cargo.toml

surf uses http-types = "2.5.0"
https://github.com/http-rs/surf/blob/main/Cargo.toml

http vs http_types
https://github.com/hyperium/http/issues/437
https://github.com/http-rs/http-types/issues/248
https://blog.yoshuawuyts.com/async-http/#shared-abstractions

**Comment by MindFlavor** [comment]
Should we keep this open? 
At least until all the clients use the HttpClient trait?

**Comment by ctaggart** [comment]
Yes, let's keep it open until I complete the port of the mgmt services. I'm working on it.

**Comment by ctaggart** [comment]
#157 adds it to mgmt services.
