### ISSUE TITLE
target wasm & wasi too

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-sdk-for-rust#37]
I think it is an important use case to be able to target wasm & wasi with these crates. We will need to add these targets to CI:
```
rustup target add wasm32-unknown-unknown
rustup target add wasm32-wasi
```
I'm hoping we can get the right features in place to support this. An important part of this is being able to use a different http client like reqwest instead of hyper. The http client abstraction is #36.

**Comment by ctaggart** [comment]
tokio does not yet work with WebAssembly https://github.com/tokio-rs/tokio/issues/1597.  reqwest is tokio based. surf has a `wasm-client` feature, but I was not able to get this to compile for wasi because of dependencies https://github.com/http-rs/surf/issues/301:

``` rust
use async_executor::{Executor, Task};
use futures_lite::future;
use surf::Result;

fn main() -> Result<()> {
    let ex = Executor::new();
    let task: Task<Result<()>> = ex.spawn(async {
        let ip = surf::get("http://ip.jsontest.com/").await?.body_string().await?;
        println!("ip {}", &ip);
        Ok(())
    });
    future::block_on(ex.run(task))
}
```

**Comment by radu-matei** [comment]
Hi!
I've been working towards compiling this (or rather parts of this) library to `wasm32-wasi` so the SDK can be used from WASI modules. It is built on top of the [experimental HTTP library for WASI][http] (and Wasmtime). 

Here is the [_very early_ fork ][wip-fork], currently with support only for the blob storage SDK, with a [samples repo here][samples].

I'll update this issue as I work on it, but as everything is experimental, I don't expect to propose a PR here anytime soon. This is in case interested people want to follow the work.

Thanks!

[samples]: https://github.com/deislabs/azure-sdk-for-rust-wasi-samples
[wip-fork]: https://github.com/Azure/azure-sdk-for-rust/compare/master...radu-matei:enable-wasi-experimental-http?expand=1
[http]: https://github.com/deislabs/wasi-experimental-http

**Comment by radu-matei** [comment]
And here is how we are using the SDK from within WASI modules - https://github.com/deislabs/wagi-azure-samples

**Comment by ctaggart** [comment]
@radu-matei, this looks amazing! I look forward to trying it out once I have time.

**Comment by ctaggart** [comment]
@radu-matei, thanks for the blog post!
Using Azure services from WebAssembly modules
https://deislabs.io/posts/using-azure-services-wasi/

**Comment by thangchung** [comment]
That's cool. Just have a look at the repo at https://github.com/deislabs/wagi-azure-samples. But there are a lot of works to make it runs well with other Rust libs out there, almost based on [tokio-rs](https://github.com/tokio-rs/tokio/issues/1597) which couldn't run on WASM right now

**Comment by cataggar** [comment]
#939 add a wasm target, which was the goal of this issue. There is more work to be done to support it, but it is progress.
