### ISSUE TITLE
Add usage to SDK READMEs

### ISSUE THREAD

**Issue by cataggar** [Azure/azure-sdk-for-rust#379]
It is not obvious how to use the SDKs currently. Each README should show to use it currently. For example:

``` toml
azure_cosmos = { git = "https://github.com/Azure/azure-sdk-for-rust" }
```

> All of our READMEs across services / languages follow a similar pattern like this:
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Secrets/README.md

**Comment by deven96** [comment]
Was thinking of using `cargo readme` to keep the version and other details specific to each SDKs fresh on the README. Is that okay @rylev ?
