### ISSUE TITLE
X-IDENTITY-HEADER is not required when getting token

### ISSUE THREAD

**Issue by thovoll** [Azure/azure-sdk-for-rust#420]
ManagedIdentityCredential [requires](https://github.com/Azure/azure-sdk-for-rust/blob/efdc0ead81a2eabb1627aa4df7084756404f0343/sdk/identity/src/token_credentials/managed_identity_credentials.rs#L52) the environment variable IDENTITY_HEADER to be set and [sends](https://github.com/Azure/azure-sdk-for-rust/blob/efdc0ead81a2eabb1627aa4df7084756404f0343/sdk/identity/src/token_credentials/managed_identity_credentials.rs#L59) the value via the X-IDENTITY-HEADER when getting a token.

There is evidence of this header here, but related to Azure Automation and Azure App Service:
https://docs.microsoft.com/en-us/azure/automation/enable-managed-identity-for-automation
https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity?tabs=dotnet
https://github.com/Azure/azure-sdk-for-net/search?q=X-IDENTITY-HEADER

And this header isn't mentioned in the AMI docs:
https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-http

Nor in the canonical REST API specs:
https://github.com/Azure/azure-rest-api-specs/blob/60fcb275cbce38d343f9c35411786e672aba154e/specification/imds/data-plane/Microsoft.InstanceMetadataService/stable/2019-08-01/imds.json#L94

And it's not being set in this part of the .Net SDK:
https://github.com/Azure/azure-sdk-for-net/blob/c5738f34a5ded5bf4b49e380a8eec179e12a1c6b/sdk/identity/Azure.Identity/src/ImdsManagedIdentitySource.cs#L51

**Comment by mattsains** [comment]
I found a workaround - if you set the IDENTITY_HEADER environment variable to anything, it'll work - doesn't have to be valid.

**Comment by cataggar** [comment]
It was made optional by #775.
