### ISSUE TITLE
Rename ManagedIdentityCredential to ImdsManagedIdentityCredential 

### ISSUE THREAD

**Issue by thovoll** [Azure/azure-sdk-for-rust#423]
Current name: [ManagedIdentityCredential](https://github.com/Azure/azure-sdk-for-rust/blob/b5137482b420627579a6382dd9a2490ca17868e1/sdk/identity/src/token_credentials/managed_identity_credentials.rs#L40) 
Proposed name: ImdsManagedIdentityCredential 

This follows the name from the .Net SDK:
https://github.com/Azure/azure-sdk-for-net/blob/c5738f34a5ded5bf4b49e380a8eec179e12a1c6b/sdk/identity/Azure.Identity/src/ImdsManagedIdentitySource.cs#L15

**Comment by demoray** [comment]
This is done.
