### ISSUE TITLE
DefaultCredential swallows errors while getting token

### ISSUE THREAD

**Issue by thovoll** [Azure/azure-sdk-for-rust#424]
DefaultCredential tries getting a token using a series of TokenCredential sources. Any errors are logged but not returned.
https://github.com/Azure/azure-sdk-for-rust/blob/b5137482b420627579a6382dd9a2490ca17868e1/sdk/identity/src/token_credentials/default_credentials.rs#L143

The behavior in the .Net SDK seems to be to return a token if any of the sources was successful in getting one, otherwise return an aggregate exception with all the exceptions encountered from all the sources:
https://github.com/Azure/azure-sdk-for-net/blob/c5738f34a5ded5bf4b49e380a8eec179e12a1c6b/sdk/identity/Azure.Identity/src/DefaultAzureCredential.cs#L163

**Comment by JoshGendein** [comment]
I can commit to working on this.

**Comment by thovoll** [comment]
Thanks @JoshGendein!
