### ISSUE TITLE
Rename DefaultCredential to DefaultAzureCredential

### ISSUE THREAD

**Issue by thovoll** [Azure/azure-sdk-for-rust#425]
Current name: [DefaultCredential](https://github.com/Azure/azure-sdk-for-rust/blob/b5137482b420627579a6382dd9a2490ca17868e1/sdk/identity/src/token_credentials/default_credentials.rs#L110)
Proposed name: DefaultAzureCredential

This follows the name from the .Net SDK:
https://github.com/Azure/azure-sdk-for-net/blob/c5738f34a5ded5bf4b49e380a8eec179e12a1c6b/sdk/identity/Azure.Identity/src/DefaultAzureCredential.cs#L48

**Comment by cataggar** [comment]
Fixed by #488
