### ISSUE TITLE
Service directories

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-rust#478]
Across all our official Azure SDKs, we have a consistent directory structure of `sdk/{serviceDirectory}` e.g.

* https://github.com/Azure/azure-sdk-for-net/tree/main/sdk
* https://github.com/Azure/azure-sdk-for-java/tree/main/sdk
* https://github.com/Azure/azure-sdk-for-js/tree/main/sdk
* https://github.com/Azure/azure-sdk-for-python/tree/main/sdk

These service directory patterns are used in quite a few common pipelines maintained by the Azure SDK EngSys team, and something we should reflect as well.

To make it easier to split features into separate crates like we discussed in storage in our 11/2 sync-up, I recommend using a pattern similar to several other languages:

```
sdk/{serviceDirectory}/{crate}(/{feature}
```

Examples:

```
sdk/core/azure_core/
sdk/keyvault/azure_security_keyvault/
- certificates/
- keys/
- secrets/
sdk/storage/
- azure_storage/
- azure_storage_files/
```

**Comment by heaths** [comment]
To add, our [Test Resource deployment](https://github.com/Azure/azure-sdk-tools/tree/main/eng/common/TestResources) scripts I wrote will be handy eventually, and assume a structure like this.

**Comment by cataggar** [comment]
I'd prefer to keep them organized by crate names for now. These are all consistent:

- `azure_` crates are in /sdk/
- `azure_mgmt_ `crates in /services/mgmt/
- `azure_svc_` crates in /services/svc/

**Comment by heaths** [comment]
They would be, but under the service directory. Control plane (mgmt) could maybe live in their own directory, but even in other repos they tend to be under the service directory. As for generated clients, we'll eventually want to merge those as I mentioned in the meeting today with LLCs and a grow-up story.

I can't stress enough that for common infrastructure, the service directories must be consistent.

**Comment by cataggar** [comment]
I understand. Let's wait until after the 0.1 releases.
