### ISSUE TITLE
Add a `.github/CODEOWNERS`

### ISSUE THREAD

**Issue by cataggar** [Azure/azure-sdk-for-rust#480]
Add a `.github/CODEOWNERS` file following these instructions:
https://github.com/Azure/azure-sdk/blob/main/docs/policies/opensource.md#codeowners

Examples:

- https://github.com/Azure/azure-sdk-for-net/blob/main/.github/CODEOWNERS
- https://github.com/Azure/azure-sdk-for-python/blob/main/.github/CODEOWNERS
- https://github.com/Azure/azure-sdk-for-go/blob/main/.github/CODEOWNERS

Here is an initial list of owners (primary first) from my meeting notes:

/sdk/core/ @rylev @MindFlavor
/sdk/identity/ @thovoll @heaths 
/sdk/data_cosmos/ @rylev @MindFlavor 
/sdk/data_tables/ @MindFlavor 
/sdk/messaging_queues/
/sdk/storage_datalake/ @thovoll 
/sdk/storage_blobs/ @MindFlavor @thovoll 
/sdk/storage_files/
/sdk/security_keyvault/ @heaths 
/services/ @cataggar @bmc-msft 

Let me know if adjustments are needed.

**Comment by heaths** [comment]
@weshaggard @jsquire how can we get the auto-assignment bot hooked up as well? May not be there quite yet, but this is starting to take shape.

**Comment by jsquire** [comment]
If we're talking about the PR assignments, I'll need to defer to @weshaggard.   If you're looking to hook up `Service Attention` notifications, let me know and I can help.

**Comment by heaths** [comment]
What bot do we use for automatic triage, or is that still just JesseBot?

**Comment by weshaggard** [comment]
github will automatically add reviewers based on the CODEOWNER but that is different

**Comment by heaths** [comment]
Right, but we do have something for Azure/azure-sdk-for-net - or maybe I was thinking of the hackathon project Jesse was working on. 🤔

**Comment by jsquire** [comment]
> What bot do we use for automatic triage, or is that still just JesseBot?

There's no automatic triage yet, still just me.   One of these days, I'll get a chance to finish the ML bot but there's still a bunch to do.

**Comment by cataggar** [comment]
Not ready for  codeowners right now.
