### ISSUE TITLE
Remove azure_identity::TokenCredential trait in favor of azure_core::TokenCredential

### ISSUE THREAD

**Issue by thovoll** [Azure/azure-sdk-for-rust#489]
[azure_core::TokenCredential](https://github.com/Azure/azure-sdk-for-rust/blob/7bd9193dd6e593d23568afe3011a9bb72e465f3d/sdk/core/src/lib.rs#L79)
[azure_identity::TokenCredential](https://github.com/Azure/azure-sdk-for-rust/blob/7bd9193dd6e593d23568afe3011a9bb72e465f3d/sdk/identity/src/token_credentials/mod.rs#L23)

We should probably get rid of the TokenCredential in azure_identity. This seems to match the .Net SDK as well.

This implies that the [token credential implementations](https://github.com/Azure/azure-sdk-for-rust/tree/main/sdk/identity/src/token_credentials) need to switch to the TokenCredential trait from azure_core.

Further, if we decide to implement #426, it would be nice to avoid having to downcast errors produced by a TokenCredential when creating a client, in order to enable exhaustive matching.

**Comment by cataggar** [comment]
They are not quite the same.  See the comments:

https://github.com/Azure/azure-sdk-for-rust/blob/7bd9193dd6e593d23568afe3011a9bb72e465f3d/sdk/identity/src/token_credentials/mod.rs#L20-L27

**Comment by cataggar** [comment]
> it would be nice to avoid having to downcast errors produced by a TokenCredential when creating a client, in order to enable exhaustive matching
 
 Can you give an example, so I can better understand what you are trying to do?

**Comment by thovoll** [comment]
Thanks @cataggar, I did see the comment in the code. @rylev and I looked at this code together this morning in the context of trying to determine feasibility of implementing #426 (not needed for 0.1.0 I think but I was in the area anyway). 

Taking the azure_identity::TokenCredential into clients is causing some problems because all the TokenCredential implementations have different Error types. I'm not good enough yet at Rust errors to be able to fully articulate @rylev's arguments so I'll ask him to also chime in here.

**Comment by rylev** [comment]
The reason that having a single unified error type and not allowing individual implementations to specfify different errors is that we want to be able to use this trait as a trait object (e.g., `Box<dyn TokenCredential>`) which we cannot do unless the error types are unified. The flexibility of having individual error types per implementation is not needed and makes things complicated and/or impossible. 

It's my belief we should unify on one error type (something like `TokenCredentialError`) that is the union of all possible error cases from getting a token.

**Comment by thovoll** [comment]
In #426, we want to be able to pass any TokenCredential to a client. This is easy in C# because it has only unchecked exceptions, but requires more careful design in Rust.

**Comment by cataggar** [comment]
Fixed by #781.
