### ISSUE TITLE
Allow creation of nested clients directly?

### ISSUE THREAD

**Issue by thovoll** [Azure/azure-sdk-for-rust#490]
Example:

In the .Net SDK, a DataLakeFileSystemClient can be [created directly](https://github.com/Azure/azure-sdk-for-net/blob/3b3a6c7450f781d55d83441b129b9ad23a8238ea/sdk/storage/Azure.Storage.Files.DataLake/src/DataLakeFileSystemClient.cs#L332), or [from a DataLakeServiceClient](https://github.com/Azure/azure-sdk-for-net/blob/3b3a6c7450f781d55d83441b129b9ad23a8238ea/sdk/storage/Azure.Storage.Files.DataLake/src/DataLakeServiceClient.cs#L401). In both cases, the DataLakeFileSystemClient doesn't keep a reference to the DataLakeServiceClient.

In the Rust SDK, creating a FileSystemClient [requires a DataLakeClient](https://github.com/Azure/azure-sdk-for-rust/blob/7bd9193dd6e593d23568afe3011a9bb72e465f3d/sdk/storage/src/data_lake/clients/file_system_client.rs#L31) and a reference to DataLakeClient is kept. Further, DataLakeClient keeps a reference to StorageClient, which in turn keeps a reference to StorageAccountClient. 

How can we align this better with the .Net SDK? 

It seems better to be able to directly create a DataLakeFileSystemClient from a user perspective, and it seems better to not have to keep a chain of references DataLakeFileSystemClient all the way back up to StorageAccountClient from a maintainer perspective (full assessment TBD). In fact, the .Net SDK doesn't even have a StorageAccountClient or a StorageClient, which also seems better.

**Comment by cataggar** [comment]
The generated services have child Clients for all operation groups. The main Client is cloneable with Arc around some members. I'd recommend that approach. You could add a `new` to the child, but internally, that is what it would do.

https://github.com/Azure/azure-sdk-for-rust/blob/5d9600a7d0d7bf1740ddaabf47247eb58c0ece0a/services/mgmt/vmware/src/package_2021_12_01/operations.rs#L6-L88
