### ISSUE TITLE
generate Clients for services

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-sdk-for-rust#50]
The generated code for each operation currently takes a `Configuration`. This is how opening-generator currently does it. The other Azure SDKs generate Clients instead. It may be possible to do it that way instead. We will need to evaluate the trade-offs.

**Comment by ctaggart** [comment]
I'm leaving it as `OperationConfig` for now.

**Comment by cataggar** [comment]
In #417, @bmc-msft provides examples for other Azure SDK languages, which pass the configuration into clients. I is time to reevaluate this in combination with moving to the pipeline architecture #294.
