### ISSUE TITLE
CertificateClient::new does not allow for optional api-versions

### ISSUE THREAD

**Issue by Billy-Sheppard** [Azure/azure-sdk-for-rust#516]
Tracking for point brought up in PR#334

How do they specify an optional api-version? If leaving for later, please open a tracking issue. IIRC, we were going to have a `new_with_options` or something like that which took options which allow that, among other things like user-defined policies. We have that in some clients now, like cosmos and/or storage.

_Originally posted by @heaths in https://github.com/Azure/azure-sdk-for-rust/pull/334#discussion_r734779471_

**Comment by heaths** [comment]
@cataggar this is needed for all clients, per Azure SDK guidelines. We are currently tracking this as part of #466.
