### ISSUE TITLE
Implement credential auto-refresh in authorization_policy

### ISSUE THREAD

**Issue by thovoll** [Azure/azure-sdk-for-rust#543]
Here are some starting points in other Azure SDKs:
* https://github.com/Azure/azure-sdk-for-net/blob/6afdb92e398d63280f2225b54c19386a91b50485/sdk/core/Azure.Core/src/Pipeline/BearerTokenAuthenticationPolicy.cs#L195-L337
* https://github.com/Azure/azure-sdk-for-java/blob/e5b28c9da4ad7e7601f106ff1dfe23644885e9f2/sdk/core/azure-core/src/main/java/com/azure/core/implementation/AccessTokenCache.java#L64-L146

**Comment by cataggar** [comment]
Token caching landed in #1484.
