### ISSUE TITLE
Creating Device or Module with AuthenticationMechanism type Authority does not work

### ISSUE THREAD

**Issue by rerkcp** [Azure/azure-sdk-for-rust#549]
This code does not work:
```
    let device = service_client
            .create_device_identity()
            .execute(
                &device_id,
                Status::Enabled,
                AuthenticationMechanism::new_using_certificate_authority(),
            )
            .await?;
```
The request creates a device using SAS authentification instead.

The problem lies in the definition of AuthenticationMechanism:
```
pub enum AuthenticationType {
    /// Authentication using certificate
    #[serde(rename = "certificate")]
    Certificate,
    /// Authentication using a certificate authority.
    #[serde(rename = "Authority")]
    Authority,
    /// The device or module is not authenticated.
    #[serde(rename = "none")]
    None,
    /// Authentication using symmetric keys
    #[serde(rename = "sas")]
    SAS,
    /// Authentication using self signed certificates
    #[serde(rename = "selfSigned")]
    SelfSigned,
}
```

This struct is likely a mistranslation of the documentation (like at https://docs.microsoft.com/en-us/rest/api/iothub/service/devices/create-or-update-identity#authenticationmechanism), where it looks like 
```
enum:
certificate
Authority
none
sas
selfSigned
```
due to the web layout. Looking at https://github.com/Azure/azure-iot-sdk-python/blob/bf34f908427b854542d2dd4f4ada906b9a819fad/azure-iot-hub/azure/iot/hub/protocol/models/authentication_mechanism.py#L21 shows that "certificateAuthority" needs to be one word and "certificate" is not an option.

PR #548 fixes this issue.

**Comment by cataggar** [comment]
PR #548 was merged
