### ISSUE TITLE
upgrade to tokio 1.0

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-sdk-for-rust#60]
This requires other dependencies to upgrade first:
- [x] hyper v0.14 https://github.com/hyperium/hyper/issues/2302
- [x] hyper v0.14 https://github.com/hyperium/hyper/milestone/6
- [x] reqwest ? https://github.com/seanmonstar/reqwest/issues/1060

**Comment by ctaggart** [comment]
reqwest just released with support for tokio 1.0 https://github.com/seanmonstar/reqwest/releases/tag/v0.11.0

**Comment by ctaggart** [comment]
It builds on top of top of hyper 0.14 which came out a couple of weeks ago. https://github.com/hyperium/hyper/releases

**Comment by rylev** [comment]
This is fixed in the SDK crates and needs to only be updated in the services crates now.

**Comment by karataliu** [comment]
Seems I cannot use storage controlplane(mgmt) SDK(tokio 0.2)  dataplane(tokio 1.0) in same function now:

When runtime is 1.0:
```
panicked at 'not currently running on the Tokio runtime.', \.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.0.1\src\runtime\blocking\pool.rs:84:33
```

When runtime is 0.2, it will complain from 0.2 code.

**Comment by ctaggart** [comment]
@karataliu, apologies. Working on the upgrade.

**Comment by ctaggart** [comment]
I'm just waiting on #143 to be merged first. The fix in just updating these dependencies:

![image](https://user-images.githubusercontent.com/80104/104419474-5dc4cd00-552d-11eb-8a65-635332a7c3de.png)
