### ISSUE TITLE
Please transfer ownership of azure_core crate 🙏 

### ISSUE THREAD

**Issue by cataggar** [Azure/azure-sdk-for-rust#621]
Hello @ForgettableDalit,

We are ready to publish `azure_core` crate to crates.io, but it looks like you published a 0.2.0 there 23 days ago on December 29th by mistake.

https://crates.io/crates/azure_core/versions shows that you published it and then yanked it.

![image](https://user-images.githubusercontent.com/87583576/150571648-4bc96dc1-9e3b-43dd-9ac3-5645abec643c.png)

It looks like `azure_core_mirror` is where you meant to publish.

![image](https://user-images.githubusercontent.com/87583576/150571929-d8a0022c-c871-49e3-83f0-dbeb498905e3.png)

Can you help me get the `azure_core` crate name back?

It would be great if crates.io added support for scopes like https://docs.npmjs.com/about-scopes.

**Comment by cataggar** [comment]
@ForgettableDalit, the command to run is:
```
cargo owner --add cataggar -- azure_core
```

**Comment by ForgettableDalit** [comment]
Hi! Sorry for the delay. I've added you as an owner for the azure_core crate.
Best wishes and apologies for the inconvenience.

**Comment by cataggar** [comment]
Thank you so much @ForgettableDalit ! I received ownership and then granted it to:
https://github.com/orgs/Azure/teams/azure-sdk-publish-rust
cargo owner --add github:Azure:azure-sdk-publish-rust -- azure_core
