### ISSUE TITLE
looking for appinsights-rs maintainer

### ISSUE THREAD

**Issue by cataggar** [Azure/azure-sdk-for-rust#642]
@dmolokanov is looking for a new maintainer for https://github.com/dmolokanov/appinsights-rs .

My preference is to keep it as a separate repo, similar to how https://github.com/Microsoft/ApplicationInsights-dotnet is separate. Thoughts?

**Comment by samueleresca** [comment]
Hi @cataggar,

I have some time for contributions, so I'm happy to help here.
