### ISSUE TITLE
clients for Azure DevOps REST APIs

### ISSUE THREAD

**Issue by cataggar** [Azure/azure-sdk-for-rust#644]
Azure DevOps has its own large set of specifications. AutoRust could be updated to generated clients for it.

Documentation
https://aka.ms/azure-devops-rest-apis

Specs
https://github.com/MicrosoftDocs/vsts-rest-api-specs/tree/master/specification

Prior art & related examples:
- https://github.com/Microsoft/azure-devops-go-api
- https://github.com/Microsoft/azure-devops-dotnet-samples
- https://github.com/microsoft/azure-devops-node-api
- https://github.com/microsoft/azure-devops-auth-samples
- https://github.com/microsoft/azure-devops-python-api

If not sure if they should live in this repo or be separate. My first hunch is that they should be separate.

**Comment by samueleresca** [comment]
Same as [642](https://github.com/Azure/azure-sdk-for-rust/issues/642), I have some time for contributions. I'm happy to help here.

**Comment by cataggar** [comment]
This is now public!
https://github.com/microsoft/azure-devops-rust-api
