### ISSUE TITLE
azure_storage should use azure_core::Body (or some variant) instead of Bytes

### ISSUE THREAD

**Issue by bmc-msft** [Azure/azure-sdk-for-rust#646]
Right now, all of the blob storage operations require passing Bytes, which translates to having everything in memory to make a request.  This makes uploading large files exceedingly difficult, even uploading the file using multiple PutBlock calls.

Right now, Blob storage allows blobs to have up to 50,000 blocks, with each block up to 4000 MiB, for a total of approximately 190.7TiB.  [^1]

Right now, in order to upload such a file, each 4000MiB block must be entirely read into memory before uploading.  Both `reqwest` [^2] and `hyper` [^3] support a mechanism to wrap a Stream, which would enable streaming the input, rather than reading it entirely in memory first.   

Work added in #230 started the work to support this by adding azure_core::SeekableStream.

[^1]: https://docs.microsoft.com/en-us/azure/storage/blobs/scalability-targets#scale-targets-for-blob-storage
[^2]: https://docs.rs/reqwest/0.11.9/reqwest/struct.Body.html#method.wrap_stream
[^3]: https://docs.rs/hyper/latest/hyper/body/struct.Body.html#method.wrap_stream

**Comment by cataggar** [comment]
May be we should look at building off of https://crates.io/crates/http-types instead of https://crates.io/crates/http.

> Body represents the HTTP body of both Request and Response. It’s completely streaming, and implements AsyncBufRead to make reading from it both convenient and performant.
https://docs.rs/http-types/latest/http_types/struct.Body.html

cc @yoshuawuyts
