### ISSUE TITLE
get list of owned crates

### ISSUE THREAD

**Issue by cataggar** [Azure/azure-sdk-for-rust#648]
We need a way to list the crates owned by `azure-sdk-publish-rust`.
https://crates.io/teams/github:azure:azure-sdk-publish-rust

It currently has 232 crates and https://crates.io/users/cataggar has 234 crates, so there are 2 that I still need to add the team to. When we automate publishing, we'll need a know when a crate is new and add the team.

**Comment by cataggar** [comment]
Up to 254. They are all synced. PR incoming soon.

**Comment by ctaggart** [comment]
Fixed in #822
