### ISSUE TITLE
Error retrieving list of subscriptions

### ISSUE THREAD

**Issue by polivbr** [Azure/azure-sdk-for-rust#650]
When attempting to retrieve a list of subscriptions with `azure_mgmt_subscription::operations::subscriptions::Client::list()`, I receive the following error:

` Deserialize(Error("missing field 'nextLink'", line: 1, column: 1670)`

It appears that this is due to `SubscriptionListResult::next_link` being non-optional, yet Azure isn't returning a `nextLink` field because there aren't enough subscriptions to need to page.

I'd try to pull together a PR, but I don't have the time to figure out the auto-rust magic.

**Comment by cataggar** [comment]
> I'd try to pull together a PR, but I don't have the time to figure out the auto-rust magic.

Thanks @polivbr. Pull requests that should what the generated code should look like are very useful. You can also use the fixed branches directly using a git dependency in Cargo.toml. This is probably going to be a spec bug, which I can report.

**Comment by cataggar** [comment]
Fixed by #672.
