### ISSUE TITLE
Doc for storage package not up-to-date

### ISSUE THREAD

**Issue by karataliu** [Azure/azure-sdk-for-rust#654]
https://github.com/Azure/azure-sdk-for-rust/tree/main/sdk/storage
```
This crate has several features depending on what part of the storage service you need:

Account
Blob
Queue
Table
By default all of these features are turned on. If you only need a specific feature, make sure to specify which features you need in your Cargo.toml file like so:
```

Features like `blob`,`queue` are removed in https://github.com/Azure/azure-sdk-for-rust/commit/08d500061ecdb21a9825da134d0dc5a53d5a7e53#diff-6a5d5507b372fdb01232bc2595b6c7301cfc3bb24d5a67ea83d95447f50b8d57

**Comment by cataggar** [comment]
You are correct. https://github.com/Azure/azure-sdk-for-rust#readme is more up-to-date.

**Comment by karataliu** [comment]
it's impacting https://crates.io/crates/azure_storage, which also contains wrong statement
