### ISSUE TITLE
client::with_bearer_token() borrows account and token parameters

### ISSUE THREAD

**Issue by spektom** [Azure/azure-sdk-for-rust#68]
The method borrows `account` and `token` parameters for an indefinite time.
This makes it harder for use. Is there any reason to that or the API can be adapted to work in the same way as `client::with_access_key` or `client::with_azure_sas` ?

**Comment by rylev** [comment]
Yes, I don't think there's any reason to not take ownership of account and token.

**Comment by MindFlavor** [comment]
Hi spektom,
`client::with_bearer_token()` allow borrowing and taking ownership while both `client::with_access_key` and `client::with_azure_sas` only allow borrowing. See:

https://github.com/Azure/azure-sdk-for-rust/blob/c4455a238f7b49985de4dbef17d416c7d320aca5/sdk/storage/src/core/client.rs#L155

and 

https://github.com/Azure/azure-sdk-for-rust/blob/c4455a238f7b49985de4dbef17d416c7d320aca5/sdk/storage/src/core/client.rs#L139

While `client::with_bearer_token()` allows both borrowing and taking ownership. 

https://github.com/Azure/azure-sdk-for-rust/blob/c4455a238f7b49985de4dbef17d416c7d320aca5/sdk/storage/src/core/client.rs#L229-L232

So they should behave just the same (with `client::with_bearer_token()` being more flexible).

For example, this borrows:

https://github.com/Azure/azure-sdk-for-rust/blob/c4455a238f7b49985de4dbef17d416c7d320aca5/sdk/storage/examples/blob_00.rs#L17-L24

This example takes ownership:

https://github.com/Azure/azure-sdk-for-rust/blob/c4455a238f7b49985de4dbef17d416c7d320aca5/sdk/storage/examples/blob_02_bearer_token.rs#L13-L26

But the latter works just the same if you borrow instead:

```rust
    let client = client::with_bearer_token(&account, &bearer_token);
```

--

Can you please provide a repro of your problem?

**Comment by spektom** [comment]
Thanks, and sorry for bothering.

**Comment by MindFlavor** [comment]
> Thanks, and sorry for bothering.

Don't worry, you correctly pointed out that we have uneven builders: the all should allow both borrowing and owning :+1: !

**Comment by rylev** [comment]
I somewhat disagree. I don't think allowing for the flexibility of taking either a reference or an owned value is really worth the complexity. Taking these as `String` instead of `Cow<'a, str>` would simplify the API considerably at only a very minimal potential runtime cost.
