### ISSUE TITLE
Attempting to enable hyper causes azure_core to fail to compile

### ISSUE THREAD

**Issue by pcd1193182** [Azure/azure-sdk-for-rust#688]
Hello, I'm attempting to use these crates to access Azure Blob Storage. Because this is a new feature for an existing project, the code already uses Hyper under the hood, so I was attempting to replicate that in the use of these crates as well. However, when I attempt to enable hyper on the `azure_core` crate, it fails to compile with a large number of error messages. This is true even if I use `default-features = false` to attempt to disable the default reqwest support.

Among the issues are misuse of the hyper_rustls crate (`with_native_roots` is a function on the HttpsConnectorBuilder in 0.23, not the HttpsConnector), there is no `new_unexpected_status_code` in HttpError, and more.

Is the use of `hyper` currently supported with these crates, and if not, is there anything that can be done to help get support for it off the ground? Thanks!

**Comment by cataggar** [comment]
@pcd1193182, by default `reqwest` uses `hyper`. Is there a reason `reqwest` doesn't work for you?

https://github.com/Azure/azure-sdk-for-rust/blob/34e6cadce7d6938ee2e08b321955e7177036ac6a/sdk/core/Cargo.toml#L50-L54

**Comment by pcd1193182** [comment]
So far we haven't had any issues with using reqwest. We originally wanted to use hyper because we understand it to be more performant, and to just reduce the total size of our dependency graph.

**Comment by cataggar** [comment]
You could implement `HttpClient` to pass in a version that does not use reqwest. #760 removes this defunct feature. After it is merged, I'll have another PR for making reqwest optional.
