### ISSUE TITLE
Return structured response from blob functions (and others) instead of boxed trait object

### ISSUE THREAD

**Issue by pcd1193182** [Azure/azure-sdk-for-rust#692]
If users want to be able to try to intelligently handle different kinds of errors returned by Azure, it would be helpful if the returned error type from requests was a structured entity (like the already existing HttpError) rather than a boxed trait object. I know the SDK is still in beta, but the `non_exhaustive` annotation already warns users to watch out for changes in the structure, and it makes errors much easier to handle when doing GetBlob, CopyBlob, and other requests.

**Comment by gzp-crey** [comment]
I agree as now a downcast_ref is required instead of a simple pattern matching.

**Comment by cataggar** [comment]
@gzp-crey, can you provide an example currently with the `downcast_ref` and what an example of what you would like to see?

**Comment by pcd1193182** [comment]
Our error handling logic looks something like:
```
fn convert_error(e: Box<dyn Error + Send + Sync>) -> OurError {
    let http_error: Box<HttpError> = e.downcast().unwrap();
    match e {
        HttpError::StatusCode { status, body: _ } => {
            ...
        }
    }
}
```
with a number of From and MaybeFrom impls to help convert the different error types into our internal representation.

**Comment by gzp-crey** [comment]
My current usage:
```
            let response = self.container_client.as_blob_client(url.path()).get().execute().await;
            match response {
                Ok(response) => ...
                Err(err) => {
                    if let Some(HttpError::StatusCode { status, .. }) = err.downcast_ref::<HttpError>() {
                        if status.as_u16() == 404 {
                            Ok(ConditionalRead::NotFound)
                        } else {
                            Err(AssetIOError::AzureError(AzureError::General(err)))
                        }
                    } else {
                        Err(AssetIOError::AzureError(AzureError::General(err)))
                    }
                }
            }
```

But if there were enum variants, without `Box<dyn Error>', it'd be simplified into a much simple match: (also it would require one less heap usage)

```
            let response = self.container_client.as_blob_client(url.path()).get().execute().await;
            match response {
                Ok(response) => ...
                Err(HttpError::StatusCode { status, .. }) => ...
                Err(err) => Err(AssetIOError::AzureError(err.into()))
            }
```

**Comment by bmc-msft** [comment]
The storage crates now use azure_core::error::Error, which addresses this.
