### ISSUE TITLE
How to access get_page_ranges?

### ISSUE THREAD

**Issue by sga001** [Azure/azure-sdk-for-rust#723]
Is there a way to call get_page_ranges (https://docs.microsoft.com/en-us/rest/api/storageservices/get-page-ranges) from a blob client? or is there any other way to call that API?

**Comment by wdcui** [comment]
I coded up a commit to support get_page_ranges.  How can I create a pull request for my code?

**Comment by wdcui** [comment]
I created a pull request to resolve this issue.

#725
