### ISSUE TITLE
Question about blob operations with etag conditions.

### ISSUE THREAD

**Issue by gzp-crey** [Azure/azure-sdk-for-rust#730]
I don't see how to perform blob operation (get, put, delete) with IfMatch, IfNoneMatch conditions.
(edit: just to be clear on the operations and context: [Operations](https://docs.microsoft.com/en-us/rest/api/storageservices/operations-on-blobs); [Conditional headers](https://docs.microsoft.com/en-us/rest/api/storageservices/specifying-conditional-headers-for-blob-service-operations) )

For example How can I set these headers through the `GetBlobBuilder`.

**Comment by gzp-crey** [comment]
I'm a bit confused of sdk and svc struture. I see svc is code generated clients and sdk is hand written, 
but while svc has a full feature set (ex https://github.com/Azure/azure-sdk-for-rust/blob/89e9f7189daf847b88b7e0b766ab52d69d546044/services/svc/blobstorage/src/package_2020_10/operations.rs#L3358)
the sdk lacks many of them.
 
Could you please update the readme.md as it states only their existence but not what is the planned/intended relationship between them. As a newbie to this crate I'm really confused and cannot figure out what to use (and not use).

**Comment by cataggar** [comment]
In the future, we'd like the sdk crates to use the generated svc crates to provide a more ergonomic API than what can be generated. A blocker for azure_svc_blobstorage right now is xml support #649. We are currently looking at integrating a smaller crate, device_update, to figure out best practices. cc @bmc-msft
