### ISSUE TITLE
IoT Hub Device SDK

### ISSUE THREAD

**Issue by mladedav** [Azure/azure-sdk-for-rust#731]
Hi, I am currently using Rust to connect and send messages to Azure IoT Hub. I noticed this functionality is missing here which I think is a shame since Rust gains some popularity in the embedded world.

I would like to contribute but first I want to get an OK from maintainers that this is something they would like to see here.

**Comment by Dessix** [comment]
I’m not a maintainer on this repo, but I’d like to see it and would be willing to help with code reviews.

**Comment by cataggar** [comment]
So you are looking for something similar to the [Azure IoT device SDK for C](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-device-sdk-c-intro). Do any of these generated crates help?

- https://crates.io/crates/azure_mgmt_iothub
- https://crates.io/crates/azure_mgmt_iotcentral
- https://crates.io/crates/azure_svc_iotcentral
- https://crates.io/crates/azure_svc_deviceupdate, see #733

**Comment by mladedav** [comment]
@cataggar I am looking for a subpackage in the C SDK to connect to IoT Hub as a device (https://github.com/Azure/azure-iot-sdk-c/tree/main/iothub_client)

The first two crates you have posted are management APIs to create or manage actual Azure resources. The other two are cloud-side data plane operations on objects in the IoT Hub/Central, but it is still cloud-side management of the devices.

I am talking about a library created for devices so that they are able to connect to IoT Hub and send messages through MQTT.

**Comment by cataggar** [comment]
I think IoT support in Rust is a great use case. To help build the business case, please fill out the survey that I linked in #738.

**Comment by mladedav** [comment]
I have personal experience only with `rumqttc` but `ntex` seems intreguing. On the first look there may be an issue with TLS because it seems to use only rustls which cannot be used to connect to Azure IoT Hub (there are no shared cipher suites without enabling preview options on the IoT  Hub). For the record `rumqttc` currently does not support `native-tls` but there is an open PR for that.

**Comment by cataggar** [comment]
> An MQTT v3.1.1 Client implementation in Rust
https://github.com/Azure/iotedge/tree/main/mqtt/mqtt3

cc @onalante-msft

**Comment by CedricLemay** [comment]
I would also need this feature. Any development on this?

**Comment by cataggar** [comment]
This would be awesome to have, but needs to be funded. It is not planned for now.
