### ISSUE TITLE
make the sdk wasm32-wasi compatible

### ISSUE THREAD

**Issue by Mossaka** [Azure/azure-sdk-for-rust#735]
Currently the `azure-core` has a dependency on `reqwest`, which is depended on `wasm-bindgen`. This package can only be used to compile to `wasm32-unknown-unknown` target, used in browser. 

However, this prevent the crate to be compatible to `wasm32-wasi` target. 

Could we make the dependency on `reqwest` an optional feature?

**Comment by cataggar** [comment]
Yes, we'll accept pull requests to make it truly optional. It is already marked as optional in `azure_core`:

https://github.com/Azure/azure-sdk-for-rust/blob/66db4b485ce56b68be148708d9c810960a50be51/sdk/core/Cargo.toml#L28-L30

**Comment by cataggar** [comment]
#755 is in draft to fix this.

**Comment by Mossaka** [comment]
Huge thanks!

**Comment by cataggar** [comment]
I think #939 completed this.
