### ISSUE TITLE
generated crates need to support `x-ms-pageable`

### ISSUE THREAD

**Issue by bmc-msft** [Azure/azure-sdk-for-rust#736]
In the specs, the way to support pageable is to provide the field `x-ms-pageable` in the operation.  This is described in the autorest specification here:

https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-pageable

We should probably use `azure_core::Pageable` and generate an `into_stream` automatically if the `x-ms-pageable` is provided.

**Comment by cataggar** [comment]
This is very much needed. This duplicates #218, but has a better description. I think we may be able to close #341.

**Comment by cataggar** [comment]
Fixed by #742.
