### ISSUE TITLE
StorageAccountClient bearer token refresh

### ISSUE THREAD

**Issue by yvespp** [Azure/azure-sdk-for-rust#739]
While looking into https://github.com/vectordotdev/vector/issues/8667 I noticed that the client doesn't refresh the bearer token and will stop working once it expires.

Is there a way to refresh the token automatically?

I've seen that there is [AutoRefreshingTokenCredential](https://github.com/Azure/azure-sdk-for-rust/blob/main/sdk/identity/src/token_credentials/auto_refreshing_credentials.rs) but it can't be passed to the StorageAccountClient at the moment.

**Comment by cataggar** [comment]
@yvespp, new crates were published on Friday. AutoRefreshingTokenCredential is in azure_identity 0.2.0.

**Comment by yvespp** [comment]
@cataggar ok, but I don't see a way to use AutoRefreshingTokenCredential with the StorageAccountClient. The client takes the token as a string https://github.com/Azure/azure-sdk-for-rust/blob/beb3375631cfa31849775682ad82d39394e1dfee/sdk/storage/src/core/clients/storage_account_client.rs#L37 and not as a TokenCredential?
