### ISSUE TITLE
add AutoRust support for x-ms-enum modelAsString

### ISSUE THREAD

**Issue by cataggar** [Azure/azure-sdk-for-rust#768]
#413 is for x-ms-enum in general, but this is specifically `modelAsString` support. When an enumeration is markes as `"modelAsString": true`, it is extensible. 

Currently, the `cargo run --package azure_mgmt_compute --example vm_list` example fails for me because one of my VMs is a size not in the enum.

An snippet from a spec: `Microsoft.Compute\stable\2021-11-01\compute.json`

``` json
    "HardwareProfile": {
      "properties": {
        "vmSize": {
          "type": "string",
          "enum": [
            "Basic_A0",
            "Basic_A1",
            "Basic_A2",
            "Basic_A3",
            "Basic_A4",
            "Standard_A0",
            "Standard_A1",
            "Standard_A2",

            "Standard_ND6s",
            "Standard_ND12s",
            "Standard_ND24s",
            "Standard_ND24rs",
            "Standard_NV6",
            "Standard_NV12",
            "Standard_NV24"
          ],
          "x-ms-enum": {
            "name": "VirtualMachineSizeTypes",
            "modelAsString": true
          }
        },
```

The generated code looks like this:
``` rust
pub mod hardware_profile {
    use super::*;

    #[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
    pub enum VmSize {
        #[serde(rename = "Basic_A0")]
        BasicA0,
        #[serde(rename = "Basic_A1")]
        BasicA1,
        #[serde(rename = "Basic_A2")]
```

We need a way to deserialize and deserialize other string values using serde.

**Comment by johnbatty** [comment]
I looked at this a while back and concluded that it wasn't possible with the standard serde features, and that we'd probably need to generate explicit serializer/deserializer code.

However, I just looked again, and found the `serde-enum-str` crate which looks promising:
https://stackoverflow.com/questions/57469527/how-can-i-support-an-unknown-or-other-value-for-a-serde-enum
https://docs.rs/serde-enum-str/latest/serde_enum_str/

Would you be happy for the additional enum value to be `Other(String)`?

**Comment by johnbatty** [comment]
Bah... I just implemented this, only to find that:
- there are some enums that have an `Other` value
- there are some enums that have an `Error` value with clashes with an `Error` type used within the `serde-enum-str` macros!

**Comment by johnbatty** [comment]
Think I'll try replacing `serde-enum-str` with the workaround at the end of: https://github.com/serde-rs/serde/issues/912.

That will fix my `Error` error.  Then we just need to decide how to resolve the clash between `Other` and the new field `Other(String)`.  Possibly alternative names for the new field...
- `OtherValue(String)`
- `Unknown(String)`
- `Unrecognized(String)`

Any alternative suggestions welcome.

I haven't yet checked whether any of these clash with existing enum values!  I guess `OtherValue(String)` has least chance of clashing.

**Comment by cataggar** [comment]
#769 used `UknownValue`. That works for me.
