### ISSUE TITLE
refactor header helpers

### ISSUE THREAD

**Issue by cataggar** [Azure/azure-sdk-for-rust#837]
``` rust
 pub fn get_as_str<T: Into<HeaderName>>(&self, key: T) -> Option<&str> {
        self.get(key).map(|v| v.as_str())
    }
```

> I think we should just get rid of the variants of this methods and only have the variants which return a `crate::Result`. If you need an option, you can just call `.ok()` on the `Result`. 
And of course, then we just use the simpler naming convention and not the `or_err` names.
https://github.com/Azure/azure-sdk-for-rust/pull/833#pullrequestreview-1013829560

``` rust
    pub fn get_as_enum<T: Into<HeaderName>, V: FromStr<Err = E>, E>(
```

> This is a bit more general than for enums. Can we call this `get_as_parsed` or something like that? I think `get_as_u64_or_err`  can be implemented using this function.

**Comment by cataggar** [comment]
`get_as_parsed` sounds good. I'm not sure about removing the variants. Right now:
- Option is used if the header is optional
- `or_err` variants are a shortcut for `unwrap_or_err` for when the header is required, if return a `Result::Err`.
- the `get_as_u64` and `get_as_enum` may fail parsing, and thus return a `Result::Err`

Some options I'd like to explore:
- keep fallible conversions separate and remove `get_as_u64` and `get_as_enum`
- renaming `or_err` functions
  - may be `require`, `require_str` and `require_string`

**Comment by rylev** [comment]
The last thing to consider is renaming some of the methods. I'll take a look at that tomorrow.

**Comment by rylev** [comment]
This was finished in #864
