### ISSUE TITLE
remove `chrono` dependency in favor of `time`

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-sdk-for-rust#905]
[chrono](https://crates.io/crates/chrono) has not been updated in almost 2 years with 0.4.19 being the latest version. [time](https://crates.io/crates/time) development is active. There was some discussion previously in #559 about this. If we are able to update our dependency on it, may be we can get oauth2 to as well.

time 0.1.44
└── chrono 0.4.19
    ├── oauth2 4.2.2
    │   ├── azure_storage_blobs 0.4.0
    │   ├── azure_security_keyvault 0.3.0
    │   │   └── azure_identity 0.4.0

**Comment by ctaggart** [comment]
created https://github.com/ramosbugs/oauth2-rs/issues/177

**Comment by bmc-msft** [comment]
Note, this is in conflict with #51

**Comment by rylev** [comment]
FYI: development on chrono has picked up again under new maintainers. There have been 2 release candidate releases and a new release should be coming soon: https://crates.io/crates/chrono/versions
