### ISSUE TITLE
Build fails => cargo build --target wasm32-wasi --release

### ISSUE THREAD

**Issue by kamlesh-nb** [Azure/azure-sdk-for-rust#906]
I am trying to build rust lib with create-type as cdylib with target as wasm32-wasi, build fails with below error. Trying to build webassembly microservice using azure cosmosdb, any quick help would be highly appreciated.

```rust
error[E0277]: the trait bound `ClientOptions: Default` is not satisfied
   --> C:\Users\xxxx\.cargo\registry\src\github.com-1ecc6299db9ec823\azure_data_cosmos-0.4.0\src\clients\cosmos.rs:174:5
    |
172 | #[derive(Debug, Clone, Default)]
    |                        ------- in this derive macro expansion
173 | pub struct CosmosOptions {
174 |     options: ClientOptions,
    |     ^^^^^^^^^^^^^^^^^^^^^^ the trait `Default` is not implemented for `ClientOptions`
```

**Comment by rylev** [comment]
On a technical level this is because, `ClientOptions` does not implement `Default` when targeting the wasm32 architecture.

https://github.com/Azure/azure-sdk-for-rust/blob/2bf0bc42ff39cf7b8072d7b64b470d569ad2626c/sdk/core/src/options.rs#L19-L26

However, I'm not sure why this is. Perhaps @cataggar who was the author of that change might have some insight.

**Comment by cataggar** [comment]
@rylev, we don't have a default HttpClient for wasm32, so there is no default TransportOptions for wasm32. An alternative would be to have a default NoopHttpClient or similar, but you trade a compile time error for a runtime error.

https://github.com/Azure/azure-sdk-for-rust/blob/2bf0bc42ff39cf7b8072d7b64b470d569ad2626c/sdk/core/src/options.rs#L179-L217

**Comment by rylev** [comment]
I think we'll want to have a noop transport layer that panics when called. @yoshuawuyts and I are working on making it easier to set custom transport policies. This way users of wasm can set their own transport policies depending on what they want to assume about their environment (e.g., using browser APIs if running in the browser or WASI apis if running in a WASI environment).
