### ISSUE TITLE
When is the next release planned?

### ISSUE THREAD

**Issue by roeap** [Azure/azure-sdk-for-rust#967]
In some other projects (specifically arrow-/delta-rs) we are looking to improve our azure object store implementation. Currently this is somewhat blocked by some issues with azurite, that are already fixed on main. Additionally, the storage clients recently underwent some great improvements, that would would love to leverage as well.

Do you already have an ETA for the next release, maybe @ctaggart knows? 😄  

Thanks!

**Comment by cataggar** [comment]
Hi @roeap, thanks for letting us know. Currently waiting for:

- [ ] #802
- [ ] #964
- [ ] #965

Hopefully within a week or two. Assistance on #802 would speed things up.

**Comment by roeap** [comment]
Thanks @cataggar - I could give IoT Hub a try, as i need to understand that API a bit better anyhow. Will also post in the tracking issue.

**Comment by cataggar** [comment]
@roeap, published earlier today. https://github.com/Azure/azure-sdk-for-rust/releases/tag/v2022-08-09
