### ISSUE TITLE
parsing error in headers

### ISSUE THREAD

**Issue by rajasekarv** [Azure/azure-sdk-for-rust#976]
Default parse method from chrono fails on this timestamp returned in response headers

```
use chrono::{DateTime, FixedOffset, Utc};

fn main() {
    let datestr = "Thu, 04 Aug 2022 12:50:56 GMT";
    let date = DateTime::parse_from_rfc2822(datestr);
    println!("{:?}", date);
    let s: DateTime<FixedOffset> = datestr.parse().unwrap();
}
```

In essense,
https://github.com/Azure/azure-sdk-for-rust/blob/c8ccf8d34872613db5a5b521dc22f3dbc407b119/sdk/core/src/headers/utilities.rs#L19

should be changed similar to 
https://github.com/Azure/azure-sdk-for-rust/blob/c8ccf8d34872613db5a5b521dc22f3dbc407b119/sdk/core/src/headers/utilities.rs#L32

Is there any reason why `last_modified_from_headers_optional` method was using default parse method and the `last_modified_from_headers` method is using different parsing method?

**Comment by rajasekarv** [comment]
If my suggestion is correct, let me know and I can raise a PR with fix

**Comment by ctaggart** [comment]
The code you linked are both using rfc1123 which is the correct format for `"Thu, 04 Aug 2022 12:50:56 GMT"`.  The `main` branch no longer uses `chrono`. It was switched to `time` 3 days ago #965. Can you test the latest from `main`?

**Comment by rajasekarv** [comment]
ya with the main branch it looks fine. Thanks for the response. 

Maybe not the right place to ask, but I have one more question. Why when reading from blob, response includes the full data as bytes, instead of stream of bytes. I think reqwest allows us to stream from the response. So why to provide the full data, as it can easily lead to spike in RAM usage for large blobs.

**Comment by cataggar** [comment]
Great! New issue for the other issue please.
