### ISSUE TITLE
Expose streaming for operations with potentially large data

### ISSUE THREAD

**Issue by rajasekarv** [Azure/azure-sdk-for-rust#981]
When reading from blob, response includes the full data as bytes, instead of stream of bytes. It can easily lead to spike in RAM usage for reading large blobs. Reqwest and hyper allows us to stream bytes from the response. 

Is there any reason for this? or is this already in road map?

**Comment by rylev** [comment]
Thanks! This is indeed supported at the lowest level of the SDKs but is not being exposed for use by end users.

As an example, the `get_blob` operation returns a `GetBlobResponse` which has a field `data` which is just a `Bytes` collection. This is created by running the stream we get back from the transport layer eagerly through a `collect_pinned_stream` function which collects the stream into a `Bytes` collection.

We *could* expose the stream directly to the user, but I think this would be a bad idea in its current form. The stream is of type `Pin<Box<dyn Stream<Item = crate::Result<Bytes>> + Send + Sync>>` which is pretty unwieldy to use. I think we'll want to consider creating a wrapper type that allows both streaming and collecting into a `Bytes` collection.

**Comment by nlfiedler** [comment]
Same for `put_block_blob` as well, right? Any data, regardless of size, will need to be read entirely into memory. The other cloud providers have this covered so I am surprised that this SDK does not.
