### ISSUE TITLE
Add status query for service bus queues

### ISSUE THREAD

**Issue by mario-guerra** [Azure/azure-sdk-for-rust#989]
The service bus crate is lacking a few features. The most glaring is the ability to query the queue to find out how many messages are pending in the queue. This feature should be added.

**Comment by cataggar** [comment]
I think we should recommend the AMQP based azservicebus. #1429

**Comment by minghuaw** [comment]
The `ServiceBusAdministrationClient` in the dotnet SDK seems to be using HTTP instead of AMQP for status query
