### ISSUE TITLE
Add dead letter queue support to service bus crate

### ISSUE THREAD

**Issue by mario-guerra** [Azure/azure-sdk-for-rust#990]
The service bus crate does not appear to offer any way to query the dead letter queue in a service bus client. This feature should be added.

**Comment by minghuaw** [comment]
Is there a specification on how to complete a DLQ message with AMQP 1.0? 

It seems like the dotnet sdk uses the `"x-opt-lock-token"` as the delivery tag. However, I have made an example which simply uses the delivery tag of the DLQ message itself, and the example seems to work fine. 

https://github.com/minghuaw/fe2o3-amqp/blob/main/examples/service_bus/src/bin/queue_dlq.rs

**Comment by cataggar** [comment]
I think we should recommend the AMQP based azservicebus. #1429
