### ISSUE TITLE
Message read and peek missing message info

### ISSUE THREAD

**Issue by mario-guerra** [Azure/azure-sdk-for-rust#991]
Reading or peeking at a message does not provide a way to read message info like message ID, timestamp, label, or anything else. This information should be accessible in the object returned by a read or peek query.

**Comment by cataggar** [comment]
If the REST API is continued to be used, then this may be the API
https://docs.microsoft.com/en-us/rest/api/servicebus/peek-lock-message-non-destructive-read

**Comment by cataggar** [comment]
I think we should recommend the AMQP based azservicebus. #1429
